try{
var utf=function(a,b){for(var c=b?a.wa:a.ra,d=0,e;e=c[d];d++)if(DD(a.Oa,e.Xd(),e.wj(),e.getName()).Xn(8))return!0;return!1},gR=function(a,b){return a.getAll(void 0,!1,b).length},vtf=function(a){if(a.Fl()&&a.ha&&a.ha.Bc()){var b=W3d(a.ha,a.Xd());a=T3d(a.ha);for(var c=a.Yd();0<c.length;){var d=c.pop(),e=iG(d);a.set(e,a.get(d))}b&&(b=iG(b));return a.get(b)}if(r7d(a)&&a.ha)for(a=a.ha.uc(),b=a.Ku(),c=0;c<b;c++)if(d=a.uo(c),d.get(4,""))return d.get(4,"");return null},wtf=function(a){this.mb=a;this.ha=new U3d(a)};
wtf.prototype.jya=function(a){return DD(this.mb,a.Xd(),a.wj(),a.getName()).Xn(4)};wtf.prototype.getName=function(a){return DD(this.mb,a.Xd(),a.wj(),a.getName()).getName()};var xtf=function(a,b){return DD(a.mb,b.Xd(),b.wj(),b.getName()).kba()};wtf.prototype.Rn=function(a){return a.Fl()?this.ha.Rn(a.Xd()):""};fi(K.Ma(),"rpw");
var ytf=function(a){switch(a){case 1:return"calendarFrom";case 2:return"doclistFrom";case 3:return"threadlistFrom";case 4:return"updatesFrom";case 0:return"attachmentsFrom";default:throw"Unrecognized data type";}};var hR=function(a,b){WA.call(this,ytf(b),a)};r(hR,WA);var ztf=function(a,b){var c=ok(a).Fb,d=ytf(b);return c.Pb(d,!0)},Btf=function(a,b,c){a.Pb(b).set(new Atf(c))},Ctf=function(a,b){var c=a.Pb(b),d=q()-6E5;return c.Dj()&&c.xWa>d};hR.prototype.getData=function(a){return(a=this.Pb(a).get())?a.data:null};hR.prototype.Pb=function(a,b){var c=XA(this,a);c||b||(c=new fB(a,this,!0));return c};var Atf=function(a){this.data=a};Atf.prototype.tZ=function(){};
var Etf=function(a){D(this,a,"rpa",-1,Dtf,null)};r(Etf,C);var Dtf=[1];H("rpa",Etf);Etf.prototype.wa=function(){return bh(this,Ftf,1)};var Ftf=function(a){D(this,a,0,-1,null,null)};r(Ftf,C);Ftf.prototype.getTitle=function(){return E(this,3)};Ftf.prototype.setTitle=function(a){G(this,3,a)};Ftf.prototype.Jm=function(){return null!=E(this,3)};Ftf.prototype.My=function(){return E(this,4)};
var Htf=function(a){D(this,a,"rpd",-1,Gtf,null)};r(Htf,C);var Gtf=[1,2];H("rpd",Htf);Htf.prototype.B6=function(a,b){return eh(this,2,a,Itf,b)};var Jtf=function(a){D(this,a,0,-1,null,null)};r(Jtf,C);Jtf.prototype.getTitle=function(){return E(this,3)};Jtf.prototype.setTitle=function(a){G(this,3,a)};Jtf.prototype.Jm=function(){return null!=E(this,3)};var Itf=function(a){D(this,a,0,-1,null,null)};r(Itf,C);f=Itf.prototype;f.getTitle=function(){return E(this,2)};f.setTitle=function(a){G(this,2,a)}; f.Jm=function(){return null!=E(this,2)};f.Un=function(){return E(this,3)};f.cF=function(){return E(this,4)};f.vT=function(a){G(this,4,a)};
var Ltf=function(a){D(this,a,"rpt",-1,Ktf,null)};r(Ltf,C);var Ktf=[2];H("rpt",Ltf);Ltf.prototype.Au=function(){return E(this,1)};Ltf.prototype.p5=function(a){G(this,1,a)};var Mtf=function(a){D(this,a,0,-1,null,null)};r(Mtf,C);Mtf.prototype.Re=function(){return E(this,2)};Mtf.prototype.Mi=function(){return E(this,3)};Mtf.prototype.Eq=function(a){G(this,3,a)};Mtf.prototype.zR=function(){return null!=E(this,3)};
var Ntf=function(a,b,c){lB.call(this,a,43);this.ha=b;this.tf=c;a=Al(a);RA(this,a.ow())};r(Ntf,lB);Ntf.prototype.Sk=function(){return!1};Ntf.prototype.Sc=function(a){Ntf.Ea.Sc.call(this,a);rl(a,"FAIL");Rx(a,!0);ul(a,"view","rpa");ul(a,"address",this.ha);ul(a,"num",3)};Ntf.prototype.Rl=function(a,b,c){"rpa"==b&&(a=new Etf(c),this.tf(a))};
var Otf=function(a,b,c){var d='<div id="'+O(a.id)+'"><div class="anU"><table cellpadding="0" class="cf an6" id="'+O(a.id)+'"><tbody>';b=a.rows;for(var e=b.length,g=0;g<e;g++){var h;h=vi({vAc:0==g,PAc:1==g,mVa:g==e-1},b[g]);var l=c;h=""+('<tr id="'+O(h.wz)+'" class="anX '+(h.Bq?" "+O(h.Bq)+" ":"")+(h.vAc?" an0":"")+(h.PAc?" anZ":"")+(h.mVa?" anY":"")+' anW" title="'+Ai("Show recent activity")+'"><td class="anB"><div><div class="anz">'+M(PC({Dx:h.SHb,yd:h.yd},null,l))+'</div></div></td><td class="aoa"><div dir="'+
O(h.hq)+'" class="anF" tabindex="0">'+M(h.text)+'</div></td><td class="amZ"><div class="amY">&raquo;</div></td></tr>');h=L(h);d+=h}d+="</tbody></table></div>";a.A9c?(d+='<div id="'+O(a.IEa)+'" class="an4 e"><span tabindex="0" role="link">',0<a.Hyb?(a="Show "+(M(a.Iyb)+" more"),d+=a):d+="Show details",d+="</span></div>"):0<a.Hyb&&(a=M(a.Iyb)+" more",d+='<div class="anH">'+a+"</div>");return L(d+"</div>")},Qtf=function(a,b,c){a=a||{};return L('<div class="anI">'+Ptf(a,null,c)+"</div>")},Ptf=function(a){var b=
L,c='<img name="'+O(a.YX)+'" jid="'+O(a.jid)+'" src="'+O(Fi(a.url))+'" alt="';return b(c+O(ui(""+(""+a.name+"'s profile photo")))+'" class="'+O(a.CCb)+'"/>')},Rtf=function(a,b,c){var d;d=""+('<div id="'+O(a.id)+'" class="'+(a.className?" "+O(a.className)+" ":"")+'"><div class="an7"><div class="an9">'+M(a.fX)+'</div><div id="'+O(a.IEa)+'" class="an8 e">Show more</div></div><table cellpadding="0" class="cf an6"><tbody>');a=a.rows;b=a.length;for(var e=0;e<b;e++){var g;g=vi({mVa:e==b-1},a[e]);var h=c;
g=L('<tr id="'+O(g.wz)+'" class="anX '+(g.Bq?" "+O(g.Bq)+" ":"")+" "+(g.mVa?" anY ":"")+'"><td class="anB">'+M(PC(g,null,h))+'</td><td dir="'+O(g.hq)+'" class="aoa"><span tabindex="0" '+(g.Wi?' title="'+O(g.Wi)+'" ':"")+">"+M(g.text)+"</span></td></tr>");d+=g}return L(d+"</tbody></table></div>")},Ttf=function(a,b,c){b=L;var d=(a.N2?L('<div id="'+O(a.N2)+'" class="azg">'+(a.W_c?'<div class="aQU J-J5-Ji">'+M(a.V_c)+"</div>":'<div class="azh J-J5-Ji"></div><div id="'+O(a.RJa)+'" class="am5 J-J5-Ji e" tabindex="0" role="link"></div>')+
"</div>"):"")+'<div id="'+O(a.id)+'" class="anr">',e,g=a.profile;e=L;var h='<div id="'+O(g.id)+'" class="anL"><table class="cf an5" id="'+O(g.id)+'"><tbody><tr><td rowspan="3" class="anS"><div id="'+O(g.S1c)+'" class="anR"></div></td><td dir="'+O(g.hq)+'" class="anQ"><span id="'+O(g.R1c)+'" title="'+O(g.name)+'">'+M(g.name)+'</span></td></tr><tr><td id="'+O(g.Eic)+'" class="anO"></td></tr><tr><td class="a0F">';if(g.E8c)var g=g.Xu,l="Email "+g.nhb,n="Start a video call with "+g.nhb,g=""+('<div class="yX5eO"><div class="J-J5-Ji anm">'+
(g.fdd?iR({Ym:g.tdb,disabled:!1,HKa:N("aJj"),hQ:N("aWK")},null,c):iR({Ym:g.tdb,disabled:!1,HKa:N("and"),hQ:N("ane")},null,c))+iR({Ym:g.Q7b,disabled:!1,title:N(""+n),hQ:N("Gq")},null,c)+iR({Ym:g.R7b,disabled:!1,title:N(""+l),hQ:N("ank")},null,c)+iR({Ym:g.S7b,disabled:!1,title:N("More actions"),hQ:N("anl")},null,c)+"</div></div>"),g=L(g);else g="";e=e(h+g+"</td></tr></tbody></table></div>");return b(d+e+"<div>"+(a.mP?Stf(a,null,c):"")+"</div></div>")},Utf=function(a){var b="";a.SEc?(a="People ("+(M(a.aYa)+
")"),b+=a):0<a.Nyb?(a=M(a.aYa)+" more",b+=a):b+="More";return L(b)},Vtf=function(a){var b='<div id="'+O(a.id)+'" class="am0"><div class="an7"><div class="an9">'+M(a.fX)+'</div></div><div class="am3">';a=a.rows;for(var c=a.length,d=0;d<c;d++){var e;e=a[d];e=L('<div id="'+O(e.TRc)+'" tabindex="0" class="am4 J-J5-Ji"><img src="'+O(Fi(e.xyc))+'" alt="'+O(e.title)+'" title="'+O(e.title)+'" class="am1" /></div>');b+=e}return L(b+"<div></div>")},Stf=function(a){a=""+('<div id="'+O(a.Fwb)+'" class="anD">Loading...</div>');
return L(a)},Wtf=function(a){a=""+('<div id="'+O(a.id)+'" class="an3 e"><span tabindex="0" role="link">Show details</span></div>');return L(a)},iR=function(a,b,c){return L(M(Zj({style:4,id:a.Ym,disabled:a.disabled,title:a.title,className:N("am7 T-I-awG"+(a.HKa?" "+a.HKa:"")),content:xi('<span class="ann">&nbsp;</span>'+M(PC({yd:N("anj T-I-J3"+(a.hQ?" "+a.hQ:""))},null,c)))},null,c)))},Xtf=function(a,b,c){b=L;var d='<div id="'+O(a.id)+'" class="anu">',e;e=(e=a.toolbar)||{};var g;g="";g=e.UH?g+"Start a hangout":
g+"Start group chat";g='<div class="yX5eO"><div class="J-J5-Ji anm">'+iR({Ym:e.goc,title:N(g),hQ:N("anE Hi o3"+(e.UH?" aWs":""))},null,c);e.szc&&(g+=iR({Ym:e.FCc,disabled:!1,title:N("Email this group"),hQ:N("ank")},null,c)+iR({Ym:e.wDc,disabled:e.vDc,title:N("Schedule a meeting with group"),hQ:N("an1")},null,c));e=L(g+"</div></div>");e=L(""+('<div class="anv"><table class="cf an5"><tr><td class="anw">People</td><td class="anx">'+e+"</td></tr></table></div>"));return b(d+e+Otf(a.B5c,null,c)+"</div>")}, Ytf=function(){return L('<div class="am6"></div>')};
var jR=function(a){this.ra=a};r(jR,il);f=jR.prototype;f.vob=ll();f.GNb=ll();f.wJb=ol();f.Vbb=ll();f.dispose=ol();f.w_a=ol();f.TMb=ll();f.qDa=ll();f.PMb=ll();f.uxb=ll();f.R1=ll();f.pbb=ol();f.ccb=ll();f.Qqb=ll();f.Orb=ll();f.jzb=ol();f.eFb=ll();var kR=function(a,b,c){Cy.call(this,a);pl(this);this.Ha=b;this.ra=c;this.Ub=tA(a);this.Ae=zB(a);this.Za=new hG(a);this.Ja=new wtf(a);this.Ht=Al(a);this.Tg=a.get(Rk);this.Aa=YB(a);this.lE=QD(a);this.Ws=eo(a).wa;this.Va=new ki(!1);this.Fa=[];this.Sd={};this.He={};this.Iq=(c=pk(this.Ha.Kd()))?c.qb("fpu"):"";this.lj=this.Ub.Hg(5598);this.Hi=this.Ub.Hg(5379);this.pj=this.Ub.Hg(5381);this.qg=this.Ub.Hg(5724);this.HF=this.Ub.Hg(5894);this.Db=vG(a).UH();this.XA=this.Ub.Hg(5987);this.rr=this.Ub.Hg(6005);this.Qb=
ztf(a,0);this.Qf=ztf(a,1);this.Md=ztf(a,2);this.Kc=ztf(a,3);this.Fc=[];this.nb=this.Ra=this.Yb=!1;this.z_=this.i6=null;this.Uh=1E4<q()-b.xWa;Ng(this.getHandler().listen(this.Ba(),"mouseover",this.qG).listen(this.Ba(),"mouseout",this.nE),this.Ba(),ym,this.ih,!0);this.getHandler().listen(this.ra,"md",this.Zp);Qi(this);this.Og=a.Nc("F4zhRb")};r(kR,Cy);jl(jR,kR);var Ztf=[],$tf=new Gn(1);
kR.prototype.Ua=function(){kR.Ea.Ua.call(this);if(auf(this)){this.ha=this.ra.getAll(void 0,!1,!0)[0];this.Wa.uxb(this.ra)?buf(this,!0):buf(this,1<gR(this.ra,!0));qn(this.Ba(),"anT");var a=new GD(this.getContext());oi(a.Ba(),Ytf);this.tb(a)}};
var cuf=function(a,b){for(var c=Af(a.Ka(),"DIV","T-I",b),d,e=0;d=c[e];e++){var g=d.id==a.hb(lR(a,"bmo"));tz(d);g?(g=new qm(null,null,ak.Ma(),a.Ka()),g.Tb(d),Uj(g,64,!0),a.getHandler().listen(g,"open",a.Gh),g.Js=m(w_d,g,g,null,null,13,12,void 0),a.kd=g,a.ha&&a.ha.Fl()||g.setVisible(!1)):(g=new Am(null),g.Tb(d),g.getId()==a.hb("gc")&&(a.Ie=g,utf(a.ra,!0)||g.setVisible(!1)),a.yc||g.getId()!=a.hb("me")||(a.yc=g),g.getId()==a.hb(lR(a,"bch"))&&(a.Ta=g),g.getId()==a.hb(lR(a,"bhg"))&&(a.Xc=g,g.setVisible(!1)),
g.getId()==a.hb(lR(a,"bma"))&&(a.Ca=g,a.ha&&a.ha.Fl()||g.setVisible(!1)));d!=d.parentNode.firstChild&&qn(d,"T-I-Js-Gs");d!=d.parentNode.lastChild&&qn(d,"T-I-Js-IF");a.Fc.push(g)}};kR.prototype.Nb=function(){kR.Ea.Nb.call(this);this.Wa.dispose();for(var a,b=0;a=this.Fc[b];b++)a.dispose();this.Fc.length=0;this.kd=this.Ca=this.Xc=this.IP=this.Ta=this.yc=this.Ie=null;x(this.Ia);this.Ia=null;Xh(this.ef);this.Cb=null};kR.prototype.mE=function(){this.Wa.w_a()};
var auf=function(a){return 0==gR(a.ra,!0)||!a.Wa.PMb(a.ra)&&a.Ha.get().WPa()?!1:!0};kR.prototype.$b=function(){return auf(this)};kR.prototype.Zp=function(){if(!this.Wa.Orb(this.ra)){if(this.Ie){var a=utf(this.ra,!0);this.Ie.setVisible(a)}for(var a=this.ra.getAll(void 0,!1,!0),b,c=0;b=a[c];c++){var d=b;if(b=this.Ba(lR(this,"pi",d)))d=DD(this.getContext(),d.Xd(),d.wj(),d.getName()).j4(),b.className=d.Gm}this.ha&&(this.Db?duf(this):euf(this))}this.ha&&fuf(this);guf(this)};
var duf=function(a){var b=a.ha.getName()||"",c=DD(a.getContext(),a.ha.Xd(),a.ha.wj(),b),d=c.Xn(4),c=c.Xn(5);d||c?(a.Ta.setVisible(!0),a=a.Ta.Ba(),c?(jz(a,"aWK","ang"),a.title="Invite "+(b+" to chat")):(jz(a,"ang","aWK"),a.title="Hangout with "+b),tz(a)):a.Ta.setVisible(!1)},euf=function(a){var b=a.ha.getName()||"",c="Chat with "+b,d="Send "+(b+" an SMS"),e=huf(a,a.ha);a.Ta.setVisible(1!=e);a=a.Ta.Ba();rn(a,"ang","anb","anf","anc","ani","anh","and");switch(e){case 3:a.title="Invite "+(b+" to chat");
tz(a);qn(a,"ang");break;case 4:a.title=c;tz(a);qn(a,"anb");break;case 5:a.title=c;tz(a);qn(a,"anf");break;case 6:a.title=c;tz(a);qn(a,"anc");break;case 7:a.title=d;tz(a);qn(a,"ani");break;case 2:a.title=c;tz(a);qn(a,"anh");break;default:a.title="",tz(a),qn(a,"and")}},fuf=function(a){var b=vtf(a.ha),c=a.Ba(lR(a,"pn")),d=a.Ba(lR(a,"pp"));if(c){rf(c,a.ha.getName().replace(/ \.$/,""));c.setAttribute("title",a.ha.getName());if(!b)return;qn(c,"e");c.setAttribute("tabindex",0)}b&&d&&qn(d,"Gr")},huf=function(a,
b){var c=b.Xd(),d=b.wj(),e=b.getName(),c=DD(a.getContext(),c,d,e);if(c.Xn(5))return 3;if(!c.Xn(4))return 1;switch(c.yY()){case 2:case 6:return 4;case 3:return 5;case 4:return 6;case 7:return 7;case 1:case 5:return 2;default:return 1}},guf=function(a){if(a.Ia){var b=a.ha.Xd(),c=a.Ia.Ic(),d=a.hb(lR(a,"mm")),e=!!a.Ja.Rn(a.ha)&&!xtf(a.Ja,a.ha);c.Pb(d+" de").setVisible(e);e=!e&&!a.Ja.Rn(a.ha)&&!xtf(a.Ja,a.ha)&&a.ha.Fl();c.Pb(d+" ac").setVisible(e);e=a.ha;e=DD(a.Ja.mb,e.Xd(),e.wj(),e.getName());e=e.Xn(0)&&
e.Xn(6);c.Pb(d+" vc").setVisible(e);var e=a.getContext().Nc("t1Wg0"),g=a.HF&&!!e&&4==e.ra(b),h;if(h=!!e&&!g)h=a.ha,h=DD(a.Ja.mb,h.Xd(),h.wj(),h.getName()).Xn(4);c.Pb(d+" qc").setVisible(h||g);c.Pb(d+" gpbl").setVisible(g);c.Pb(d+" au").setVisible(h);c.Pb(d+" pi").setVisible(h);c.Pb(d+" hi").setVisible(h);c.Pb(d+" bl").setVisible(h);if(h){var l;switch(e.ra(b)){case 0:l="au";break;case 1:l="pi";break;case 2:l="hi";break;case 3:l="bl"}iuf(a,l)}}},kuf=function(a){var b;a:{b=a.ra.getAll(void 0,!1,!1);
for(var c=0;c<b.length;c++)if(!b[c].Fl()){b=!1;break a}b=!0}b={id:a.hb("gr"),B5c:juf(a),toolbar:{goc:a.hb("gc"),szc:b,vDc:Gz(),wDc:a.hb("me"),FCc:a.hb("gm"),UH:a.Db}};c=new GD(a.getContext());oi(c.Ba(),Xtf,b);a.ri(c,0);cuf(a,c.Ba());b=a.nb?a.ra.getAll(void 0,!1,!0):a.ra.getAll(5,!1,!0);MG(a.ra,b,m(a.eh,a))},juf=function(a){var b=[],c=gR(a.ra,!0),d;if(a.nb){d=SD(a.lE);var e=zh(a.Ba());d=Math.floor((d.clientHeight-e-40)/30);d!=c&&--d}else d=5;for(var e=0,g=a.ra.getAll(void 0,!1,!0),h,l=0;(h=g[l])&&
e!=d;l++)e++,b.push(luf(a,h));c-=e;return{id:a.hb("ro"),rows:b,IEa:a.hb("smg"),A9c:!a.nb&&0<c,Hyb:c,Iyb:$tf.format(c)}},luf=function(a,b){var c=lR(a,"rr",b),d=lR(a,"pi",b);a.Fa.push(c);a.Fa.push(d);var e=b.Xd(),g=DD(a.getContext(),e,b.wj(),b.getName()).j4();return{wz:a.hb(c),SHb:a.hb(d),yd:g.Gm,jid:e,text:b.getName(),hq:a.Va.hq(b.getName()||"")}},buf=function(a,b){var c=new GD(a.getContext()),d=!a.Ne&&b?a.hb("h"):null,e=a.hb("ba"),g=a.ha.Xd(),h=lR(a,"pn"),l=lR(a,"pp");a.Fa.push(h);DD(a.getContext(),
g,a.ha.wj(),a.ha.getName()).j4();var n=!a.Wa.Qqb(),d={id:a.hb(lR(a,"de")),N2:d,RJa:e,Nyb:gR(a.ra,!0),aYa:$tf.format(gR(a.ra,!0)),Fwb:a.hb(lR(a,"lo")),mP:!!a.Wa.R1()||!!a.ha.Xd(),profile:{id:a.hb(lR(a,"pr")),R1c:a.hb(h),S1c:a.hb(l),Eic:a.hb(lR(a,"focp")),name:a.ha.getName(),E8c:n,Xu:{nhb:a.ha.getName(),fdd:a.Db,tdb:a.hb(lR(a,"bch")),R7b:a.hb(lR(a,"bma")),Q7b:a.hb(lR(a,"bhg")),S7b:a.hb(lR(a,"bmo"))}}};a.Wa.pbb(d);oi(c.Ba(),Ttf,d);a.ri(c,Math.max(0,a.Vi()-1));n&&(cuf(a,c.Ba()),a.Db?duf(a):euf(a));fuf(a);
c=a.ha.Fl(!0);n=a.Wa.R1();c?(a.Sd[g]=[],a.ef=Wh("Ag`"+g,m(a.Of,a,g,!0),1E4)):n&&(a.Sd[n]=[]);b&&!a.Ne&&(d=a.ra.getAll(10,!1,!0),MG(a.ra,d,m(a.En,a,d,{})));a.Ne=!0;muf(a);(c||n)&&nuf(a);c&&(Ctf(a.Qb,g)?mR(a,g,[0],2):ouf(a,g),a.Ra&&puf(a))};
kR.prototype.Gh=function(a){if(!this.Ia){var b=this.hb(lR(this,"mm")),c=[],d=XF(this.ha.ha.uc().Bc());if(d){var e=d.ll();if(e)for(var g=0;g<e;g++){var h=d.Mc(g),l=h.get(2,1),n=h.qb();c.push({eo:n,type:l,Aib:h.get(3,""),e$c:7==l||18==l})}}if((d=this.getContext().Nc("pLPUQe"))&&d.ra()){d=this.hb(lR(this,"mm"));e=[];for(h=0;g=c[h];h++)e.push({id:d+" c "+h,action:"Call",ACb:g.eo,rY:X3d(g.type,g.Aib),lGa:!1});d=e}else d=[];if((e=this.getContext().Nc("ciN9Rb"))&&e.Kdb()){e=this.hb(lR(this,"mm"));g=[];for(l=
0;h=c[l];l++)h.e$c&&g.push({id:e+" s "+l,action:"SMS",ACb:h.eo,rY:X3d(h.type,h.Aib),lGa:!1});e=g}else e=[];d.length&&(d[0].lGa=!0);e.length&&(e[0].lGa=!0);this.Cb=[];for(h=0;g=c[h];h++)this.Cb[h]=g.eo;d={E5b:b+" ac",S7:b+" de",G6a:b+" vc",U3c:b+" rc",zCb:Cb(d,e),z3c:b+" qc",dkc:b+" gpbl",ekc:i2e(),d7b:b+" au",MTc:b+" pi",xxc:b+" hi",E7b:b+" bl"};b=this.Ka().Na("DIV",{"class":"E"});this.Ba(lR(this,"de")).appendChild(b);c=this.getContext();l=""+('<div id="'+O(d.E5b)+'" class="J-N">Add to contacts</div><div id="'+
O(d.S7)+'" class="J-N">Edit contact details</div><div id="'+O(d.G6a)+'" class="J-N">Start video chat</div><div id="'+O(d.U3c)+'" class="J-N">Recent mail from</div>');if(d.zCb)for(e=d.zCb,g=e.length,h=0;h<g;h++)var n=e[h],p="",w=M(n.action)+(' <span dir="ltr">'+(M(n.ACb)+("</span> ("+(M(n.rY)+")")))),p=p+('<div id="'+O(n.id)+'" class="J-N '+(n.lGa?"anK":"")+'">'+w+"</div>"),n=L(p),l=l+n;l+='<div id="'+O(d.z3c)+'" class="J-N J-N-JE anK">Show in chat list:</div><div id="'+O(d.dkc)+'" class="J-N J-N-JE">'+
M(PC({yd:N("anJ")},null,void 0))+M(d.ekc)+'</div><div id="'+O(d.d7b)+'" class="J-N J-Ks">'+M(PC({yd:N("anJ")},null,void 0))+'Auto</div><div id="'+O(d.MTc)+'" class="J-N J-Ks">'+M(PC({yd:N("anJ")},null,void 0))+'Always show</div><div id="'+O(d.xxc)+'" class="J-N J-Ks">'+M(PC({yd:N("anJ")},null,void 0))+'Never show</div><div id="'+O(d.E7b)+'" class="J-N J-Ks">'+M(PC({yd:N("anJ")},null,void 0))+"Block</div>";d=L(l);this.Ia=new pF(c,b,d);a.target.aj(this.Ia.Ic());this.getHandler().listen(this.Ia.Ic(),
"action",this.Yp);guf(this)}};kR.prototype.eh=function(a){if(this.jd()){var b=a.Xd(),c=this.Ba(lR(this,"rr",a));if(c){var d=a.Kn();if(d){var d=quf(this,d,24),e=Af(this.Ka(),"TD","amZ",c)[0];oi(e,Qtf,{url:d,YX:this.Tg.ha,jid:b,name:a.getName(),CCb:"aNM"});qn(c,"Xtcpwc")}}}};
var suf=function(a,b,c){var d=PE(a.getContext()),e=new C4d;e.dT(!0);xD(e,m(function(a){c.Fia=J1d(a);ruf(this,b,c)},a));gye(e,m(function(){c.Fia=null;ruf(this,b,c)},a));e.uL="FAIL";d.execute(e)},muf=function(a){var b={Fia:void 0,j1a:!1};a.Wa.TMb()&&t7d(a.ra)?suf(a,a.ha,b):b.Fia=null;MG(a.ra,[a.ha],m(function(a){this.ra&&(b.j1a=!0,ruf(this,a,b))},a))},ruf=function(a,b,c){if(c.j1a&&!b.getName())0==gR(a.ra,!0)?I(a.Ba(),!1):kuf(a);else if(k(c.Fia)&&c.j1a&&(c=c.Fia,a.jd())){var d=b.Kn(!0),e=a.Ba(lR(a,"pr",
b));if(d){var d=quf(a,d,64),g=Af(a.Ka(),"DIV","anR",e)[0];oi(g,Ptf,{url:d,YX:a.Tg.ha,jid:b.Xd(),name:b.getName(),CCb:"aNN"});qn(e,"anP")}a.qg&&a.Og&&b.wj()&&a.Xc&&DD(a.getContext(),b.Xd(),b.wj(),b.getName()).Xn(1)&&a.Xc.setVisible(!0);(d=b.Fl())&&a.Ca&&a.Ca.setVisible(!0);d&&a.kd&&a.kd.setVisible(!0);d=a.Ba(lR(a,"focp"));a.Wa.qDa(b,c,d)||(b=(c=lK(jK(b.ha),[]))&&c.getTitle()?c.getTitle():c&&c.getName()?c.getName():b.Fl()?b.Xd():"",qn(d,"anN"),d.dir=a.Va.hq(b||""),c=a.Ka().createElement("SPAN"),c.title=
b,rf(c,b),d.appendChild(c));fuf(a)}};kR.prototype.Wb=function(a){Xh(Ztf[a]);Ztf[a]=null};
var mR=function(a,b,c,d){for(var e=a.Sd[b],g=0;g<c.length;g++)e[c[g]]=d;1!=d&&Wh("Bg",m(a.Of,a,b,!1),0)},puf=function(a){if(a.ha.Fl()){var b=a.ha.Xd(),c=!1,d=a.Ra?5:3;if(Ctf(a.Kc,b)){var e=a.Kc.getData(b),g=bh(e,Mtf,2).length;if(d<=g||e.Au()==g)c=!0,mR(a,b,[3],2)}c||(a.pj?(c=new tuf(m(a.Ik,a,b)),c=new sl(a.Ht.ow(),c),rl(c,"FAIL"),le(c.wa,"rhspeople/threadlist/"),ul(c,"address",b),ul(c,"num",d),c.send(),mR(a,b,[3],1)):mR(a,b,[3],0));Ctf(a.Md,b)?mR(a,b,[1,2],2):a.Hi?(d=new tuf(m(a.uj,a,b)),d=new sl(a.Ht.ow(),
d),rl(d,"FAIL"),le(d.wa,"rhspeople/details/"),ul(d,"address",b),d.send(),d=[1,2],mR(a,b,d,1)):(d=[1,2],mR(a,b,d,0))}},nuf=function(a){var b;b=a.Wa.R1()||a.ha.Xd();a.Wa.Vbb(b)?mR(a,b,[4],2):!a.lj||!a.Yb&&Ztf[4]?mR(a,b,[4],0):(Ztf[4]=Wh("Cg",m(a.Wb,a,4),1E4),a.Wa.vob(b,m(a.$p,a,b),!a.Yb)?mR(a,b,[4],1):mR(a,b,[4],0))};kR.prototype.$p=function(a,b){this.Wb(4);mR(this,a,[4],b?2:3)};
var ouf=function(a,b){a.Yb||a.Uh&&!Ztf[0]?(Ztf[0]=Wh("Dg",m(a.Wb,a,0),1E4),(new Ntf(a.getContext(),b,m(a.sj,a,b))).send(),mR(a,b,[0],1)):mR(a,b,[0],0)};
kR.prototype.En=function(a,b,c){if(this.jd()){var d=c.Xd()||c.wj();b[d]=c.Kn();if(bc(b)==a.length)if(d=gR(this.ra,!0),0==d)I(this.Ba(),!1);else if(1!=d){var e=c=0,g;for(g in b)b[g]&&e++;if(1<e)for(g=Af(this.Ka(),"*","azh",this.Ba())[0],e=0;e<a.length;e++){var h=a[e].Xd()||a[e].wj(),l=b[h];if(l){var l=quf(this,l,24),n=a[e].getName(),p=this.Ka().createElement("IMG");p.id=this.hb("hp "+h);p.className="azi";p.src=l;p.setAttribute("data-tooltip",n);p.setAttribute("aria-label",n);p.setAttribute("role",
"link");p.setAttribute("tabindex",0);g.appendChild(p);c++}if(4==c)break}a=d-c;b=this.Ba("ba");oi(b,Utf,{SEc:0==c,Nyb:a,aYa:$tf.format(a)})}}};kR.prototype.Ik=function(a,b){Btf(this.Kc,a,b);mR(this,a,[3],2)};kR.prototype.uj=function(a,b){Btf(this.Qf,a,{ZHd:bh(b,Itf,2),Aa:E(b,3)});Btf(this.Md,a,bh(b,Jtf,1));mR(this,a,[1,2],2)};var vuf=function(a,b,c,d){var e=uuf(a,b,d,null);b=e[0]+": Free";e=e[1];c="cs "+c+" "+d;a.Fa.push(c);return{wz:a.hb(c),Bq:"anq",yd:"",hq:a.Va.hq(b||""),text:b,Wi:e}};
kR.prototype.sj=function(a,b){this.Wb(0);Btf(this.Qb,a,b);mR(this,a,[0],2)};kR.prototype.YI=function(a){a=a.target;var b=50/a.height;if(64>=a.width&&50>=a.height){var c=a.parentNode;c.style.width=a.width+"px"}else if(1.28<a.width/a.height)b=-Math.floor((a.width*b-64)/2),a.height=50,a.style.marginLeft=b+"px";else{var d=a.width;a.height=50;c=a.parentNode;c.style.width=d*b+"px"}a.style.visibility="visible"};
kR.prototype.Of=function(a,b){if(this.jd()&&!this.He[a]){var c=this.Sd[a],d=c[1],e=c[2],g=c[3],h=c[4],l=c[0],c=1!=h&&1!=l;this.Ra&&(c=c&&1!=g&&1!=d&&1!=e);if(c||b){c=0;2==h&&(c=this.Wa.GNb(a)?1:0);h=0;if((!c||this.Ra)&&2==l){var n=this.Qb.getData(a).wa();if(0==n.length)h=0;else{for(var h=[],l=[],p,w=0;p=n[w];w++){var z="at "+p.My()+" "+w;l.push(z);h.push({xyc:E(p,1),title:"View photo in message",TRc:this.hb(z)})}z="ats "+a;w={id:this.hb(z),fX:"Recent photos",rows:h};z=(z=this.Ba(z))?z.parentNode:
this.Ka().createElement("DIV");oi(z,Vtf,w);this.Ba("de "+a).appendChild(z);for(w=0;w<l.length;w++)z=this.Ba(l[w]).firstChild,this.getHandler().ud(z,"load",this.YI);h=h.length}}l=0;if(2==g)if(w=bh(this.Kc.getData(a),Mtf,2),z=this.Ha.get().hd(),1<w.length||1==w.length&&w[0].Re()!=z){for(var l=[],g=[],n=this.Ra?5:2,F=0;(p=w[F])&&l.length!=n;F++)if(p.Re()!=z){var J="th "+p.Re();this.Fa.push(J);var T=p.Mi()||"(no subject)";l.push({wz:this.hb(J),Bq:E(p,1)?"aod":"",yd:"aoc",hq:this.Va.hq(T||""),text:T,Wi:T});
g.push(E(p,4))}w="tl "+a;this.Fa.push(w);g={id:this.hb(w),IEa:this.hb("tlsm "+a),className:"aob",fX:wuf(this,g,3),rows:l};w=this.Ka().createElement("DIV");oi(w,Rtf,g);this.Ba("de "+a).appendChild(w);l=l.length}else l=0;g=0;2==d&&(z=this.Qf.getData(a),g=z.Aa,w=new Date,d=[],z[0]&&(n=z[0],p=uuf(this,w,n.Un(),n.cF()),F=n.getTitle()||"(no title)",z=p[0]+": "+F,p=p[1]+" \n"+F,n="ce "+E(n,1),this.Fa.push(n),d.push({wz:this.hb(n),yd:"anp",hq:this.Va.hq(z||""),text:z,Wi:p})),g&&d.push(vuf(this,w,a,g)),d.length?
(g={id:this.hb("ca "+a),className:"ano",fX:"Calendar and availability",rows:d},w=this.Ka().createElement("DIV"),oi(w,Rtf,g),this.Ba("de "+a).appendChild(w),g=d.length):g=0);d=0;if(2==e)if(w=this.Md.getData(a),0<w.length){e=[];d=[];for(n=0;z=w[n];n++)p="do "+E(z,2),this.Fa.push(p),e.push({wz:this.hb(p),yd:"",Ctb:E(z,1),hq:this.Va.hq(z.getTitle()||""),text:z.getTitle(),Wi:z.getTitle()}),d.push(E(z,4));w="dl "+a;this.Fa.push(w);d={id:this.hb(w),IEa:this.hb("dlsm "+a),className:"ans",fX:wuf(this,d,2),
rows:e};w=this.Ka().createElement("DIV");oi(w,Rtf,d);this.Ba("de "+a).appendChild(w);d=e.length}else d=0;c=c+l+g+d+h;e=this.Ba("de "+a);this.Ra||-1==a.indexOf("@")||(h=this.Ka().createElement("DIV"),oi(h,Wtf,{id:this.hb("smd "+a)}),e.appendChild(h));h=this.Ba("lo "+a);this.Ra&&(0==c||1==gR(this.ra,!0)&&this.Xp==c)?(rf(h,"No details"),e.appendChild(h.parentNode)):e.removeChild(h.parentNode);this.Xp=c;this.He[a]=!0;Xh(this.ef);xuf(this)}}};
var yuf=function(a,b){var c=b.Xd(),d=uG(a.getContext()),e=DD(a.getContext(),c,b.wj(),b.getName());return 7==huf(a,b)?(d.DY(a.getContext(),c),!0):a.Ja.jya(b)?(d.DS(a.getContext(),e,a.gF()),!0):!1};kR.prototype.gF=function(){if(this.rr)return null;for(var a=this.Ha.get().Yk(),b=a.length-1;0<=b;b--){var c=this.Ha.Pb(a[b]).Pb("message");if(c&&c.Ld()&&(c=c.get()))return c.gF()}return null};var zuf=function(a,b){var c=vtf(a.ha);c&&(a.Aa.wb(b),c=vA(c,$f()||"0"),c=a.Wa.ccb(c,b)||c,zl(c))};
kR.prototype.ih=function(a){this.Yb=!0;a:{a=a.target;for(var b=this.Ba();a.parentNode&&a!=b;){var c=Auf(this,a);if("rr"==c||"hp"==c||"pi"==c||"pn"==c||"pp"==c||"ba"==c||"gc"==c||"gm"==c||"th"==c||"at"==c||"ce"==c||"cs"==c||"do"==c||"me"==c||"bch"==c||"bma"==c||"bhg"==c||"bjg"==c||"smd"==c||"smg"==c||"tlsm"==c||"dlsm"==c)break a;a=a.parentNode}a=null}if(a)switch(b=Auf(this,a),b){case "rr":if(a=Buf(this,a))this.ha=a;Cuf(this);break;case "hp":if(a=Buf(this,a))this.Aa.wb(NEa),this.Ba(lR(this,"de")).style.display=
"none",this.ha=a,Duf(this);break;case "ba":this.Aa.wb(CEa);this.nb=!0;this.Wa.jzb();a=this.Ba(lR(this,"de"));b=this.Ba("gr");b||(kuf(this),b=this.Ba("gr"));a.style.display="none";b.style.display="";this.Ba("h").style.display="none";xuf(this);break;case "gc":this.Ha.xF()&&this.Db?(a=this.Ha.get().qha(),uG(this.getContext()).Lv(this.getContext(),a),a=!0):a=!1;a||(a=this.getContext(),uG(a).lZa(a,Xcf(this.ra,void 0,!0),this.gF()));break;case "gm":this.Aa.wb(REa);a=this.Ha.get().M1();for(var b=this.Za,
c=[],d=0;d<a.length;d++){var e=a[d];tA(b.Oa).Fl(dA(e.Xd()))||c.push(p3d(b,e.Xd(),e.getName()))}b.Ae.navigate({view:EC,Xw:c.join(","),Sf:lC});break;case "th":a=this.hh(a.id).split(" ")[1];this.Aa.wb(QEa);b="from:"+this.ha.Xd();b=Mz(b);this.Ae.navigate({view:DC,search:b,Tl:a});break;case "at":a=this.hh(a.id).split(" ")[1];this.Aa.wb(JEa);b="from:"+this.ha.Xd()+" filename:(jpg OR jpeg OR png)";b=Mz(b);this.Ae.navigate({view:DC,search:b,Tl:a});break;case "ce":this.Aa.wb(KEa);a=ce(this.hh(a.id).split(" ")[1],
"authuser",$f()||0);zl(a);break;case "cs":b=this.hh(a.id).split(" ");a=b[1];d=Number(b[2]);this.Aa.wb(LEa);b=this.Ha.get().yB();d?(c=new Ol(new Date(d)),d=new Ol(new Date(d+18E5)),a=SId([a],b,void 0,c.a_()+"Z/"+d.a_()+"Z")):a=SId([a],b);zl(a);break;case "do":this.Aa.wb(MEa);a=ce(this.hh(a.id).split(" ")[1],"authuser",$f()||0);zl(a);break;case "me":this.yc&&this.yc.isEnabled()&&(this.Aa.wb(VEa),a=this.Ha.get().yB(),b=new Ol,c=b.getMinutes(),0!=c&&30!=c&&b.add(new Ml("n",30<c?60-c:30-c)),b.setSeconds(0),
c=b.clone(),c.add(new Ml("h",1)),a=SId(Xcf(this.ra,void 0,!0),a,void 0,b.a_()+"Z/"+c.a_()+"Z"),zl(a));break;case "bch":this.Ta.isEnabled()&&(this.Aa.wb(TEa),!yuf(this,this.ha)&&this.ha.Fl()&&h2e(this.getContext()).ra(this.getContext(),this.ha.Xd()));break;case "bma":this.Aa.wb(UEa);q3d(this.Za,this.ha.Xd(),this.Ja.getName(this.ha));break;case "pp":zuf(this,aFa);break;case "pn":zuf(this,$Ea);break;case "smd":this.Aa.wb(fFa);this.Ra=!0;a=this.ha.Xd();b=this.Ba(lR(this,"de"));c=this.Ba("smd "+a);b.removeChild(c.parentNode);
c=this.Ka().createElement("DIV");oi(c,Stf,{Fwb:this.hb(lR(this,"lo"))});b.appendChild(c);this.ef=Wh("Eg`"+a,m(this.Of,this,a,!0),1E4);this.He[a]=!1;nuf(this);Ctf(this.Qb,a)?mR(this,a,[0],2):ouf(this,a);puf(this);break;case "smg":this.Aa.wb(gFa);this.nb=!0;a=juf(this);b=this.Ba("ro");oi(b,Otf,a);a=this.ra.getAll(void 0,!1,!0);MG(this.ra,a,m(this.eh,this));xuf(this);break;case "tlsm":eye(this.Za,this.ha.Xd(),!1);break;case "dlsm":a=this.ha.Xd();zl("https://docs.google.com/?q="+encodeURI("from:"+a));
break;case "pi":if(a=Buf(this,a))this.Aa.wb(OEa),yuf(this,a)||(this.ha=a,Cuf(this));break;case "bhg":this.qg&&r7d(this.ha)&&this.Og&&(a=DD(this.getContext(),this.ha.Xd(),this.ha.wj(),this.ha.getName()),this.Og.ra(9,a,SEa));break;default:this.Wa.eFb(b)}};
kR.prototype.Yp=function(a){var b=a.target.getId().split(" "),c=b[1];a=this.ha.Xd();var d=this.getContext().Nc("t1Wg0");switch(c){case "ac":this.Aa.wb(WEa);fye(this.Za,a,this.ha.getName());break;case "de":this.Aa.wb(XEa);this.Za.ra(a,this.Ja.Rn(this.ha));break;case "vc":this.Aa.wb(ZEa);uG(this.getContext()).VAa(this.getContext(),a);break;case "rc":this.Aa.wb(YEa);eye(this.Za,a,!1);break;case "s":b=La(this.Cb[parseInt(b[2],10)]);this.Aa.wb(cFa);uG(this.getContext()).DY(this.getContext(),a,void 0,b);
break;case "c":b=La(this.Cb[parseInt(b[2],10)]);this.Aa.wb(bFa);iE(this.getContext()).ha(this.getContext(),b);break;case "au":d&&(d.vZ(a,0),iuf(this,"au"));break;case "pi":d&&(d.vZ(a,1),iuf(this,"pi"));break;case "hi":d&&(d.vZ(a,2),iuf(this,"hi"));break;case "bl":d&&(d.vZ(a,3),iuf(this,"bl"))}};
var iuf=function(a,b){var c=a.Ia.Ic(),d=a.hb(lR(a,"mm"));c.Pb(d+" au").Wf("au"==b);c.Pb(d+" pi").Wf("pi"==b);c.Pb(d+" hi").Wf("hi"==b);c.Pb(d+" bl").Wf("bl"==b)},Cuf=function(a){a.Aa.wb(PEa);a.Ba("gr").style.display="none";a.Ne&&(a.Ba("h").style.display="");Duf(a)},Duf=function(a){var b=a.Ba(lR(a,"de"));b?(b.style.display="",a.Wa.wJb(a.ha.Xd())):buf(a,!0);for(var c=0;b=a.Fc[c];c++)b.getId()==a.hb(lR(a,"bch"))&&(a.Ta=b),b.getId()==a.hb(lR(a,"bhg"))&&(a.Xc=b),b.getId()==a.hb(lR(a,"bma"))&&(a.Ca=b),
b.getId()==a.hb(lR(a,"bmo"))&&(a.kd=b);x(a.Ia);a.Ia=null;a.Cb=null;xuf(a)},xuf=function(a){a.dispatchEvent(new y("ag"))},wuf=function(a,b,c){a=b[0];for(var d,e=1;d=b[e];e++)d<a&&(a=d);b=3==c;c=q()-a;return 864E5>=c?b?"Mail from today":"Docs from today":6048E5>=c?b?"Mail from this week":"Docs from this week":2592E6>=c?b?"Mail from this month":"Docs from this month":b?"Mail":"Docs"},uuf=function(a,b,c,d){a=new Date(c);c=new Date(d||c+18E5);b=fFd(b,c)?(new Rl(7)).format(a):Ll.VHa[a.getDay()];d=new Rl(11);
a=d.format(a)+" - "+d.format(c);return[b,a]};kR.prototype.qG=function(a){if(a=Euf(this,a.target)){var b=Auf(this,a);if("pi"==b){var c=Buf(this,a);c&&this.Ja.jya(c)&&(qn(a,"anA"),c=c.getName(),a.title="Chat with "+c,tz(a))}else qn(a,"any");if("th"==b||"do"==b)a=Euf(this,a.parentNode),qn(a,"anG")}};kR.prototype.nE=function(a){a=a.relatedTarget&&Euf(this,a.relatedTarget);for(var b,c=0;b=this.Fa[c];c++)b=this.Ba(b),a&&b==a||rn(b,"any","anA","anG")};
var Euf=function(a,b){for(var c=a.Ba();b.parentNode&&b!=c;){var d=Auf(a,b);if("rr"==d||"pi"==d||"tl"==d||"dl"==d||"th"==d||"do"==d||"ce"==d||"cs"==d)return b;b=b.parentNode}return null},quf=function(a,b,c){a.XA&&2==sy(a.Ws)&&(c*=2);return ce(Jz(a.Iq,b),"sz",c)},Auf=function(a,b){var c=a.hh(b.id);return c?c.split(" ")[0]:null},Buf=function(a,b){var c=a.hh(b.id);return(c=c?c.split(" ")[1]:null)?a.ra.ha.get(c):null},lR=function(a,b,c){a=c||a.ha;return k(a)?b+" "+a.getId():b},tuf=function(a){this.tf= a};tuf.prototype.Rl=function(a,b,c){"rpd"==b?(a=new Htf(c),this.tf(a)):"rpt"==b?(a=new Ltf(c),this.tf(a)):"rpa"==b&&(a=new Etf(c),this.tf(a))};
var Fuf=function(){};Fuf.prototype.create=function(a,b,c){return new kR(a,b,c)};var Guf=function(){v.call(this)};r(Guf,Yh);$h(ai(K.Ma(),"rpw"),Guf);Guf.prototype.Zc=function(a){var b=ok(a).Fb;new hR(b,0);new hR(b,1);new hR(b,2);new hR(b,3);new hR(b,4);a.registerService("np3VFd",new Fuf)};
var Huf=function(a){this.ra=a;a=a.getContext();var b=pk(ok(a).Fb);this.ha=!C6e(a.get(Kk))&&!!b.qb("cpg")};Q(Huf,jR);Huf.prototype.qDa=function(a,b,c){return this.ha&&a.tX()?(a={id:this.ra.hb("bjg "+a.getId()),content:"Join Google+",style:5,title:"Join Google+"},oi(c,Zj,a),cuf(this.ra,c),qn(c,"aCS"),!0):!1};Huf.prototype.eFb=function(a){return"bjg"==a?(a="https://plus.google.com/u/"+($f()||"0")+"/up/accounts/upgrade/?hl=en&gpsrc=gmwpw&continue="+encodeURIComponent(Wf.toString()),zl(a),!0):!1};

var Iuf=function(a){tG.call(this,a,"gmail.rhs")};r(Iuf,tG);var Juf={r:HEa,ms:GEa,cc:DEa,cu:EEa,uu:IEa,l:FEa,fr:dFa};Iuf.prototype.Fa=function(a){return Juf[a]};Iuf.prototype.ieb=function(){return Zcf(this.ha)?!0:!1};Iuf.prototype.jYa=function(){qn(this.Ca,"anM");this.wa.ha.Boa(135)};
var Kuf=function(a){this.ra=a;this.ha=new Iuf(a.getContext())};Q(Kuf,jR);f=Kuf.prototype;f.dispose=function(){this.ha.dispose()};f.w_a=function(){f5d(this.ha)};f.TMb=function(){return!0};f.qDa=function(a,b,c){if(b){var d=this.ra.Ka().createElement("DIV");d.id=this.ra.hb("cp "+a.getId());c.appendChild(d);this.ha.ha.ha=b;if(a.Fl(!0))return g5d(this.ha,a.Xd(),a.ha,d);if(r7d(a,!0)){b=this.ha;c=a.wj();var e=a.Ga;b.Ha=a.ha;b.Ca=d;b.Aa=tPa(c);return b.kna(!!e,!1,!1)}}return!1};f.jzb=function(){f5d(this.ha)};

var Ouf=function(a){this.ra=a;this.wa=YB(a.getContext())};r(Ouf,jR);Q(Ouf,jR,-1);f=Ouf.prototype;f.g2b="23";f.e2b="gmail:rhspw_pp:default:image";f.f2b="gmail:rhspw_pp:default:name";f.PMb=function(a){a=a.getAll(void 0,!1,!0);return 0<a.length&&a[0].Ga?!0:!1};f.uxb=function(a){a=a.getAll(void 0,!1,!0);return 0<a.length&&a[0].Ga&&(this.ha=a[0].getId())?(this.wa.wb(eFa),!0):!1};f.pbb=function(a){this.ha&&(a.W_c=this.ha,a.V_c="Related Google+ Page")};
f.ccb=function(a,b){if(a&&this.ha)switch(a=ce(a,"socpid",this.g2b),b){case aFa:a=ce(a,"socfid",this.e2b);break;case $Ea:a=ce(a,"socfid",this.f2b)}return a};f.R1=function(){return this.ha};f.Orb=function(){return!!this.R1()};f.Qqb=function(){return!!this.R1()};f.qDa=function(){return!!this.R1()};

var Puf=function(a){this.ra=a;a=a.getContext();this.Ph=AD(a);this.wa=a.get(fpa);this.Aa=XB(a);this.Pa=new B(this);this.ha={}};Q(Puf,jR);var Quf=function(a,b){return-1!=b.indexOf("@")?b.replace(/@googlemail.com/i,"@gmail.com"):b};f=Puf.prototype;f.vob=function(a,b,c){if(!this.wa.ha)return!1;var d=Quf(this,a);if(this.ha[d])return!0;c&&this.Aa.Ita()?this.Pa.ud(this.Aa,"tb",Fa(this.wob,a,b)):this.wob(a,b);return!0};
f.wob=function(a,b){var c=Quf(this,a);this.wa.r1c(c);var d=this.ra.Ba("de "+a),e=yfe(this.wa);e.className="dx";e.width=220;e.style.position="fixed";e.style.visibility="hidden";d.appendChild(e);this.Pa.listen(e,"load",m(this.wa.FNb,this.wa,e,c,b));this.ha[c]=e};f.GNb=function(a){a=Quf(this,a);this.ha[a]&&(this.ha[a].style.position="",this.ha[a].style.visibility="");return!0};f.wJb=function(a){a=Quf(this,a);this.ha[a]&&this.wa.FNb(this.ha[a],a,null);return!0}; f.Vbb=function(a){a=Quf(this,a);a=this.ha[a];return!!a&&""==a.style.visibility};f.w_a=function(){this.wa.W4()};f.dispose=function(){x(this.Pa);for(var a in this.ha){var b=this.ha[a];b.parentNode.removeChild(b)}this.ha=null};

di(K.Ma(),"rpw");gi(K.Ma(),"rpw");
}catch(e){_DumpException(e)}
// Google Inc.
