/* JS */ gapi.loaded_3(function(_){var window=this;
var Mk;_.Kk=function(a){if(!_.Vc(a))return null;for(var b={},c=0;c<a.length;c++)b[a[c]]=a[c];return b};_.Lk=function(a,b){var c=a.length;if(c!=b.length)return!1;for(var d=0;d<c;++d){var e=a.charCodeAt(d),f=b.charCodeAt(d);65<=e&&90>=e&&(e+=32);65<=f&&90>=f&&(f+=32);if(e!=f)return!1}return!0};Mk=null;
_.Nk=function(a){if(null===Mk){var b=_.E("client/headers/response");b||(b=_.E("googleapis/headers/response"));Mk=_.Kk(b)}if(null!=Mk){if(Mk.hasOwnProperty(a))return!0;for(var c in Mk)if(Mk.hasOwnProperty(c)&&_.Lk(c,a))return!0}return!1};
_.Ok=function(a){a=String(a||"").split("\x00").join("");for(var b=[],c=!0,d=0,e=a.length;d<e;++d){var f=a.charAt(d),h=a.charCodeAt(d);if(55296<=h&&56319>=h&&d+1<e){var k=a.charAt(d+1),l=a.charCodeAt(d+1);56320<=l&&57343>=l&&(f+=k,h=65536+(h-55296<<10)+(l-56320),++d)}if(!(0<=h&&1114109>=h)||55296<=h&&57343>=h||64976<=h&&65007>=h||65534==(h&65534))h=65533,f=String.fromCharCode(h);k=!(32<=h&&126>=h)||" "==f||c&&":"==f||"\\"==f;!c||"/"!=f&&"?"!=f||(c=!1);"%"==f&&(d+2>=e?k=!0:(l=16*(0,window.parseInt)(a.charAt(d+
1),16)+(0,window.parseInt)(a.charAt(d+2),16),0<=l&&255>=l?(h=l,f=0==h?"":"%"+(256+l).toString(16).toUpperCase().substr(1),d+=2):k=!0));k&&(f=(0,window.encodeURIComponent)(f),1>=f.length&&(0<=h&&127>=h?f="%"+(256+h).toString(16).toUpperCase().substr(1):(h=65533,f=(0,window.encodeURIComponent)(String.fromCharCode(h)))));b.push(f)}a=b.join("");a=a.split("#")[0];a=a.split("?");b=a[0].split("/");c=[];d=0;for(e=b.length;d<e;++d)f=b[d],h=f.split("%2E").join("."),h=h.split((0,window.encodeURIComponent)("\uff0e")).join("."),
"."==h?d+1==e&&c.push(""):".."==h?(0<c.length&&c.pop(),d+1==e&&c.push("")):c.push(f);a[0]=c.join("/");for(a=a.join("?");a&&"/"==a.charAt(0);)a=a.substr(1);return"/"+a};_.Qk=function(a){var b=_.Ok(a);if(String(a)!=b)throw Error("G");(a=b)&&"/"==a.charAt(a.length-1)||(a=(a||"")+"/");_.G.register("init",function(){_.Qk(a)});_.Pk=a;_.F.Xc(window.location.href)};
_.Rk="function"==typeof window.atob;
_.$b.Raa=function(a){var b=[];if(1<arguments.length)for(var c=0,d;d=arguments[c];++c)b.push(d);else b=a;return function(a){for(var c=0;b[c];++c)if(a===b[c])return!0;return!1}};_.$b.Hea=function(a){return function(b){return a.test(b)}};_.$b.yU=function(a){return"undefined"!==typeof a};_.$b.pda=function(a){return"string"===typeof a&&0<a.length};_.$b.Y9=function(a){return"boolean"===typeof a};_.$b.uca=function(a){return function(b){for(var c in a)if(a.hasOwnProperty(c)&&!(0,a[c])(b[c]))return!1;return!0}};

_.F=_.F||{};(function(){function a(a){b=a["core.util"]||{}}var b={},c={};_.$b&&_.$b.register("core.util",null,a);_.F.Kha=function(a){return"undefined"===typeof b[a]?null:b[a]};_.F.hasFeature=function(a){return"undefined"!==typeof b[a]};_.F.Uha=function(){return c}})();

_.ax=function(a){this.Fr=a};_.ax.prototype.toString=function(){return this.Fr};_.bx=function(a){_.td.call(this);this.bj=1;this.$z=[];this.jA=0;this.ig=[];this.wj={};this.CX=!!a};_.C(_.bx,_.td);_.g=_.bx.prototype;_.g.subscribe=_.q(48);_.g.cw=_.q(50);_.g.unsubscribe=_.q(52);_.g.Lk=function(a){var b=this.ig[a];if(b){var c=this.wj[b];0!=this.jA?(this.$z.push(a),this.ig[a+1]=_.xd):(c&&_.rd(c,a),delete this.ig[a],delete this.ig[a+1],delete this.ig[a+2])}return!!b};
_.g.Eq=function(a,b){var c=this.wj[a];if(c){for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];if(this.CX)for(e=0;e<c.length;e++){var h=c[e];cx(this.ig[h+1],this.ig[h+2],d)}else{this.jA++;try{for(e=0,f=c.length;e<f;e++)h=c[e],this.ig[h+1].apply(this.ig[h+2],d)}finally{if(this.jA--,0<this.$z.length&&0==this.jA)for(;c=this.$z.pop();)this.Lk(c)}}return 0!=e}return!1};var cx=function(a,b,c){_.vf(function(){a.apply(b,c)})};
_.bx.prototype.clear=function(a){if(a){var b=this.wj[a];b&&((0,_.jd)(b,this.Lk,this),delete this.wj[a])}else this.ig.length=0,this.wj={}};_.bx.prototype.Yb=function(a){if(a){var b=this.wj[a];return b?b.length:0}a=0;for(b in this.wj)a+=this.Yb(b);return a};_.bx.prototype.va=function(){_.bx.S.va.call(this);this.clear();this.$z.length=0};
_.dx=function(a){_.td.call(this);this.Ke=new _.bx(a);_.vd(this,this.Ke)};_.C(_.dx,_.td);_.g=_.dx.prototype;_.g.subscribe=_.q(47);_.g.cw=_.q(49);_.g.unsubscribe=_.q(51);_.g.Lk=function(a){return this.Ke.Lk(a)};_.g.Eq=function(a,b){return this.Ke.Eq(a.toString(),b)};_.g.clear=function(a){this.Ke.clear(_.na(a)?a.toString():void 0)};_.g.Yb=function(a){return this.Ke.Yb(_.na(a)?a.toString():void 0)};

_.kx=function(){_.jx="oauth2relay"+String(2147483647*(0,_.yk)()|0);_.ix.proxy=_.jx};_.lx=new _.dx;_.mx=new _.ax("oauth");_.ix={};_.kx();var nx=_.E("oauth-flow/client_id");_.ix.client_id=nx;var ox=_.ix,px;var qx=String(_.E("oauth-flow/redirectUri"));if(qx)px=qx.replace(/[#][\s\S]*/,"");else{var rx=_.rj.qb(window.location.href);px=[_.E("oauth-flow/callbackUrl"),"?x_origin=",(0,window.encodeURIComponent)(rx)].join("")}ox.redirect_uri=px;_.ix.origin=_.rj.qb(window.location.href);_.ix.response_type="token"; _.ix.gsiwebsdk="1";

var tx,sx,ux,vx,wx,xx,yx,zx,Ax,Bx,Cx,Dx,Ex,Fx,Gx,Hx,Ix,Jx,Kx,Mx,Nx,Ox,Px,Qx,Rx,Tx,Ux,Vx,Wx,Xx,Yx,Zx,$x,ay,by,cy,dy,ey,fy,gy,hy,jy,ky,ly,my,ny,oy,qy,ry,sy,ty,uy,xy,yy,Ay;_.bx.prototype.unsubscribe=_.I(52,function(a,b,c){if(a=this.wj[a]){var d=this.ig;if(a=_.ah(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.Lk(a)}return!1});_.dx.prototype.unsubscribe=_.I(51,function(a,b,c){return this.Ke.unsubscribe(a.toString(),b,c)});
_.bx.prototype.subscribe=_.I(48,function(a,b,c){var d=this.wj[a];d||(d=this.wj[a]=[]);var e=this.bj;this.ig[e]=a;this.ig[e+1]=b;this.ig[e+2]=c;this.bj=e+3;d.push(e);return e});_.dx.prototype.subscribe=_.I(47,function(a,b,c){return this.Ke.subscribe(a.toString(),b,c)});
tx=function(a){var b=sx;_.gx(b,[{hA:"-webkit-transform",duration:1,timing:"ease",Um:0}]);_.gx(b,[{hA:"transform",duration:1,timing:"ease",Um:0}]);_.Lh(function(){b.style.webkitTransform="translate3d(0px,"+a+"px,0px)";b.style.transform="translate3d(0px,"+a+"px,0px)"},0)};
vx=function(a){var b=_.fk(a);if(!b)return new _.Lj("G_USERSTATE_");a=["G_USERSTATE_",_.Rj&&b.qd?"S":"H",b.Bg].join("");var c=_.ak[a];c||(c={zia:63072E3},_.Pl(_.hk(b),c),c=new _.Ij(a,c),_.ak[a]=c,b=c.read(),"undefined"!==typeof b&&null!==b&&(window.document.cookie=a+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/",c.write(b)));return c};wx=function(a){a=a&&a.id_token;if(!a||!a.split(".")[1])return null;a=(a.split(".")[1]+"...").replace(/^((....)+).?.?.?$/,"$1");return _.Tg(_.Bv(a,!0))};xx=function(){sx.parentNode.removeChild(sx)};
yx=function(){var a=ux+88;tx(a);ux=a};zx=function(){var a=ux-88;tx(a);ux=a};Ax=function(a){var b=vx(a).read();a=_.Ra();if(b)for(var b=b.split(":"),c;c=b.shift();)c=c.split("="),a[c[0]]=c[1];return a};Bx=function(a){if(!a)return[];a=a.split("=");return a[1]?a[1].split("|"):[]};Cx=function(a){return(a=wx(a))?a.sub:null};
Dx=function(a){var b=a?yx:zx,c=a?zx:yx;a=a?"-":"";ux=(0,window.parseInt)(a+88,10);sx.style.webkitTransform="translate3d(0px,"+a+88+"px,0px)";sx.style.transform="translate3d(0px,"+a+88+"px,0px)";sx.style.display="";sx.style.visibility="visible";b();_.Lh(c,4E3);_.Lh(xx,5E3)};Ex=function(){var a,b=null;_.Sj.iterate(function(c,d){if(0===c.indexOf("G_AUTHUSER_")){var e=_.Tj(c.substring(11));if(!a||e.qd&&!a.qd||e.qd==a.qd&&e.Bg>a.Bg)a=e,b=d}});return{OX:a,ip:b}};
Fx=function(a){a=a.split(":");return{BL:a[0].split("=")[1],j7:Bx(a[1]),wia:Bx(a[2]),Cha:Bx(a[3])}};Gx=function(a){a=_.fk(a);if(!a||a.qd&&!_.Rj)return null;var b=["G_AUTHUSER_",_.Rj&&a.qd?"S":"H",a.Bg].join(""),c=_.Zj[b];c||(c=new _.Sj(b,_.hk(a)),_.Zj[b]=c);return c};Hx=function(a){var b=Cx(a);b?(a=Ax(a.cookie_policy),b="0"==a[b]||"X"==a[b]):b=!1;return b};
Ix=function(a){var b=_.E("oauth-flow/toast/position");"top"!==b&&(b="bottom");var c=window.document.createElement("div");sx=c;c.style.cssText="position:fixed;left:0px;z-index:1000;width:100%;";var d;_.Q(c,"visibility","hidden");_.Q(c,b,"-40px");_.Q(c,"height","128px");d=c;if("desktop"==_.E("deviceType")){d=window.document.createElement("div");d.style.cssText="float:left;position:relative;left:50%;";c.appendChild(d);var e=window.document.createElement("div");e.style.cssText="float:left;position:relative;left:-50%";
d.appendChild(e);d=e}e="top"==b?"-":"";ux=(0,window.parseInt)(e+88,10);sx.style.webkitTransform="translate3d(0px,"+e+88+"px,0px)";sx.style.transform="translate3d(0px,"+e+88+"px,0px)";e=window;try{for(;e.parent!=e&&e.parent.document;)e=e.parent}catch(f){}e=e.document.body;try{e.insertBefore(c,e.firstChild)}catch(f){}_.an.hj({url:":socialhost:/:session_prefix:_/widget/oauthflow/toast",queryParams:{clientId:a.client_id,idToken:a.id_token},where:d,onRestyle:function(){"top"===b?Dx(!0):Dx(!1)}})};Jx=!1;
Kx=!1;_.Lx=function(a){_.Ib(a)&&_.Mb(a)};Nx=function(a){var b=Ex(),c=b.OX,b=b.ip,d=a&&_.Vj(a);if(null!==b){var e;_.Sj.iterate(function(a,b){var f=_.Wj(a);f&&f.Je&&(d&&f.CL!=d||f.qd==c.qd&&f.Bg==c.Bg&&(e=b))});if(e){var f=Fx(e);a=f&&f.j7[Number(b)];f=f&&f.BL;if(a)return{ip:b,jja:a,BL:f}}}return null};Ox=function(a){a=Gx(a.g_user_cookie_policy);_.hb("googleapis.config/sessionIndex",null);a.clear()};Px=function(a){return _.Aj(function(b){return a[b]})};
Qx=function(a,b){var c=null;if(a&&b){c=b.client_id=b.client_id||a.client_id;b.scope=b.scope||a.scope;b.g_user_cookie_policy=a.cookie_policy;b.cookie_policy=b.cookie_policy||a.cookie_policy;b.response_type=b.response_type||a.response_type;var d=_.E("iframes/signin/iframeType");!Jx&&b.error&&Px(a)&&(_.Lx("gapi.signin.impression."+d+"."+c),Jx=!0)}b&&(b.issued_at||(b.issued_at=String(_.Hj())),d=(0,window.parseInt)(b.expires_in,10)||86400,b.error&&(d=_.E("oauth-flow/errorMaxAge")||86400),b.expires_in=
String(d),b.expires_at||(b.expires_at=String(_.Hj()+d)),a&&Px(a)||(b["g-oauth-window"]=(Mx||{}).popup),b._aa||b.error||null!=Nx(c)||!Px(a)||(b._aa="1"),c=b.status={},c.google_logged_in=!!b.session_state,d=c.signed_in=!!b.access_token,c.method=d?b["g-oauth-window"]?"PROMPT":"AUTO":null);return b};Rx={};
_.Sx=function(a,b){var c,d;"string"==typeof a?(c=b,d=a):(c=a,d="token");if(c){var e=_.jk(c,!0);if(e){var f;if((f=c)&&f.session_state){var h=[],k=[],l=[],m=(0,window.parseInt)(f.authuser,10)||0;h[m]=f.session_state;k[m]=f.issued_at;l[m]=f.expires_at;f=["C="+f.client_id,"S="+h.join("|"),"I="+k.join("|"),"X="+l.join("|")].join(":")}else f=null;f&&e.yh.write(f);"token"==d&&(e=Gx(c.g_user_cookie_policy))&&(c.error?Ox(c):c.session_state&&e.write(c.authuser||"0"))}}if(d="token"!==d?_.ik(d):_.jk(c))if(c){if(d.yh.write(c),
!_.bk||d.GZ&&"token"!==_.bk)_.bk=d.key}else d.yh.clear(),_.bk=null;_.kk(void 0,void 0)};Tx=function(a,b){var c=b&&b.key||"token",d=a=Qx(b&&b.params,a);!Hx(d)&&d&&0<=(" "+(d.scope||"")+" ").indexOf(" https://www.googleapis.com/auth/plus.login ")&&_.E("isLoggedIn")&&"1"===(d&&d._aa)&&(d._aa="0",Kx||(Kx=!0,Ix(d)));_.Sx(c,a);a=_.kk(c,void 0);if(b){c=b.popup;d=b.after_redirect;if(c&&"keep_open"!=d)try{c.close()}catch(e){}b.callback&&(b.callback(a),b.callback=null)}};Ux={};Vx=function(){return!!_.E("oauth-flow/usegapi")};
Wx=function(a){var b=_.jx;return function(c){if(this.f==b&&this.t==_.G.ql(this.f)&&this.origin==_.G.zl(this.f))return a.apply(this,arguments)}};Xx=null;Yx=[];Zx=function(a,b){Vx()?Xx.unregister(a):_.G.unregister(a+":"+b)};$x=function(a,b,c){Vx()?Xx.register(a,c,_.mn):_.G.register(a+":"+b,Wx(c))};
ay=function(a){var b=_.F.Xc;if(null!=b(a).jsh)return a;if(b=String(b().jsh||_.Za.h||"")){var c=(a+"#").indexOf("#");a=a.substr(0,c)+(-1!==a.substr(0,c).indexOf("?")?"&":"?")+"jsh="+(0,window.encodeURIComponent)(b)+a.substr(c)}return a};by={};cy=0;
dy=function(a){a&&Yx.push(a);a=_.jx;var b=window.document.getElementById(a),c=(new Date).getTime();if(b){if(cy&&6E4>c-cy)return;var d=_.G.ql(a);d&&(Zx("oauth2relayReady",d),Zx("oauth2callback",d));b.parentNode.removeChild(b);if(/Firefox/.test(window.navigator.userAgent))try{window.frames[a]=void 0}catch(f){}_.kx();a=_.jx}cy=c;var e=String(2147483647*(0,_.yk)()|0),b=_.E("oauth-flow/proxyUrl")||_.E("oauth-flow/relayUrl");Vx()?Xx=_.an.hj({where:_.F.ey(),url:b,id:a,attributes:{style:{width:"1px",height:"1px",
position:"absolute",top:"-100px"}},dontclear:!0}):(b=[b,"?parent=",(0,window.encodeURIComponent)(_.rj.qb(window.location.href)),"#rpctoken=",e,"&forcesecure=1"].join(""),c=_.F.ey(),d=_.F.VC({name:a,id:a}),d.src=ay(b),d.style.width="1px",d.style.height="1px",d.style.position="absolute",d.style.top="-100px",d.tabIndex=-1,c.appendChild(d),_.G.Mv(a));$x("oauth2relayReady",e,function(){Zx("oauth2relayReady",e);var a=Yx;if(null!==a){Yx=null;for(var b=0,c=a.length;b<c;++b)a[b]()}});$x("oauth2callback",e,
function(a){var b=_.F.Xc;a=b(a);var b=a.state,c;c=b.replace(/\|.*$/,"");c={}.hasOwnProperty.call(Rx,c)?Rx[c]:null;a.state=c;null!=a.state&&(c=Ux[b],delete Ux[b],Tx(a,c))})};ey=function(a){var b={error:"user_signed_out"};b.client_id=a.client_id;b.g_user_cookie_policy=a.g_user_cookie_policy;b.scope=a.scope;b.response_type=a.response_type;b.session_state=a.session_state;return Qx(null,b)};
fy=function(a,b){var c=a||{},d;for(d in _.ix)_.na(c[d])||(c[d]=_.ix[d]);a=c;c=_.E("googleapis/overrideClientId");null!=c&&(a.client_id=c);if(!a.redirect_uri||"postmessage"===a.redirect_uri){c=a;d=a.state||"";d=String(d);var e;if({}.hasOwnProperty.call(by,d))e=by[d];else{for(var f=2147483647*(0,_.yk)()|0;;){e=String(f);if(!{}.hasOwnProperty.call(Rx,e))break;f+=(0,_.yk)()}Rx[e]=d;by[d]=e}c.state=e+"|"+(0,_.yk)();Ux[a.state]=b}c=a.authorize_uri||_.E("oauth-flow/authUrl");delete a.authorize_uri;c+=0<
c.indexOf("?")?"&":"?";c+=_.ek(a);c=_.Cj(c);d=_.E("iframes/signin/iframeType");"blue"==d?c+="&e=3100070":"red"==d?c+="&e=3100071":"default"==d&&(c+="&e=3100077");return c};gy=function(a){var b=_.po(),c=b&&b.scope,b=a&&a.scope,b="string"===typeof b?b.split(" "):b||[];if(c){for(var c=c.split(" "),d=0;d<c.length;++d){var e=c[d];-1==_.Sb.call(b,e)&&b.push(e)}0<b.length&&(a.scope=b.join(" "))}return a};
hy=function(a){if(!_.na(a.include_granted_scopes)){var b=_.E("include_granted_scopes"),c=_.po().include_granted_scopes;_.na(b)?a.include_granted_scopes=!!b:_.na(c)&&(a.include_granted_scopes="1"==c||"true"==c)}return a};_.iy=function(a){null===Yx?a&&a():dy(a)};jy=function(a,b,c,d){var e=Ax(c),f=e[a];e[a]=b?"0":"1";var h=[];_.nb(e,function(a,b){h.push(b+"="+a)});b=h.join(":");c=vx(c);b?c.write(b):c.clear();e[a]!==f&&d&&d()};
ky=function(a,b){for(var c=a.split(" "),d=b.split(" "),e=_.Ra(),f=0,h=d.length;f<h;++f)d[f]&&(e[d[f]]=1);f=0;for(h=c.length;f<h;++f)if(c[f]&&!e[c[f]])return!1;return!0};ly=function(a){if(!a)return null;var b,c,d=_.Vj(a);_.Pj.iterate(function(a){var e=_.Wj(a);e&&e.Je&&e.CL===d&&(!b||e.qd&&!b.qd||e.qd==b.qd&&e.Bg>b.Bg)&&(b=e,c=a)});return c};
my=function(a){if(Vx()){var b=_.an.hj({where:_.F.ey(),url:a.uri,attributes:{style:{width:"1px",height:"1px",position:"absolute",top:"-100px"}},dontclear:!0});window.setTimeout(function(){b.close()},3E5)}else{var c=_.F.ey(),d=_.F.VC();d.src=ay(a.uri);d.style.width="1px";d.style.height="1px";d.style.position="absolute";d.style.top="-100px";window.setTimeout(function(){d.parentNode&&d.parentNode.removeChild(d)},3E5);c.appendChild(d)}};
ny=function(a,b){var c=a,d=b||function(){};if(Mx){var e=Mx.popup,f=Mx.after_redirect;if(e&&"keep_open"!=f&&!Px(a))try{e.close()}catch(h){}}e=Mx={};"key"in c&&(e.key=c.key,delete c.key);c=hy(c);e.params=gy(c);e.callback=function(a){Px(c)||!a||a.error||jy(Cx(a),!1,a.cookie_policy);Hx(a)&&Px(c)&&(a=ey(a));d(Qx(c,a))};e.uri=fy(c,e);return e};
oy=function(a,b){var c=_.Ra();c.client_id=a.client_id;c.session_state=a.session_state;_.iy(function(){Vx()?Xx.send("check_session_state",c,function(a){b.call(null,a[0])},_.mn):_.G.call(_.jx,"check_session_state",Wx(function(a){b.call(null,a)}),c.session_state,c.client_id)})};qy=function(a){a=_.F.Xc("#"+_.ek(a));if(!Px(a))return null;var b=a.key||ly(a.client_id);return(b=_.kk(b,!0,!0))&&b.client_id===a.client_id&&ky(a.scope,b.scope)&&ky(a.response_type,b.response_type)?b:null};
ry=function(a,b){var c=_.F.Xc();a.hl=c.lang||c.hl||_.E("lang");var d=ny(a,b);a.after_redirect&&(d.after_redirect=a.after_redirect);if(null!=a.scope&&null!=a.client_id){var e=function(){_.iy(function(){if(d.popup)d.popup.focus();else if(Px(a))my(d);else{var b=Math.min(_.E("oauth-flow/authWindowWidth",599),window.screen.width-20),c=Math.min(_.E("oauth-flow/authWindowHeight",600),window.screen.height-30),e=(window.screen.width-b)/2,f=(window.screen.height-c)/2;Mx.popup=window.open(ay(d.uri),"_blank",
["toolbar=no","location="+(window.opera?"no":"yes"),"directories=no,status=no,menubar=no,scrollbars=yes,resizable=yes,copyhistory=no","width="+b,"height="+c,"top="+f,"left="+e].join())}})},f=qy(a);!_.E("oauth-flow/disableOpt")&&f?(c=_.Ra(),c.client_id=f.client_id,c.session_state=f.session_state,oy(c,function(a){a?Tx(f,Mx):e()})):e()}else Tx(null,Mx),_.Yb("Unable to perform authorization: scope and/or client_id parameters missing.")};
sy=function(a){a||(a=_.kk(void 0,!0));a&&"object"===typeof a||(a={error:"invalid_request",error_description:"no callback data"});var b=a.error_description;b&&window.console&&(window.console.error(a.error),window.console.error(b));a.error||(_.Za.drw=null);_.Sx(a);if(b=a.authuser)_.E("googleapis.config/sessionIndex"),_.hb("googleapis.config/sessionIndex",b);_.lx.Eq(_.mx,a);return a};
ty=function(a,b){var c=a||{},d=b||function(){};if(_.E("oauth-flow/disableOpt")||_.E("isLoggedIn")||!Px(c))ry(c,d);else{var e=_.Ra();e.client_id=c.client_id;e.session_state=null;oy(e,function(a){a?(a=_.Ra(),a.error="immediate_failed_user_logged_out",d(Qx(c,a))):(_.hb("isLoggedIn",!0),ry(c,d))})}};uy=function(a,b){var c=Cx(a);c&&(Ox(a),jy(c,!0,b,function(){sy&&sy(ey(a))}))};
_.vy=function(a,b){var c=new _.Af(function(b,c){var d=function(a){null==a||a.error?c(a):b(a)};try{ty(a,d)}catch(h){c(h)}});b&&c.then(b,function(a){b(sy(a))});return c};_.wy=function(a){_.Vb&&(_.Vb.error?_.Vb.error(a):_.Vb.log&&_.Vb.log(a))};xy=_.wk.fE;yy=null;
_.By=function(a,b){if("force"!==a.approvalprompt){var c=_.zy(a);c.prompt="none";delete c.redirect_uri;delete c.approval_prompt;delete c.immediate;var d;if(d=!b)yy?(c.client_id!==yy.client_id&&window.console&&window.console.log&&window.console.log("Ignoring mismatched page-level auth param client_id="+c.client_id),d=!0):(yy=c,d=!1);d||Ay(c)}};
_.zy=function(a){var b=a.redirecturi||"postmessage",c=(0,_.Yc)((a.scope||"").replace(/[\s\xa0]+/g," ")),b={client_id:a.clientid,redirect_uri:b,response_type:"code token id_token gsession",scope:c};a.approvalprompt&&(b.approval_prompt=a.approvalprompt);a.state&&(b.state=a.state);a.openidrealm&&(b["openid.realm"]=a.openidrealm);c="offline"==a.accesstype?!0:(c=a.redirecturi)&&"postmessage"!=c;c&&(b.access_type="offline");a.requestvisibleactions&&(b.request_visible_actions=(0,_.Yc)(a.requestvisibleactions.replace(/[\s\xa0]+/g,
" ")));a.after_redirect&&(b.after_redirect=a.after_redirect);a.cookiepolicy&&"none"!==a.cookiepolicy&&(b.cookie_policy=a.cookiepolicy);"none"===a.cookiepolicy&&_.Lx("gapi.signin.cpnone");"undefined"!=typeof a.includegrantedscopes&&(b.include_granted_scopes=a.includegrantedscopes);a.e&&(b.e=a.e);(a=a.authuser||_.E("googleapis.config/sessionIndex"))&&(b.authuser=a);(a=_.E("useoriginassocialhost"))&&(b.use_origin_as_socialhost=a);return b};
Ay=function(a){_.jp("waaf0","signin","0");_.vy(a,function(a){_.jp("waaf1","signin","0");sy(a)})};_.Cy=function(a){a=_.zy(a);_.hb("oauth-flow/authWindowWidth",445);_.hb("oauth-flow/authWindowHeight",615);Ay(a)};_.Dy=function(a){_.lx.unsubscribe(_.mx,a);_.lx.subscribe(_.mx,a)};
var Ky,Ny;_.Fy=function(a){return a.cookiepolicy?!0:(_.Ey("cookiepolicy is a required field.  See https://developers.google.com/+/web/signin/#button_attr_cookiepolicy for more information."),!1)};_.Ey=function(a){window.console&&(window.console.error?window.console.error(a):window.console.log&&window.console.log(a))};_.Jy=function(a,b){var c=_.po();_.Pl(a,c);c=gy(c);if(_.Fy(c)){var d=_.Gy(c);_.Hy(c);b?_.Ya(b,"click",function(){_.Iy(c,d)}):_.Iy(c,d)}};
_.Gy=function(a){var b=new Ky;_.Dy(function(c){if(b.RF&&c&&(c.access_token&&_.hb("isPlusUser",!0),c["g-oauth-window"]))if(b.RF=!1,c.access_token&&"consent"==c.prompt){var d=c["g-oauth-window"];c=c.id_token;var e=a.apppackagename;if(e&&d){var f=!0;try{f=d.closed}catch(h){}f||(c=_.E("iframes/:socialhost:")+"/_/history/otaappinstall?clientId="+(0,window.encodeURIComponent)(a.clientid)+"&appId="+(0,window.encodeURIComponent)(e)+"&idToken="+(0,window.encodeURIComponent)(c),c=_.Cj(c),d.location.href=c)}}else if(d=
c["g-oauth-window"],a.apppackagename&&d)try{d.close()}catch(h){}});return b};Ky=function(){this.RF=!1};_.Hy=function(a){a=_.Ly(a);_.My(a.callback);_.iy(function(){_.By(a)})};_.Ly=function(a){Ny(a);a.apppackagename&&(a.after_redirect="keep_open");a.redirecturi&&delete a.redirecturi;_.Bj(function(b){return a[b]})||(a.authuser=0);a.apppackagename&&(a.apppackagename=a.apppackagename.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));return a};Ny=function(a){/^\s*$/.test(a.scope||"")&&(a.scope="https://www.googleapis.com/auth/plus.login")}; _.My=function(a){if("string"===typeof a)if(window[a])a=window[a];else{_.Ey('Callback function named "'+a+'" not found');return}a&&_.Dy(a)};_.Iy=function(a,b){b.RF=!0;var c;c=_.Ly(a);_.Cy(c)};
_.D("gapi.auth.authorize",_.vy);_.D("gapi.auth.checkSessionState",oy);_.D("gapi.auth.getAuthHeaderValueForFirstParty",xy);_.D("gapi.auth.getToken",function(a,b){return _.kk(a,b)});_.D("gapi.auth.getVersionInfo",function(a,b){_.iy(function(){var c=_.vk()||"",d=null,e=null;c&&(e=c.split(" "),2==e.length&&(d=e[1]));d?Vx()?Xx.send("get_versioninfo",{xapisidHash:d,sessionIndex:b},function(b){a(b[0])},_.mn):_.G.call(_.jx,"get_versioninfo",Wx(function(b){a(b)}),d,b):a()})});_.D("gapi.auth.init",_.iy);
_.D("gapi.auth.setToken",_.Sx);_.D("gapi.auth.signIn",function(a){_.Jy(a)});_.D("gapi.auth.signOut",function(){var a=_.kk(void 0,void 0);a&&uy(a,a.cookie_policy)});_.D("gapi.auth.unsafeUnpackIdToken",wx);_.D("gapi.auth._pimf",_.By);_.D("gapi.auth._oart",Ix);_.D("gapi.auth._guss",function(a){return vx(a).read()});
var Oy=_.po();Oy.clientid&&Oy.scope&&Oy.cookiepolicy&&_.Lx("gapi.auth.pageLevelConfig("+_.sb(Oy).sort().join("-")+")");Oy.clientid&&Oy.scope&&Oy.callback&&!_.E("disableRealtimeCallback")?_.Hy(Oy):_.iy();
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.Qf=function(a,b){this.cm=[];this.XP=a;this.eM=b||null;this.bu=this.Bp=!1;this.rk=void 0;this.AI=this.PX=this.rC=!1;this.cB=0;this.mb=null;this.ex=0};_.Qf.prototype.cancel=function(a){if(this.Bp)this.rk instanceof _.Qf&&this.rk.cancel();else{if(this.mb){var b=this.mb;delete this.mb;a?b.cancel(a):(b.ex--,0>=b.ex&&b.cancel())}this.XP?this.XP.call(this.eM,this):this.AI=!0;this.Bp||this.Vx(new _.Rf)}};_.Qf.prototype.SL=function(a,b){this.rC=!1;Sf(this,a,b)};
var Sf=function(a,b,c){a.Bp=!0;a.rk=c;a.bu=!b;Tf(a)};_.g=_.Qf.prototype;_.g.Yk=function(){if(this.Bp){if(!this.AI)throw new Uf;this.AI=!1}};_.g.je=function(a){this.Yk();Sf(this,!0,a)};_.g.Vx=function(a){this.Yk();Sf(this,!1,a)};_.g.Rd=function(a,b){return this.Ok(a,null,b)};_.g.Ok=function(a,b,c){this.cm.push([a,b,c]);this.Bp&&Tf(this);return this};_.g.then=function(a,b,c){var d,e,f=new _.Af(function(a,b){d=a;e=b});this.Ok(d,function(a){a instanceof _.Rf?f.cancel():e(a)});return f.then(a,b,c)};_.xf(_.Qf);
_.Qf.prototype.mL=_.q(10);
var Vf=function(a){return(0,_.md)(a.cm,function(a){return _.gd(a[1])})},Tf=function(a){if(a.cB&&a.Bp&&Vf(a)){var b=a.cB,c=Wf[b];c&&(_.r.clearTimeout(c.Ka),delete Wf[b]);a.cB=0}a.mb&&(a.mb.ex--,delete a.mb);for(var b=a.rk,d=c=!1;a.cm.length&&!a.rC;){var e=a.cm.shift(),f=e[0],h=e[1],e=e[2];if(f=a.bu?h:f)try{var k=f.call(e||a.eM,b);_.na(k)&&(a.bu=a.bu&&(k==b||k instanceof Error),a.rk=b=k);if(_.yf(b)||"function"===typeof _.r.Promise&&b instanceof _.r.Promise)d=!0,a.rC=!0}catch(l){b=l,a.bu=!0,Vf(a)||(c=
!0)}}a.rk=b;d&&(k=(0,_.u)(a.SL,a,!0),d=(0,_.u)(a.SL,a,!1),b instanceof _.Qf?(b.Ok(k,d),b.PX=!0):b.then(k,d));c&&(b=new Xf(b),Wf[b.Ka]=b,a.cB=b.Ka)},Uf=function(){_.ef.call(this)};_.C(Uf,_.ef);Uf.prototype.message="Deferred has already fired";Uf.prototype.name="AlreadyCalledError";_.Rf=function(){_.ef.call(this)};_.C(_.Rf,_.ef);_.Rf.prototype.message="Deferred was canceled";_.Rf.prototype.name="CanceledError";var Xf=function(a){this.Ka=_.r.setTimeout((0,_.u)(this.A8,this),0);this.Wx=a}; Xf.prototype.A8=function(){delete Wf[this.Ka];throw this.Wx;};var Wf={};

_.Py={s:function(a,b,c){return(0,window.isNaN)(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+(0,_.Zc)(" ",Number(c)-a.length):(0,_.Zc)(" ",Number(c)-a.length)+a},f:function(a,b,c,d,e){d=a.toString();(0,window.isNaN)(e)||""==e||(d=(0,window.parseFloat)(a).toFixed(e));var f;f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if((0,window.isNaN)(c)||d.length>=Number(c))return d;d=(0,window.isNaN)(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e); a=Number(c)-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+(0,_.Zc)(" ",a):f+(0,_.Zc)(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,h,k){return _.Py.f((0,window.parseInt)(a,10),b,c,d,0,f,h,k)}};_.Py.i=_.Py.d;_.Py.u=_.Py.d;

var Qy=function(a){a=_.ch(a);_.se(a,function(b,c){_.Nk(c)&&(a[c]=b)});return a},Ry=function(a,b){if(null==b)return b;var c=String(b);c.match(/^\/\/.*/)&&(c=("http:"==window.location.protocol?"http:":"https:")+c);c.match(/^\/([^\/].*)?$/)&&window.location.host&&String(window.location.protocol).match(/^https?:$/)&&(c=window.location.protocol+"//"+window.location.host+c);var d=c.match(/^(https?:)(\/\/)?(\/([^\/].*)?)?$/i);d&&window.location.host&&String(window.location.protocol).match(/^https?:$/)&&
(c=d[1]+"//"+window.location.host+(d[3]||""));c=c.replace(/^(https?:\/\/[^\/?#@]*)\/$/i,"$1");c=c.replace(/^(http:\/\/[-_a-z0-9.]+):0*80([\/?#].*)?$/i,"$1$2");c=c.replace(/^(https:\/\/[-_a-z0-9.]+):0*443([\/?#].*)?$/i,"$1$2");c.match(/^https?:\/\/[-_a-z0-9.]*[-_a-z][-_a-z0-9.]*$/i)&&(c=c.toLowerCase());d=_.E("client/rewrite");_.Wc(d)&&Object.prototype.hasOwnProperty.call(d,c)?c=String(d[c]||c):(c=c.replace(/^(https?):\/\/www\.googleapis\.com$/,"$1://content.googleapis.com"),c=c.replace(/^(https?):\/\/www-(googleapis-[-_a-z0-9]+\.[-_a-z0-9]+\.google\.com)$/,
"$1://content-$2"),c.match(/^https?:\/\/content(-[-_a-z0-9.]+)?\.googleapis\.com$/)||(c=c.replace(/^(https?):\/\/([-_a-z0-9]+(\.[-_a-z0-9]+)?\.googleapis\.com)$/,"$1://content-$2")));a&&(d=_.E("client/firstPartyRewrite"),_.Wc(d)&&Object.prototype.hasOwnProperty.call(d,c)?c=String(d[c]||c):(c=c.replace(/^(https?):\/\/content\.googleapis\.com$/,"$1://clients6.google.com"),c=c.replace(/^(https?):\/\/content-([-a-z0-9]+)\.([-a-z0-9]+)\.googleapis\.com$/,"$1://$2-googleapis.$3.google.com"),c=c.replace(/^(https?):\/\/content-([-a-z0-9]+)\.googleapis\.com$/,
"$1://$2.clients6.google.com"),c=c.replace(/^(https?):\/\/([-a-z0-9]+)-www-googleapis\.([-a-z0-9]+).google.com$/,"$1://content-googleapis-$2.$3.google.com")));return c},Sy={error:{code:-1,message:"A network error occurred and the request could not be completed."}},Ty=function(a){a=_.ch(a);_.nb(a,function(b,c){_.qa(b)&&(a[c]=b.join(", "))});return a},Uy=function(a,b,c){c||((c=_.E("googleapis.config/proxy"))&&(c=String(c).replace(/\/static\/proxy\.html$/,"")||"/"),c=String(c||""));c||(c=_.E("googleapis.config/root"),
b&&(c=_.E("googleapis.config/root-1p")||c),c=String(c||""));c=String(Ry(b,c)||c);return a=_.Uh(c,a)},Vy=function(a,b,c,d){_.bi.call(this);this.xe=a;this.Yc=b;this.Wb=c;this.vu=d;this.kj=null};_.C(Vy,_.bi);
Vy.prototype.then=function(a){this.kj||(this.kj=(new _.Af(function(a,c){this.V("error",(0,_.u)(function(){c(Wy(this))},this));this.V("success",(0,_.u)(function(){a(Wy(this))},this));this.send(this.xe,this.Yc,this.Wb,this.vu)},this)).then(function(a){a.headers=Qy(a.headers);return a},function(a){return a.status?(a.headers=Qy(a.headers),_.Nn(a)):_.Nn({result:Sy,body:'{"error":{"code":-1,"message":"A network error occurred and the request could not be completed."}}',headers:null,status:null,statusText:null})}));
return this.kj.then.apply(this.kj,arguments)};
var Wy=function(a){for(var b=a.getStatus(),c=_.oi(a),d=204==b?!1:""==a.Zl?(0,_.hc)(c):_.pi(a),e={},f=a.getAllResponseHeaders().split("\r\n"),h=0;h<f.length;h++)if(!_.ad(f[h])){var k=_.Wh(f[h],": ",2);e[k[0]]=e[k[0]]?e[k[0]]+(", "+k[1]):k[1]}var l;try{l=2<_.mi(a)?a.La.statusText:""}catch(m){l=""}return{result:d,body:c,headers:e,status:b,statusText:l}},Xy=function(a,b){for(var c=_.Vc(b),d=c?b:arguments,c=c?0:1;c<d.length&&(a=a[d[c]],_.na(a));c++);return a},Yy=function(a){var b=a.params||_.Ra();a=_.ch(b.headers)||
{};var c=b.httpMethod||"GET",d=String(b.url||""),e=b.body||null,b=b.responseType||null,f=_.tk(a);delete a["X-Referer"];a=Ty(a);a=new Vy(d,c,e,a);a.Ii=f;b&&(a.Zl=b);return a},Zy=function(a,b){var c=a.params||_.Ra();c.url=c.path;var d=c.root,d=Uy("/",_.tk(c.headers),d);d.match(/^(.*[^\/])?\/$/)&&(d=d.substr(0,d.length-1));c.root=d;a.params=c;_.Ak.Xq("makeHttpRequests",[a],b)},$y={"'":"\\'"},az={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\",
"<":"<"},bz=function(a,b){var c=function(a){a=_.ch(a);delete a.result;a={gapiRequest:{data:a}};b&&b(a,(0,_.gc)(a))};Yy(a).then(c,c)},cz=function(a){return new _.Af(function(b,c){var d=function(a){a&&a.gapiRequest?a=a.gapiRequest.data||a:c(a);a={result:204!=a.status&&(0,_.hc)(a.body),body:a.body,headers:a.headers||null,status:a.status||null,statusText:a.statusText||null};_.Sh(a.status)?b(a):c(a)};try{Zy(a,d)}catch(e){c(e)}})},dz=function(a){var b;b=(a=Xy(a,"params","headers"))&&_.Wc(a)?a:{};a="chrome-extension"==
(window.location.href.match(_.Oh)[1]||null);b=_.tk(b);var c=!0,d=_.ai(_.Zh);d&&_.na(d.withCredentials)||(c=!1);return!(a&&b)&&c},ez=function(a){_.ef.call(this,a)};_.C(ez,_.ef);ez.prototype.name="gapi.client.Error";var fz=function(a,b){_.E("client/cors")&&dz(a)?bz(a,b):Zy(a,b)},gz=function(a){if(!a||!_.gd(a))throw new ez("Must provide a function.");this.kj=null;this.kZ=a};gz.prototype.then=function(a,b,c){this.kj||(this.kj=this.kZ());return this.kj.then(a,b,c)};
gz.prototype.MA=function(a){this.kj||(this.kj=a)};
var hz=function(a){(0,window.isFinite)(a)&&(a=String(a));return _.t(a)?/^\s*-?0x/i.test(a)?(0,window.parseInt)(a,16):(0,window.parseInt)(a,10):window.NaN},iz=function(a){a=String(a);for(var b=['"'],c=0;c<a.length;c++){var d=a.charAt(c),e=d.charCodeAt(0),f=c+1,h;if(!(h=az[d])){if(!(31<e&&127>e))if(d in $y)d=$y[d];else if(d in az)d=$y[d]=az[d];else{h=d.charCodeAt(0);if(31<h&&127>h)e=d;else{if(256>h){if(e="\\x",16>h||256<h)e+="0"}else e="\\u",4096>h&&(e+="0");e+=h.toString(16).toUpperCase()}d=$y[d]= e}h=d}b[f]=h}b.push('"');return b.join("")};
var jz=function(a,b,c){this.yc=b.name||null;this.cn={};for(a=0;a<c.length;a++)b=c[a],this.cn[b.getTag()]=b};jz.prototype.getName=function(){return this.yc};var kz=function(a){a=_.yd(a.cn);_.fx(a,function(a,c){return a.getTag()-c.getTag()});return a};var lz=function(a,b,c){this.mb=a;this.v8=b;this.yc=c.name;this.kz=!!c.$ia;this.Tj=c.WD;this.k4=c.type};lz.prototype.getTag=function(){return this.v8};lz.prototype.getName=function(){return this.yc};var mz=function(){this.Cc={};this.cn=this.Yj().cn;this.Qi=null},nz=function(a,b,c){c=c||a;for(var d in a.Cc){var e=Number(d);a.cn[e]||b.call(c,e,a.Cc[d])}};_.g=mz.prototype;_.g.has=function(a){return null!=this.Cc[a.getTag()]};_.g.get=function(a,b){return oz(this,a.getTag(),b)};_.g.set=function(a,b){pz(this,a.getTag(),b)};_.g.add=function(a,b){qz(this,a.getTag(),b)};_.g.clear=function(a){a=a.getTag();delete this.Cc[a];this.Qi&&delete this.Qi[a]};
_.g.equals=function(a){if(!a||this.constructor!=a.constructor)return!1;for(var b=kz(this.Yj()),c=0;c<b.length;c++){var d=b[c],e=d.getTag();if(null!=this.Cc[e]!=(null!=a.Cc[e]))return!1;if(null!=this.Cc[e]){var f=11==d.Tj||10==d.Tj,h=rz(this,e),e=rz(a,e);if(d.kz){if(h.length!=e.length)return!1;for(d=0;d<h.length;d++){var k=h[d],l=e[d];if(f?!k.equals(l):k!=l)return!1}}else if(f?!h.equals(e):h!=e)return!1}}return!0};_.g.Qh=function(a){this!=a&&(this.Cc={},this.Qi&&(this.Qi={}),sz(this,a))};
var sz=function(a,b){for(var c=kz(a.Yj()),d=0;d<c.length;d++){var e=c[d],f=e.getTag();if(null!=b.Cc[f]){a.Qi&&delete a.Qi[e.getTag()];var h=11==e.Tj||10==e.Tj;if(e.kz)for(var e=rz(b,f)||[],k=0;k<e.length;k++)qz(a,f,h?e[k].clone():e[k]);else e=rz(b,f),h?(h=rz(a,f))?sz(h,e):pz(a,f,e.clone()):pz(a,f,e)}}};mz.prototype.clone=function(){var a=new this.constructor;a.Qh(this);return a};
var rz=function(a,b){var c=a.Cc[b];return null==c?null:c},oz=function(a,b,c){var d=rz(a,b);return a.cn[b].kz?d[c||0]:d},pz=function(a,b,c){a.Cc[b]=c;a.Qi&&(a.Qi[b]=c)},qz=function(a,b,c){a.Cc[b]||(a.Cc[b]=[]);a.Cc[b].push(c);a.Qi&&delete a.Qi[b]},tz=function(a,b){var c=[],d=b[0],e;for(e in b)0!=e&&c.push(new lz(a,e,b[e]));return new jz(0,d,c)};
var uz=function(){mz.call(this)};_.C(uz,mz);var vz=null,wz=function(){mz.call(this)};_.C(wz,mz);var xz=null;wz.prototype.JN=function(){return oz(this,1)};wz.prototype.setVersion=function(a){pz(this,1,a)};uz.prototype.Yj=function(){var a=vz;a||(vz=a=tz(uz,{0:{name:"Version",EZ:"buzz.channel.Version"},1:{name:"major_version",WD:5,type:Number},2:{name:"minor_version",WD:5,type:Number}}));return a};uz.Yj=uz.prototype.Yj; wz.prototype.Yj=function(){var a=xz;a||(xz=a=tz(wz,{0:{name:"ProtocolVersion",EZ:"buzz.channel.ProtocolVersion"},1:{name:"version",WD:11,type:uz}}));return a};wz.Yj=wz.prototype.Yj;
(function(){var a;return _.He?(a=/Windows NT ([0-9.]+)/,(a=a.exec(_.Cd))?a[1]:"0"):_.Ge?(a=/10[_.][0-9_.]+/,(a=a.exec(_.Cd))?a[0].replace(/_/g,"."):"10"):_.Je?(a=/Android\s+([^\);]+)(\)|;)/,(a=a.exec(_.Cd))?a[1]:""):_.Ke||_.Le||_.Me?(a=/(?:iPhone|CPU)\s+OS\s+(\S+)/,(a=a.exec(_.Cd))?a[1].replace(/_/g,"."):""):""})();
var yz=new wz,zz=new uz;pz(zz,1,3);pz(zz,2,2);yz.setVersion(zz);var Az=new uz;pz(Az,1,3);pz(Az,2,2);var Bz=new uz;pz(Bz,1,3);pz(Bz,2,2);var Cz=function(){};var Dz=function(a,b){this.yT=!!b};_.C(Dz,Cz);Dz.prototype.dm=function(a){var b=new Ez;Fz(this,a,b);return b.toString()};
var Fz=function(a,b,c){var d=kz(b.Yj());(0,_.jd)(d,function(a){if(b.has(a)){var d;d=a.getTag();d=b.cn[d].kz?null!=b.Cc[d]?b.Cc[d].length:0:null!=b.Cc[d]?1:0;for(var e=0;e<d;++e){c.append(a.getName());11==a.Tj||10==a.Tj?(c.append(" {"),Gz(c),c.Hn()):c.append(": ");Hz(this,b.get(a,e),a,c);if(11==a.Tj||10==a.Tj)c.In-=2,c.append("}");Gz(c)}}},a);nz(b,function(a,b){Iz(this,a,b,c)},a)},Iz=function(a,b,c,d){if(null!=c)if(_.qa(c))(0,_.jd)(c,function(a){Iz(this,b,a,d)},a);else{if(_.Wc(c)){d.append(b);d.append(" {");
Gz(d);d.Hn();if(c instanceof mz)Fz(a,c,d);else for(var e in c){var f=hz(e);Iz(a,f,c[e],d)}d.In-=2;d.append("}")}else _.t(c)&&(c=iz(c)),d.append(b),d.append(": "),d.append(c.toString());Gz(d)}},Hz=function(a,b,c,d){switch(c.Tj){case 1:case 2:case 3:case 4:case 5:case 13:case 6:case 7:case 8:case 15:case 16:case 17:case 18:d.append(b);break;case 12:case 9:b=iz(b.toString());d.append(b);break;case 14:if(!a.yT){var e=!1;_.se(c.k4,function(a,c){e||a!=b||(d.append(c),e=!0)})}e&&!a.yT||d.append(b.toString());
break;case 10:case 11:Fz(a,b,d)}},Ez=function(){this.In=0;this.Ub=[];this.kH=!0};Ez.prototype.toString=function(){return this.Ub.join("")};Ez.prototype.Hn=function(){this.In+=2};Ez.prototype.append=function(a){if(this.kH){for(var b=0;b<this.In;++b)this.Ub.push(" ");this.kH=!1}this.Ub.push(a.toString())};var Gz=function(a){a.Ub.push("\n");a.kH=!0};
var Jz=new Dz;mz.prototype.toString=function(){return Jz.dm(this)};new _.ke([1,2,3]);new _.ke([1,2]);var Kz={1:"NativeMessagingTransport",2:"FrameElementMethodTransport",3:"IframeRelayTransport",4:"IframePollingTransport",5:"FlashTransport",6:"NixTransport",7:"DirectTransport"};var Lz=function(a){_.td.call(this);this.Be=a||_.yg()};_.C(Lz,_.td);Lz.prototype.QI=0;Lz.prototype.ra=function(){return this.QI};Lz.prototype.yb=function(){return this.Be.yb()};Lz.prototype.getName=function(){return Kz[String(this.QI)]||""};var Mz=function(a,b){Lz.call(this,b);this.Sd=a;this.HH=this.Sd.UZ().ppu;this.Q5=this.Sd.UZ().lpu;this.DA=[]},Nz,Oz;_.C(Mz,Lz);_.g=Mz.prototype;_.g.x5=5;_.g.QI=4;_.g.cm=0;_.g.Lr=!1;_.g.Hg=!1;_.g.XQ=null;var Pz=function(a){return"googlexpc_"+a.Sd.name+"_msg"},Qz=function(a){return"googlexpc_"+a.Sd.name+"_ack"},Rz=function(a){try{if(!a.Rb&&a.Sd.u3())return a.Sd.Sha().frames||{}}catch(b){}return{}},Sz=function(a,b){return Rz(a)[b]};
Mz.prototype.connect=function(){if(!this.Rb&&this.Sd.u3()){if(!this.Hg){var a=Pz(this);this.xq=Tz(this,a);this.dG=this.yb().frames[a];a=Qz(this);this.$o=Tz(this,a);this.XB=this.yb().frames[a];this.Hg=!0}if(Uz(this,Pz(this))&&Uz(this,Qz(this)))this.KP=new Vz(this,Sz(this,Pz(this)),(0,_.u)(this.L5,this)),this.SK=new Vz(this,Sz(this,Qz(this)),(0,_.u)(this.K5,this)),this.zL();else{if(1==this.Sd.wy()){if(!(this.XQ||0<this.x5--)){for(var b=10,a="";0<b--;)a+="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".charAt(Math.floor(62*
Math.random()));this.Sd.zja(a);Wz(this);this.Hg=!1;this.XQ=Tz(this,"googlexpc_reconnect_"+this.Sd.name)}}else if(0==this.Sd.wy())for(var a=Rz(this),c=a.length,d=0;d<c;d++){try{a[d]&&a[d].name&&(b=a[d].name)}catch(f){}if(b){var e=b.split("_");if(3==e.length&&"googlexpc"==e[0]&&"reconnect"==e[1]){this.Sd.name=e[2];Wz(this);this.Hg=!1;break}}}this.yb().setTimeout((0,_.u)(this.connect,this),100)}}};
var Tz=function(a,b){var c=_.Hg("IFRAME"),d=c.style;d.position="absolute";d.top="-10px";d.left="10px";d.width="1px";d.height="1px";c.id=c.name=b;c.src=a.HH+"#INITIAL";a.yb().document.body.appendChild(c);return c},Wz=function(a){a.xq&&(a.xq.parentNode.removeChild(a.xq),a.xq=null,a.dG=null);a.$o&&(a.$o.parentNode.removeChild(a.$o),a.$o=null,a.XB=null)},Uz=function(a,b){try{var c=Sz(a,b);if(!c||0!=c.location.href.indexOf(a.Q5))return!1}catch(d){return!1}return!0};
Mz.prototype.zL=function(){var a=Rz(this);a[Qz(this)]&&a[Pz(this)]?(this.LP=new Xz(this.HH,this.dG),this.Jw=new Xz(this.HH,this.XB),this.yb().setTimeout((0,_.u)(function(){this.LP.send("SETUP");this.Lr=!0},this),100)):(this.yL||(this.yL=(0,_.u)(this.zL,this)),this.yb().setTimeout(this.yL,100))};var Yz=function(a){if(a.OR&&a.R5&&(a.Sd.Dia(),a.Xs)){for(var b=0,c;b<a.Xs.length;b++)c=a.Xs[b],a.Sd.m9(c.service,c.s5);delete a.Xs}};
Mz.prototype.L5=function(a){if("SETUP"==a)this.Jw&&(this.Jw.send("SETUP_ACK"),this.OR=!0,Yz(this));else if(this.Sd.XO()||this.OR){var b=a.indexOf("|"),c=a.substring(0,b);a=a.substring(b+1);b=c.indexOf(",");if(-1==b){var d;this.Jw.send("ACK:"+c);Zz(this,a)}else d=c.substring(0,b),this.Jw.send("ACK:"+d),c=c.substring(b+1).split("/"),b=(0,window.parseInt)(c[0],10),c=(0,window.parseInt)(c[1],10),1==b&&(this.IG=[]),this.IG.push(a),b==c&&(Zz(this,this.IG.join("")),delete this.IG)}};
Mz.prototype.K5=function(a){"SETUP_ACK"==a?(this.Lr=!1,this.R5=!0,Yz(this)):this.Sd.XO()&&this.Lr&&(0,window.parseInt)(a.split(":")[1],10)==this.cm&&(this.Lr=!1,$z(this))};var $z=function(a){if(!a.Lr&&a.DA.length){var b=a.DA.shift();++a.cm;a.LP.send(a.cm+b);a.Lr=!0}},Zz=function(a,b){var c=b.indexOf(":"),d=b.substr(0,c),c=b.substring(c+1);a.Sd.XO()?a.Sd.m9(d,c):(a.Xs||(a.Xs=[])).push({service:d,s5:c})};
Mz.prototype.send=function(a,b){var c=a+":"+b;if(!_.L||3800>=b.length)this.DA.push("|"+c);else for(var d=b.length,e=Math.ceil(d/3800),f=0,h=1;f<d;)this.DA.push(","+h+"/"+e+"|"+c.substr(f,3800)),h++,f+=3800;$z(this)};Mz.prototype.va=function(){Mz.S.va.call(this);var a=aA;_.rd(a,this.KP);_.rd(a,this.SK);this.KP=this.SK=null;_.Lg(this.xq);_.Lg(this.$o);this.dG=this.XB=this.xq=this.$o=null};
var aA=[],bA=(0,_.u)(function(){var a=aA,b,c=!1;try{for(var d=0;b=a[d];d++)c=c||b.lA()}catch(e){if(b.E8.Sd.Eia(),!a.length)return}a=(0,_.Ca)();c&&(Nz=a);Oz=window.setTimeout(bA,1E3>a-Nz?10:100)},Mz),cA=function(){Nz=(0,_.Ca)();Oz&&window.clearTimeout(Oz);Oz=window.setTimeout(bA,10)},Xz=function(a,b){if(!/^https?:\/\//.test(a))throw Error("ia`"+a);this.L6=a;this.IR=b;this.aD=0};
Xz.prototype.send=function(a){this.aD=++this.aD%2;a=this.L6+"#"+this.aD+(0,window.encodeURIComponent)(a);try{_.Ee?this.IR.location.href=a:this.IR.location.replace(a)}catch(b){}cA()};var Vz=function(a,b,c){this.E8=a;this.UQ=b;this.aY=c;this.XL=this.UQ.location.href.split("#")[0]+"#INITIAL";aA.push(this);cA()};Vz.prototype.lA=function(){var a=this.UQ.location.href;if(a!=this.XL){this.XL=a;if(a=a.split("#")[1])a=a.substr(1),this.aY((0,window.decodeURIComponent)(a));return!0}return!1};
var dA=function(a){this.zv=a;this.qg=!1;this.promise={then:(0,_.u)(function(a,c,d){this.qg||(this.qg=!0);this.yv&&!this.tv?this.zv.resolve(this.yv):this.tv&&!this.yv&&this.zv.reject(this.tv);return this.zv.promise.then(a,c,d)},this)}};dA.prototype.resolve=function(a){this.qg?this.zv.resolve(a):this.yv||this.tv||(this.yv=a)};dA.prototype.reject=function(a){this.qg?this.zv.reject(a):this.yv||this.tv||(this.tv=a)};
var eA=function(a){gz.call(this,eA.prototype.gA);if(!a||"object"!=typeof a&&"string"!=typeof a)throw new ez("Invalid request parameters");a=_.t(a)?{path:a}:a;if(!a.path)throw new ez('Missing required parameter: "path"');this.rA={path:a.path,method:a.method||"GET",params:a.params||{},headers:a.headers||{},body:a.body,root:a.root,responseType:a.responseType};this.HX=a.authType||"auto"};_.C(eA,gz);eA.prototype.Lp=function(){return this.rA};
eA.prototype.ov=function(){var a=this.rA,b=a.headers||{},c=b,d=a.applicationName||null,e=a.clientName||null,f=a.clientVersion||null,f=f||"0.1",e=e||"google-api-javascript-client",h=[];d&&(h.push(d),h.push(" "));h.push(e);f&&(h.push("/"),h.push(f));c["X-JavaScript-User-Agent"]=h.join("");c=b["Content-Type"];a.body&&!c&&(c="application/json",b["Content-Type"]=c);"application/json"!=c||a.params.alt||(a.params.alt="json");(c=a.body||null)&&_.Wc(c)&&(a.body=(0,_.gc)(c));a.key=a.id;b=_.Ak.UK(b,void 0,this.HX);
c=_.tk(b);if(b&&window.navigator){d=[];for(e=0;e<fA.length;e++)(f=window.navigator[fA[e]])&&d.push((0,window.encodeURIComponent)(fA[e])+"="+(0,window.encodeURIComponent)(f));b["X-ClientDetails"]=d.join("&")}(b=_.E("client/apiKey"))&&!_.na(a.params.key)&&(a.params.key=b);(b=_.E("client/trace"))&&!a.params.trace&&(a.params.trace=b);(b=String(a.path||"").match(/^(https?:\/\/[^\/?#]+)([\/?#].*)?$/i))&&!a.root&&(a.root=String(b[1]),a.path=String(b[2]||"/"),a.path.match(/^\/_ah\/api(\/.*)?$/)&&(a.root+=
"/_ah/api",a.path=a.path.substr(8)));b=a.params;d=_.Ok(a.path);e=String(_.E("googleapis.config/xd3")||"");18<=e.length&&"/static/proxy.html"==e.substring(e.length-18)&&(e=e.substring(0,e.length-18));e||(e="/");f=_.Ok(e);if(e!=f)throw Error("G");"/"!=e.charAt(e.length-1)&&(e+="/");d=_.Uh(e,d);_.df(d,"/")&&(d=d.substring(0,d.length-1));d=_.Ph(_.Rh([d],b));a.path=d;a.root=Ry(c,a.root);a.url=Uy(a.path,c,a.root)};
var hA=function(a){a.ov();var b=a.rA;a=b.id;var c=b.key,d=b.url,e=b.path,f=b.method,h=b.body||"",k=b.headers||{},b=b.root,l=String(_.E("client/name","google-api-javascript-client"));return{key:"gapiRequest",params:{id:a,key:c,url:d,path:e,httpMethod:f,body:h,headers:k,urlParams:{},root:b,clientName:l in gA?l:"google-api-javascript-client",clientVersion:String(_.E("client/version","1.1.0-beta"))}}};
eA.prototype.execute=function(a){this.rA.headers.Authorization||_.kk(void 0,void 0);var b=hA(this);fz(b,function(b,d){var c=b;b.gapiRequest&&(c=b.gapiRequest);c&&c.data&&(c=c.data);var c=c instanceof Array?c[0]:c,f;if(204!=c.status&&c.body)try{f=(0,_.hc)(c.body)}catch(h){}a&&a(f,d)})};eA.prototype.gA=function(){var a=hA(this);return _.E("client/cors")&&dz(a)?Yy(a):cz(a)};eA.prototype.Tt=function(){return this.gA()};eA.prototype.execute=eA.prototype.execute;eA.prototype.getPromise=eA.prototype.Tt;
var iA=/<response-(.*)>/,jA=/^application\/http(;.+$|$)/,kA=function(a,b){if(!a||!b||!_.Sa(a,b=b.toLowerCase()))throw new ez("Unable to retrieve header.");return a[b]},nA=function(a,b){for(var c="batch"+String(Math.round(2147483647*(0,_.yk)()))+String(Math.round(2147483647*(0,_.yk)())),d={path:"/batch",headers:{"Content-Type":"multipart/mixed; boundary="+c},method:"POST"},c="--"+c,e=[],f=0;f<a.length;f++)e.push(lA(a[f].request,a[f].id));d.body=[c,e.join("\r\n"+c+"\r\n"),c+"--"].join("\r\n")+"\r\n";
d.root=b||null;return mA(d)},lA=function(a,b){var c=[],d=a.Lp(),e=function(a,b){_.nb(a,function(a,c){b.push(c+": "+a)})};e({"Content-Type":"application/http","Content-Transfer-Encoding":"binary","Content-ID":"<"+b+">"},c);c.push("");c.push(d.method+" "+d.path);e(d.headers,c);c.push("");d.body&&c.push(d.body);return c.join("\r\n")},pA=function(a,b){var c=oA(a,b),d={};_.se(c,function(a,b){d[b]={result:a.result||a.body,rawResult:(0,_.gc)({id:b,result:a.result||a.body}),id:b}});return d},oA=function(a,
b){a=(0,_.Yc)(a);_.df(a,"--")&&(a=a.substring(0,a.length-2));for(var c=a.split(b),d=_.Ra(),e=0;e<c.length;e++)if(c[e]){var f;if(f=c[e]){_.df(f,"\r\n")&&(f=f.substring(0,f.length-2));if(f){f=f.split("\r\n");for(var h=0,k={headers:{},body:""};h<f.length&&""==f[h];)h++;for(k.outerHeaders=qA(f,h);h<f.length&&""!=f[h];)h++;h++;var l=f[h++].split(" ");k.status=Number(l[1]);k.statusText=l[2];for(k.headers=qA(f,h);h<f.length&&""!=f[h];)h++;h++;k.body=f.slice(h).join("\r\n");f=k}else f=null;h=_.Ra();k=kA(f.outerHeaders,
"Content-Type");if(null==jA.exec(k))throw new ez("Unexpected Content-Type");k=kA(f.outerHeaders,"Content-Id");k=iA.exec(k);if(!k)throw new ez("Unable to recognize Content-Id.");h.id=k[1];k=(0,_.hc)(f.body);h.response={result:k,body:f.body,status:f.status,statusText:f.statusText,headers:f.headers};f=h}else f=null;f&&f.id&&(d[f.id]=f.response)}return d},qA=function(a,b){for(var c=_.Ra(),d=b;d<a.length&&a[d];d++){var e=a[d].split(": "),f=(0,_.Yc)(e[0].toLowerCase()),e=(0,_.Yc)(e[1]);c[f]=c[f]?c[f]+(", "+ e):e}return c};
var rA=function(a){gz.call(this,rA.prototype.gA);this.Mc=[];this.Lg=a;this.U3=!!a};_.C(rA,gz);var sA=function(a,b){for(var c=0;c<a.Mc.length;c++)if(a.Mc[c].id==b)return!0;return!1};_.g=rA.prototype;
_.g.add=function(a,b){var c=b||_.Ra(),d=_.Ra();if(a)d.request=a;else throw new ez("Batch entry "+(_.Sa(c,"id")?'"'+c.id+'" ':"")+"is missing a request method");var e;e=_.Ym();e=new dA(e);d.uA=e;a.MA(d.uA.promise);e=a.Lp().root;if(!this.U3){if(e&&this.Lg&&e!=this.Lg)throw new ez('The "root" provided in this request is not consistent with that of existing requests in the batch.');this.Lg=e||this.Lg}if(_.Sa(c,"id")){e=c.id;if(sA(this,e))throw new ez('Batch ID "'+e+'" already in use, please use another.');
d.id=e}else{do d.id=String(Math.round(2147483647*(0,_.yk)()));while(sA(this,d.id))}d.je=c.callback;this.Mc.push(d);return d.id};_.g.execute=function(a){1>this.Mc.length||(_.mb(this.Mc,function(a){a.request.ov()}),a=this.Ru(a),nA(this.Mc,this.Lg).execute(a))};
_.g.gA=function(){if(1>this.Mc.length)return new _.Af(function(a){a({})});_.mb(this.Mc,function(a){a.request.ov()});var a=nA(this.Mc,this.Lg),b=(0,_.u)(function(a){tA(a);if(0!=kA(a.headers,"Content-Type").indexOf("multipart/mixed"))throw new ez("The response's Content-Type is not multipart/mixed.");var b=kA(a.headers,"Content-Type").split("boundary=")[1];if(!b)throw new ez("Boundary not indicated in response.");b=oA(a.body,"--"+b);a.result=b||{};for(var c=0;c<this.Mc.length;c++){var d=this.Mc[c],
k=b[d.id];_.Sh(k.status)?d.uA.resolve(k):d.uA.reject(k)}return a},this),c=(0,_.u)(function(a){for(var b=0;b<this.Mc.length;b++)this.Mc[b].uA.reject({result:{error:{code:0,message:"The batch request could not be fulfilled."}},body:'{"error":{"code":0,"message":"The batch request could not befulfilled"}}',headers:null,status:null,statusText:null});throw a;},this);return a.then(b,c)};_.g.Ru=function(a){return(0,_.u)(function(b,c){this.pC(b,c,a)},this)};
_.g.pC=function(a,b,c){if(b&&!a){var d=(0,_.hc)(b);d&&(a=d.gapiRequest?d.gapiRequest.data:d)}tA(a);if(a){if(0!=kA(a.headers,"Content-Type").indexOf("multipart/mixed"))throw new ez("The response's Content-Type is not multipart/mixed.");if(200<=a.status&&299>=a.status){var e=kA(a.headers,"Content-Type").split("boundary=")[1];if(!e)throw new ez("Boundary not indicated in response.");e=pA(a.body,"--"+e);for(a=0;a<this.Mc.length;a++)if(d=this.Mc[a],delete e[d.id].rawResult,d.je){var f=(0,_.gc)(e[d.id]); d.je(e[d.id]||!1,f)}}c&&c(e||null,b)}};var tA=function(a){if(a&&a.headers){var b=_.Ra(),c;for(c in a.headers)b[c.toLowerCase()]=a.headers[c];a.headers=b}};rA.prototype.add=rA.prototype.add;rA.prototype.execute=rA.prototype.execute;
var fA=["appVersion","platform","userAgent"],gA={"google-api-javascript-client":!0,"google-api-gwt-client":!0},uA="/rpc?fields="+(0,window.encodeURIComponent)(String(["kind","name","version","rootUrl","methods/*/id"]))+"&pp=0",vA="/rest?fields="+(0,window.encodeURIComponent)(String("kind name version rootUrl servicePath resources parameters methods".split(" ")))+"&pp=0",xA=function(a,b,c,d){function e(a){if(a.error)k(a);else{var c=null!=a.rootUrl?String(a.rootUrl):d,c=_.t(c)?c.replace(/([^\/])\/$/,
"$1"):void 0,e;for(e in a)if(a.hasOwnProperty(e)&&"methods"==e){var f=a[e],h;for(h in f)if(f.hasOwnProperty(h)){wA(h,{root:c},void 0);var l={};l[h]=b;_.hb("googleapis.config/versions",l)}}k.call(null)}}var f,h;_.Wc(a)?(h=a,f=a.name,b=a.version):f=a;if(!f||!b)throw new ez("Missing required parameters.");var k=c||function(){};h?e(h):mA({path:"/discovery/v1/apis/"+((0,window.encodeURIComponent)(f)+"/"+(0,window.encodeURIComponent)(b)+uA),callback:e,root:d})},zA=function(a,b,c,d){function e(a){function b(a){_.nb(a,
function(a){yA(e,a,f,l)})}function c(a){_.nb(a,function(a){b(a.methods);(a=a.resources)&&c(a)})}if(a.error)k(a);else{var d=l.root,d=null!=a.rootUrl?String(a.rootUrl):d,d=_.t(d)?d.replace(/([^\/])\/$/,"$1"):void 0;l.root=d;var e=a.servicePath,f=a.parameters;(d=a.resources)&&c(d);(a=a.methods)&&b(a);k.call()}}var f,h;_.Wc(a)?(h=a,f=a.name,a=a.version||"v1"):(f=a,a=b);if(!f||!a)throw new ez("Missing required parameters.");var k=c||function(){},l=_.Wc(d)?d:{};h?e(h):0<f.indexOf("://")?mA({path:f,callback:e}):
mA({path:"/discovery/v1/apis/"+((0,window.encodeURIComponent)(f)+"/"+(0,window.encodeURIComponent)(a)+vA),callback:e,root:d&&d.root})},mA=function(a,b){var c;"object"==typeof a&&(c=a.callback,delete a.callback);var d;d=AA()?new BA(a,b):new eA(a);return c?(d.execute(c),null):d},CA=function(a,b){b=_.ch(b);var c=function(a,b,c){var d;if(a.hasOwnProperty(b))d=a[b],delete a[b];else if(c)throw new ez("Missing required parameters.");return d},d=c(b,"servicePath",!0),e=String(c(b,"restPath",!0)),f=String(c(b,
"httpMethod",!0)),h=c(b,"parameters"),h=null!=h?_.ch(h):null,k=c(b,"parameterName");_.t(k)||(k=null);c=c(b,"supportsSubscription");if(!e||!f)throw new ez("Missing required parameters.");e={id:a,path:e,parameters:h,httpMethod:f,request:{parameterName:k}};c&&(e.supportsSubscription=c);yA(d,e,{path:{},query:{}},b)},wA=function(a,b,c){if(!a)throw new ez("Missing required parameters");for(var d=a.split("."),e=window.gapi.client,f=0;f<d.length-1;f++){var h=d[f];e[h]=e[h]||{};e=e[h]}d=d[d.length-1];if(!e[d]||
c){var k=b||{};e[d]=function(b){var c;c="string"==typeof k?k:k.root;b&&b.root&&(c=b.root);b={method:a,apiVersion:k.apiVersion,rpcParams:b,transport:{name:"googleapis",root:c}};return AA()?new BA(b,2):new DA(b)}}},yA=function(a,b,c,d){if(!(b&&b.id&&b.path&&b.httpMethod))throw new ez("Missing required parameters");var e=b.id.split("."),f=window.gapi.client,h;for(h=0;h<e.length-1;h++){var k=e[h];f[k]=f[k]||{};f=f[k]}k=window.gapi.client[e[0]];k.uJ||(k.uJ={servicePath:a||"",parameters:c});a=e[h];if(!f[a]){if(d&&
d.hasOwnProperty("root"))var l=d.root;f[a]=_.Aa(EA,{path:_.t(b.path)?b.path:null,httpMethod:_.t(b.httpMethod)?b.httpMethod:null,parameters:b.parameters,parameterName:(b.request||{}).parameterName||"",request:b.request,root:l},k.uJ)}},EA=function(a,b,c,d){var e=b.servicePath||"";_.bd(e,"/")||(e="/"+e);var f=FA(a.path,[a.parameters,b.parameters],c||{});b=f.Wl;c=f.M8;e=_.Uh(e,f.path);f=c.root;delete c.root;var h=a.parameterName;!h&&1==_.he(c)&&c.hasOwnProperty("resource")&&(h="resource");var k;h&&(k=
c[h],delete c[h]);null!=k||(k=d);null==k&&a.request&&(_.dh(c)&&(c=void 0),k=c);var h="complete"==_.E("client/rms")?0:1,l={},m=a.httpMethod;"GET"==m&&_.na(k)&&""!=String(k)&&(l["X-HTTP-Method-Override"]=m,m="POST");if((null==k||null!=d)&&c)for(var n in c)_.t(c[n])&&(b[n]=c[n]);return mA({path:e,method:m,params:b,headers:l,body:k,root:f||a.root},h)||null},FA=function(a,b,c){c=_.ch(c);var d={};_.mb(b,function(b){_.nb(b,function(b,e){var f=b.required;if("path"==b.location)if(Object.prototype.hasOwnProperty.call(c,
e))-1!=a.indexOf("{"+e+"}")?(f=_.Nh(c[e]),a=a.replace("{"+e+"}",f)):-1!=a.indexOf("{+"+e+"}")&&(f=(0,window.encodeURI)(String(c[e])),a=a.replace("{+"+e+"}",f)),delete c[e];else{if(f)throw new ez("Required path parameter "+e+" is missing.");}else"query"==b.location&&Object.prototype.hasOwnProperty.call(c,e)&&(d[e]=c[e],delete c[e])})});if(b=c.trace)d.trace=b,delete c.trace;return{path:a,Wl:d,M8:c}},HA=function(a){return AA()?new GA(a,0):new rA(a)},IA=function(a){var b=["complete"],c=_.E("client/rms");
if(_.pd(["rpcDeprecated","migrated"],c))_.Yb(a+" is deprecated. See https://developers.google.com/api-client-library/javascript/reference/referencedocs");else if(_.pd(b,c))throw new ez(a+" is discontinued.");},AA=function(){return"migrated"==_.E("client/rms")};
var JA=function(){this.Mc=[];this.Lg=this.Gf=null};
JA.prototype.add=function(a,b){var c=b||{},d={},e=Object.prototype.hasOwnProperty;if(a)d.vo=a;else throw new ez("Batch entry "+(e.call(c,"id")?'"'+c.id+'" ':"")+"is missing a request method");if(e.call(c,"id")){for(var e=c.id,f=0;f<this.Mc.length;f++)if(this.Mc[f].id==e)throw new ez('Batch ID "'+e+'" already in use, please use another.');d.id=e}else{do d.id=String(2147483647*(0,_.yk)()|0);while(e.call(this.Mc,d.id))}d.je=c.callback;this.Mc.push(d);return d.id};
var KA=function(a){return function(b){var c=b.body;if(b=b.result){for(var d={},e=0,f=b.length;e<f;++e)d[b[e].id]=b[e];a(d,c)}else a(b,c)}};
JA.prototype.execute=function(a){this.Gf=[];for(var b,c,d=0;d<this.Mc.length;d++)b=this.Mc[d],c=b.vo,this.Gf.push(c.zz(b.id)),this.Lg=c.xy()||this.Lg;b={requests:this.Gf,root:this.Lg};a=this.Ru(a);var e;if(b){c={};d=b.headers||{};for(e in d)({}).hasOwnProperty.call(d,e)&&(c[e]=d[e]);c["Content-Type"]="application/json";e={method:"POST",root:b.root||void 0,path:"/rpc",params:b.urlParams,headers:c,body:b.requests||[]}}else e=null;a=KA(a);mA(e).then(a,a)};
JA.prototype.Ru=function(a){var b=this;return function(c,d){b.pC(c,d,a)}};JA.prototype.pC=function(a,b,c){a||(a={});for(var d=0;d<this.Mc.length;d++){var e=this.Mc[d];e.je&&e.je(a[e.id]||!1,b)}c&&c(a,b)};JA.prototype.add=JA.prototype.add;JA.prototype.execute=JA.prototype.execute;
var DA=function(a){if(!a||"object"!=typeof a)throw new ez("Missing rpc parameters");if(!a.method)throw new ez("Missing rpc method");this.zA=a};DA.prototype.xy=function(){var a=this.zA.transport;return a?a.root||null:null};DA.prototype.execute=function(a){var b=new JA;b.add(this,{id:"gapiRpc",callback:this.Ru(a)});b.execute()};
DA.prototype.zz=function(a){var b=this.zA.method,c=String,d;(d=this.zA.apiVersion)||(d=String(b).split(".")[0],d=_.E("googleapis.config/versions/"+b)||_.E("googleapis.config/versions/"+d)||"v1",d=String(d));c=c(d);a={jsonrpc:"2.0",id:a,method:b,apiVersion:c};(b=this.zA.rpcParams)&&(a.params=b);return a};
DA.prototype.Ru=function(a){return function(b,c){var d;b?b.error?(d=b.error,null==d.error&&(d.error=_.ch(b.error))):(d=b.result||b.data,_.Wc(d)&&null==d.result&&(d.result=_.ch(b.result||b.data))):d=!1;a(d,c)}};DA.prototype.execute=DA.prototype.execute;
var BA=function(a,b){this.sf=b||0;if(2==this.sf){var c=null;null!=a&&_.Wc(a)&&(c={method:a.method,rpcParams:a.rpcParams,transport:a.transport,root:a.root,apiVersion:a.apiVersion,authType:a.authType});this.Ff=new DA(c)}else 0==this.sf&&(c=a&&a.callback)&&(a.callback=LA(c)),c=null,null!=a&&(_.Wc(a)?c={path:a.path,method:a.method,params:a.params,headers:a.headers,body:a.body,root:a.root,responseType:a.responseType,authType:a.authType}:_.t(a)&&(c=a)),this.Ff=new eA(c)},LA=function(a){return function(b){var c;
null!=b&&_.Wc(b)&&b.error?(c=MA(b),b=(0,_.gc)([{id:"gapiRpc",error:c}]),c.error=_.Vh(c)):(null!=b||(b={}),c=_.Vh(b),c.result=_.Vh(b),b=(0,_.gc)([{id:"gapiRpc",result:b}]));a(c,b)}},MA=function(a){a=_.Vh(a.error);return{code:a.code,data:a.errors,message:a.message}};_.g=BA.prototype;_.g.getFormat=function(){return this.sf};_.g.execute=function(a){this.Ff.execute(a&&1==this.sf?LA(a):a)};
_.g.then=function(a,b,c){2==this.sf&&NA('The "then" method is not available on this object.');return this.Ff.then(a,b,c)};_.g.MA=function(a){this.Ff.MA&&this.Ff.MA(a)};_.g.Lp=function(){if(this.Ff.Lp)return this.Ff.Lp()};_.g.ov=function(){this.Ff.Lp&&this.Ff.ov()};_.g.xy=function(){if(this.Ff.xy)return this.Ff.xy()};_.g.zz=function(a){if(this.Ff.zz)return this.Ff.zz(a)};_.g.Tt=function(){if(this.Ff.Tt)return this.Ff.Tt()};var GA=function(a,b){this.j5=a;this.sf=b||null;this.Ds=null};
GA.prototype.add=function(a,b){null===this.sf&&(this.sf=a.getFormat(),this.Ds=2==this.sf?new JA:new rA(this.j5));this.sf!==a.getFormat()&&NA("Unable to add item to batch.");var c=b&&b.callback;1==this.sf&&c&&(b.callback=function(a){a=OA(a);var b=(0,_.gc)([a]);c(a,b)});return this.Ds.add(a,b)};GA.prototype.execute=function(a){var b;b=a&&1==this.sf?function(b){var c=[];_.nb(b,function(a,d){a=OA(a);b[d]=a;c.push(a)});var e=(0,_.gc)(c);a(b,e)}:a;this.Ds&&this.Ds.execute(b)};
var OA=function(a){var b=a?Xy(a,"result"):null;_.Wc(b)&&null!=b.error&&(b=MA(b),a={id:a.id,error:b});return a};GA.prototype.then=function(a,b,c){2==this.sf&&NA('The "then" method is not available on this object.');return this.Ds.then(a,b,c)};var NA=function(a){throw Error("ja`"+a);};BA.prototype.execute=BA.prototype.execute;BA.prototype.then=BA.prototype.then;BA.prototype.getPromise=BA.prototype.Tt;GA.prototype.add=GA.prototype.add;GA.prototype.execute=GA.prototype.execute;GA.prototype.then=GA.prototype.then;
_.D("gapi.client.load",function(a,b,c,d){function e(b){var c="migrated"==l||"complete"==l;_.Wc(a)&&(c=a.kind?"discovery#rpcDescription"!=a.kind:null!=a.servicePath);c?zA(a,f,b,k):_.t(a)&&xA(a,f,b,h)}var f=b||"v1",h=_.Wc(d)?d.root:d,k=_.Wc(d)?d:{root:h},l=_.E("client/rms");if(c)e(c);else return new _.Af(function(a,b){function c(c){c&&c.error?b(c):a()}try{e(c)}catch(v){b(v)}})});_.D("gapi.client.newBatch",function(a){return AA()?new GA(a):"complete"==_.E("client/rms")?HA(a):new JA});
_.D("gapi.client.newRpcBatch",function(){IA("gapi.client.newRpcBatch");return AA()?new GA:new JA});_.D("gapi.client.newHttpBatch",HA);_.D("gapi.client.register",function(a,b){if("complete"==_.E("client/rms"))CA(a,b);else{IA("gapi.client.register");var c;b&&(c={apiVersion:b.apiVersion,root:b.root});wA(a,c)}});_.D("gapi.client.request",mA);
_.D("gapi.client.rpcRequest",function(a,b,c){IA("gapi.client.rpcRequest");if(!a)throw new ez('Missing required parameter "method".');a={method:a,apiVersion:b,rpcParams:c,transport:{name:"googleapis",root:c&&c.root||""}};return AA()?new BA(a,2):new DA(a)});_.D("gapi.client.setApiKey",function(a){_.hb("client/apiKey",a);_.hb("googleapis.config/developerKey",a)});_.D("gapi.client.setApiVersions",function(a){_.hb("googleapis.config/versions",a)}); _.D("gapi.client.AuthType",{E9:"auto",NONE:"none",qda:"oauth2",nba:"1p"});_.D("gapi.client.AuthType.AUTO","auto");_.D("gapi.client.AuthType.NONE","none");_.D("gapi.client.AuthType.OAUTH2","oauth2");_.D("gapi.client.AuthType.FIRST_PARTY","1p");

});
// Google Inc.
