try{
fi(K.Ma(),"sy335");var wx=function(a,b){for(var c=b||Szd,d=c.length,e="";0<a--;)e+=c.charAt(Math.floor(Math.random()*d));return e},Szd="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
di(K.Ma(),"sy335");gi(K.Ma(),"sy335");
}catch(e){_DumpException(e)}
try{
fi(K.Ma(),"sy557");
di(K.Ma(),"sy557");gi(K.Ma(),"sy557");
}catch(e){_DumpException(e)}
try{
var rL={},fEe=["pu","lru","pru","lpu","ppu"],gEe={1:"NativeMessagingTransport",2:"FrameElementMethodTransport",3:"IframeRelayTransport",4:"IframePollingTransport",5:"FlashTransport",6:"NixTransport",7:"DirectTransport"};fi(K.Ma(),"sy334");var hEe=function(){v.call(this);this.Ns={}};r(hEe,v);f=hEe.prototype;f.connect=function(a){a&&a()};f.tq=function(){return!0};f.registerService=function(a,b,c){this.Ns[a]={callback:b,Ryb:!!c}};f.getService=function(a,b){var c=this.Ns[a];return c?c:this.Ca?{callback:Fa(this.Ca,a),Ryb:Ba(b)}:null};f.Sa=function(){hEe.Ea.Sa.call(this);delete this.Fa;delete this.Ns;delete this.Ca};
var sL=function(a){v.call(this);this.Jb=a||Ie()};r(sL,v);sL.prototype.vP=0;sL.prototype.getType=function(){return this.vP};sL.prototype.getWindow=function(){return this.Jb.getWindow()};sL.prototype.getName=function(){return gEe[String(this.vP)]||""};var jEe=function(a,b){sL.call(this,b);this.ld=a;this.Pa=new B(this);this.Ya(this.Pa);this.Aa=new Sd(100,this.getWindow());this.Ya(this.Aa);this.wa=new Ff;this.Ga=new Ff;this.ha=new Ff;this.Da=wx(10);this.Ca=null;this.ra={};this.Ha=this.ld.name;iEe(this.ld,this.ld.name+"_"+tL(this.ld));this.Fa=!1;Lf(this.ha,this.wa);Lf(this.ha,this.Ga);this.ha.addCallback(this.xnc,this);this.ha.callback(!0);this.Pa.listen(this.Aa,"tick",this.Ipb)};r(jEe,sL);
var kEe={},nEe=function(a){var b=new lEe(a.channelName,a.service,a.payload);a=b.ha;var c=b.service,b=b.payload,d=rL[a];if(d)return d.ra(c,b),!0;var d=mEe(b)[0],e;for(e in rL){var g=rL[e];if(1==tL(g)&&!g.tq()&&"tp"==c&&"SETUP"==d)return iEe(g,a),g.ra(c,b),!0}return!1};f=jEe.prototype;f.vP=7;
f.QFa=function(a){a=mEe(a);var b=a[1];switch(a[0]){case "SETUP_ACK":this.wa.ha||this.wa.callback(!0);break;case "SETUP":this.send("tp","SETUP_ACK"),this.Ga.ha||this.Ga.callback(!0),null!=this.Ca&&this.Ca!=b&&this.send("tp","SETUP,"+this.Da),this.Ca=b}};f.connect=function(){var a=this.getWindow();if(a){var b=Ea(a);0==(kEe[b]||0)&&null==qa("crosswindowmessaging.channel",a)&&pa("crosswindowmessaging.channel",nEe,a);kEe[b]++;this.Fa=!0;this.Ipb()}};
f.Ipb=function(){this.ld.tq()?this.Aa.stop():(this.Aa.start(),this.send("tp","SETUP,"+this.Da))};f.send=function(a,b){if(this.ld.SF){var c=new lEe(this.Ha+"_"+(0==tL(this.ld)?1:0),a,b);this.ld.Kb().directSyncMode?this.Ykb(c):this.ra[Ea(c)]=Td(m(this.Ykb,this,c),0)}};f.Ykb=function(a){var b=Ea(a);this.ra[b]&&delete this.ra[b];try{var c=qa("crosswindowmessaging.channel",this.ld.SF)}catch(d){return}if(null!==c)try{c({channelName:a.ha,service:a.service,payload:a.payload})}catch(d){}};
f.xnc=function(){uL(this.ld,(this.ld.Kb(),0))};f.Sa=function(){if(this.Fa){var a=this.getWindow(),b=Ea(a);1==--kEe[b]&&pa("crosswindowmessaging.channel",null,a)}this.ra&&(Zb(this.ra,function(a){Ud(a)}),this.ra=null);this.wa&&(this.wa.cancel(),delete this.wa);this.Ga&&(this.Ga.cancel(),delete this.Ga);this.ha&&(this.ha.cancel(),delete this.ha);jEe.Ea.Sa.call(this)};var mEe=function(a){a=a.split(",");a[1]=a[1]||null;return a},lEe=function(a,b,c){this.ha=a;this.service=b;this.payload=c};
var oEe=function(a,b){sL.call(this,b);this.ld=a;this.ra=[];this.Aa=m(this.Bcc,this)};r(oEe,sL);f=oEe.prototype;f.vP=2;f.E1a=!1;f.connect=function(){0==tL(this.ld)?(this.ha=this.ld.s$,this.ha.XPC_toOuter=m(this.Xtb,this)):this.Hcb()};
f.Hcb=function(){var a=!0;try{this.ha||(this.ha=this.getWindow().frameElement),this.ha&&this.ha.XPC_toOuter&&(this.wa=this.ha.XPC_toOuter,this.ha.XPC_toOuter.XPC_toInner=m(this.Xtb,this),a=!1,this.send("tp","SETUP_ACK"),uL(this.ld))}catch(b){}a&&(this.Ga||(this.Ga=m(this.Hcb,this)),this.getWindow().setTimeout(this.Ga,100))};f.QFa=function(a){if(0!=tL(this.ld)||this.ld.tq()||"SETUP_ACK"!=a)throw Error("Ke");this.wa=this.ha.XPC_toOuter.XPC_toInner;uL(this.ld)};
f.Xtb=function(a,b){this.E1a||0!=this.ra.length?(this.ra.push({serviceName:a,payload:b}),1==this.ra.length&&this.getWindow().setTimeout(this.Aa,1)):this.ld.ra(a,b)};f.Bcc=function(){for(;this.ra.length;){var a=this.ra.shift();this.ld.ra(a.serviceName,a.payload)}};f.send=function(a,b){this.E1a=!0;this.wa(a,b);this.E1a=!1};f.Sa=function(){oEe.Ea.Sa.call(this);this.ha=this.wa=null};
var vL=function(a,b){sL.call(this,b);this.ld=a;this.Ia=this.ld.Kb().ppu;this.nb=this.ld.Kb().lpu;this.Ca=[]},pEe,qEe;r(vL,sL);f=vL.prototype;f.a0c=5;f.vP=4;f.oRa=0;f.yda=!1;f.Qva=!1;f.aJb=null;var rEe=function(a){return"googlexpc_"+a.ld.name+"_msg"},sEe=function(a){return"googlexpc_"+a.ld.name+"_ack"},uEe=function(a){try{if(!a.isDisposed()&&tEe(a.ld))return a.ld.SF.frames||{}}catch(b){}return{}},vEe=function(a,b){return uEe(a)[b]};
vL.prototype.connect=function(){if(!this.isDisposed()&&tEe(this.ld)){if(!this.Qva){var a=rEe(this);this.ra=wEe(this,a);this.Ha=this.getWindow().frames[a];a=sEe(this);this.ha=wEe(this,a);this.Da=this.getWindow().frames[a];this.Qva=!0}if(xEe(this,rEe(this))&&xEe(this,sEe(this)))this.Ta=new yEe(this,vEe(this,rEe(this)),m(this.Xa,this)),this.Ja=new yEe(this,vEe(this,sEe(this)),m(this.Za,this)),this.Ra();else{if(1==tL(this.ld))this.aJb||0<this.a0c--||(iEe(this.ld,wx(10)),zEe(this),this.Qva=!1,this.aJb=
wEe(this,"googlexpc_reconnect_"+this.ld.name));else if(0==tL(this.ld))for(var a=uEe(this),b=a.length,c=0;c<b;c++){var d;try{a[c]&&a[c].name&&(d=a[c].name)}catch(g){}if(d){var e=d.split("_");if(3==e.length&&"googlexpc"==e[0]&&"reconnect"==e[1]){this.ld.name=e[2];zEe(this);this.Qva=!1;break}}}this.getWindow().setTimeout(m(this.connect,this),100)}}};
var wEe=function(a,b){var c=Ue("IFRAME"),d=c.style;d.position="absolute";d.top="-10px";d.left="10px";d.width="1px";d.height="1px";c.id=c.name=b;c.src=a.Ia+"#INITIAL";a.getWindow().document.body.appendChild(c);return c},zEe=function(a){a.ra&&(a.ra.parentNode.removeChild(a.ra),a.ra=null,a.Ha=null);a.ha&&(a.ha.parentNode.removeChild(a.ha),a.ha=null,a.Da=null)},xEe=function(a,b){try{var c=vEe(a,b);if(!c||0!=c.location.href.indexOf(a.nb))return!1}catch(d){return!1}return!0};
vL.prototype.Ra=function(){var a=uEe(this);a[sEe(this)]&&a[rEe(this)]?(this.Gc=new AEe(this.Ia,this.Ha),this.Aa=new AEe(this.Ia,this.Da),this.getWindow().setTimeout(m(function(){this.Gc.send("SETUP");this.yda=!0},this),100)):(this.Qa||(this.Qa=m(this.Ra,this)),this.getWindow().setTimeout(this.Qa,100))};var BEe=function(a){if(a.Va&&a.Cb&&(uL(a.ld),a.wa)){for(var b=0,c;b<a.wa.length;b++)c=a.wa[b],a.ld.ra(c.service,c.payload);delete a.wa}};
vL.prototype.Xa=function(a){if("SETUP"==a)this.Aa&&(this.Aa.send("SETUP_ACK"),this.Va=!0,BEe(this));else if(this.ld.tq()||this.Va){var b=a.indexOf("|"),c=a.substring(0,b);a=a.substring(b+1);b=c.indexOf(",");if(-1==b){var d;this.Aa.send("ACK:"+c);CEe(this,a)}else d=c.substring(0,b),this.Aa.send("ACK:"+d),c=c.substring(b+1).split("/"),b=parseInt(c[0],10),c=parseInt(c[1],10),1==b&&(this.Fa=[]),this.Fa.push(a),b==c&&(CEe(this,this.Fa.join("")),delete this.Fa)}};
vL.prototype.Za=function(a){"SETUP_ACK"==a?(this.yda=!1,this.Cb=!0,BEe(this)):this.ld.tq()&&this.yda&&parseInt(a.split(":")[1],10)==this.oRa&&(this.yda=!1,DEe(this))};var DEe=function(a){if(!a.yda&&a.Ca.length){var b=a.Ca.shift();++a.oRa;a.Gc.send(a.oRa+b);a.yda=!0}},CEe=function(a,b){var c=b.indexOf(":"),d=b.substr(0,c),c=b.substring(c+1);a.ld.tq()?a.ld.ra(d,c):(a.wa||(a.wa=[])).push({service:d,payload:c})};vL.prototype.Ga=3800;
vL.prototype.send=function(a,b){var c=a+":"+b;if(!u||b.length<=this.Ga)this.Ca.push("|"+c);else for(var d=b.length,e=Math.ceil(d/this.Ga),g=0,h=1;g<d;)this.Ca.push(","+h+"/"+e+"|"+c.substr(g,this.Ga)),h++,g+=this.Ga;DEe(this)};vL.prototype.Sa=function(){vL.Ea.Sa.call(this);var a=EEe;Ab(a,this.Ta);Ab(a,this.Ja);this.Ta=this.Ja=null;$e(this.ra);$e(this.ha);this.Ha=this.Da=this.ra=this.ha=null};
var EEe=[],FEe=m(function(){var a=EEe,b,c=!1;try{for(var d=0;b=a[d];d++)c=c||b.receive()}catch(e){if(b.Ga.ld.close(),!a.length)return}a=q();c&&(pEe=a);qEe=window.setTimeout(FEe,1E3>a-pEe?10:100)},vL),GEe=function(){pEe=q();qEe&&window.clearTimeout(qEe);qEe=window.setTimeout(FEe,10)},AEe=function(a,b){if(!/^https?:\/\//.test(a))throw Error("Le`"+a);this.wa=a;this.ra=b;this.ha=0};
AEe.prototype.send=function(a){this.ha=++this.ha%2;a=this.wa+"#"+this.ha+encodeURIComponent(a);try{ed?this.ra.location.href=a:this.ra.location.replace(a)}catch(b){}GEe()};var yEe=function(a,b,c){this.Ga=a;this.ra=b;this.wa=c;this.ha=this.ra.location.href.split("#")[0]+"#INITIAL";EEe.push(this);GEe()};yEe.prototype.receive=function(){var a=this.ra.location.href;if(a!=this.ha){this.ha=a;if(a=a.split("#")[1])a=a.substr(1),this.wa(decodeURIComponent(a));return!0}return!1};
var wL=function(a,b){sL.call(this,b);this.ld=a;this.ra=this.ld.Kb().pru;this.ha=this.ld.Kb().ifrid;ed&&HEe()};r(wL,sL);if(ed)var IEe=[],JEe=0,HEe=function(){JEe||(JEe=window.setTimeout(function(){KEe()},1E3))},KEe=function(a){var b=q();for(a=a||3E3;IEe.length&&b-IEe[0].timestamp>=a;){var c=IEe.shift().Wyc;$e(c)}JEe=window.setTimeout(LEe,1E3)},LEe=function(){KEe()};var MEe={};wL.prototype.vP=3;
wL.prototype.connect=function(){this.getWindow().xpcRelay||(this.getWindow().xpcRelay=NEe);this.send("tp","SETUP")};var NEe=function(a,b){var c=b.indexOf(":"),d=b.substr(0,c),e=b.substr(c+1);if(u&&-1!=(c=d.indexOf("|"))){var g=d.substr(0,c),d=d.substr(c+1),c=d.indexOf("+"),h=d.substr(0,c),c=parseInt(d.substr(c+1),10),l=MEe[h];l||(l=MEe[h]={Bmb:[],XIb:0,dlb:0});Xa(d,"++")&&(l.dlb=c+1);l.Bmb[c]=e;l.XIb++;if(l.XIb!=l.dlb)return;e=l.Bmb.join("");delete MEe[h]}else var g=d;rL[a].ra(g,decodeURIComponent(e))};
wL.prototype.QFa=function(a){"SETUP"==a?(this.send("tp","SETUP_ACK"),uL(this.ld)):"SETUP_ACK"==a&&uL(this.ld)};wL.prototype.send=function(a,b){var c=encodeURIComponent(b),d=c.length;if(u&&1800<d)for(var e=db(),g=0,h=0;g<d;h++){var l=c.substr(g,1800),g=g+1800;OEe(this,a,l,e+(g>=d?"++":"+")+h)}else OEe(this,a,c)};
var OEe=function(a,b,c,d){if(u){var e=a.getWindow().document.createElement("DIV");Ee(e,wca(null,null,{onload:xc("this.xpcOnload()"),sandbox:null}));e=e.childNodes[0];e.xpcOnload=PEe}else e=a.getWindow().document.createElement("IFRAME"),ed?IEe.push({timestamp:q(),Wyc:e}):wd(e,"load",PEe);var g=e.style;g.visibility="hidden";g.width=e.style.height="0px";g.position="absolute";g=a.ra;g+="#"+a.ld.name;a.ha&&(g+=","+a.ha);g+="|"+b;d&&(g+="|"+d);e.src=g+(":"+c);a.getWindow().document.body.appendChild(e)}, PEe=function(){$e(this);this.Ha=null};wL.prototype.Sa=function(){wL.Ea.Sa.call(this);ed&&KEe(0)};
var xL=function(a,b,c,d,e){sL.call(this,c);this.ld=a;this.Aa=e||2;this.Qa=b||"*";this.Pa=new B(this);this.Ca=new Sd(100,this.getWindow());this.Ha=!!d;this.wa=new Ff;this.Ga=new Ff;this.ra=new Ff;this.Ja=wx(10);this.Fa=null;this.Ha?1==tL(this.ld)?Lf(this.ra,this.wa):Lf(this.ra,this.Ga):(Lf(this.ra,this.wa),2==this.Aa&&Lf(this.ra,this.Ga));this.ra.addCallback(this.ync,this);this.ra.callback(!0);this.Pa.listen(this.Ca,"tick",this.Jpb)};r(xL,sL);xL.prototype.ha=null;xL.prototype.Ia=!1;
xL.prototype.vP=1;var QEe={};xL.prototype.Da=0;var SEe=function(a){var b=a.Gf.data;if(!xa(b))return!1;var c=b.indexOf("|"),d=b.indexOf(":");if(-1==c||-1==d)return!1;var e=b.substring(0,c),c=b.substring(c+1,d),b=b.substring(d+1);if(d=rL[e])return d.ra(c,b,a.Gf.origin),!0;a=REe(b)[0];for(var g in rL)if(d=rL[g],1==tL(d)&&!d.tq()&&"tp"==c&&("SETUP"==a||"SETUP_NTPV2"==a))return iEe(d,e),d.ra(c,b),!0;return!1};
xL.prototype.QFa=function(a){var b=REe(a);a=b[1];switch(b[0]){case "SETUP_ACK":TEe(this,1);this.wa.ha||this.wa.callback(!0);break;case "SETUP_ACK_NTPV2":2==this.Aa&&(TEe(this,2),this.wa.ha||this.wa.callback(!0));break;case "SETUP":TEe(this,1);UEe(this,1);break;case "SETUP_NTPV2":2==this.Aa&&(b=this.ha,TEe(this,2),UEe(this,2),1!=b&&null==this.Fa||this.Fa==a||VEe(this),this.Fa=a)}};
var VEe=function(a){2!=a.Aa||null!=a.ha&&2!=a.ha||a.send("tp","SETUP_NTPV2,"+a.Ja);null!=a.ha&&1!=a.ha||a.send("tp","SETUP")},UEe=function(a,b){if(2!=a.Aa||null!=a.ha&&2!=a.ha||2!=b){if(null!=a.ha&&1!=a.ha||1!=b)return;a.send("tp","SETUP_ACK")}else a.send("tp","SETUP_ACK_NTPV2");a.Ga.ha||a.Ga.callback(!0)},TEe=function(a,b){b>a.ha&&(a.ha=b);1==a.ha&&(a.Ga.ha||a.Ha||a.Ga.callback(!0),a.Fa=null)};f=xL.prototype;
f.connect=function(){var a=this.getWindow(),b=Ea(a),c=QEe[b];za(c)||(c=0);0==c&&wd(a.postMessage?a:a.document,"message",SEe,!1,xL);QEe[b]=c+1;this.Ia=!0;this.Jpb()};f.Jpb=function(){var a=0==tL(this.ld);this.Ha&&a||this.ld.tq()||this.isDisposed()?this.Ca.stop():(this.Ca.start(),VEe(this))};
f.send=function(a,b){var c=this.ld.SF;c&&(this.send=function(a,b){var d=this,e=this.ld.name;this.Da=Td(function(){d.Da=0;try{var g=c.postMessage?c:c.document;g.postMessage&&g.postMessage(e+"|"+a+":"+b,d.Qa)}catch(n){}},0)},this.send(a,b))};f.ync=function(){uL(this.ld,1==this.Aa||1==this.ha?200:void 0)};
f.Sa=function(){if(this.Ia){var a=this.getWindow(),b=Ea(a),c=QEe[b];QEe[b]=c-1;1==c&&Ad(a.postMessage?a:a.document,"message",SEe,!1,xL)}this.Da&&(Ud(this.Da),this.Da=0);x(this.Pa);delete this.Pa;x(this.Ca);delete this.Ca;this.wa.cancel();delete this.wa;this.Ga.cancel();delete this.Ga;this.ra.cancel();delete this.ra;delete this.send;xL.Ea.Sa.call(this)};var REe=function(a){a=a.split(",");a[1]=a[1]||null;return a};
var WEe=function(a,b){sL.call(this,b);this.ld=a;this.ha=a.at||"";this.ra=a.rat||"";var c=this.getWindow();if(!c.nix_setup_complete)try{c.execScript("Class GCXPC____NIXVBS_wrapper\n Private m_Transport\nPrivate m_Auth\nPublic Sub SetTransport(transport)\nIf isEmpty(m_Transport) Then\nSet m_Transport = transport\nEnd If\nEnd Sub\nPublic Sub SetAuth(auth)\nIf isEmpty(m_Auth) Then\nm_Auth = auth\nEnd If\nEnd Sub\nPublic Function GetAuthToken()\n GetAuthToken = m_Auth\nEnd Function\nPublic Sub SendMessage(service, payload)\n Call m_Transport.GCXPC____NIXJS_handle_message(service, payload)\nEnd Sub\nPublic Sub CreateChannel(channel)\n Call m_Transport.GCXPC____NIXJS_create_channel(channel)\nEnd Sub\nPublic Sub GCXPC____NIXVBS_container()\n End Sub\nEnd Class\n Function GCXPC____NIXVBS_get_wrapper(transport, auth)\nDim wrap\nSet wrap = New GCXPC____NIXVBS_wrapper\nwrap.SetTransport transport\nwrap.SetAuth auth\nSet GCXPC____NIXVBS_get_wrapper = wrap\nEnd Function",
"vbscript"),c.nix_setup_complete=!0}catch(d){}this.GCXPC____NIXJS_handle_message=this.Anc;this.GCXPC____NIXJS_create_channel=this.znc};r(WEe,sL);var XEe=function(){var a=!1;try{var b=window.opener;window.opener={};a=Kca(window,"opener");window.opener=b}catch(c){}return a};f=WEe.prototype;f.vP=6;f.vaa=!1;f.S3=null;f.connect=function(){0==tL(this.ld)?this.Gcb():this.Fcb()};
f.Gcb=function(){if(!this.vaa){var a=this.ld.s$;try{var b=this.getWindow().GCXPC____NIXVBS_get_wrapper;a.contentWindow.opener=b(this,this.ha);this.vaa=!0}catch(c){}this.vaa||this.getWindow().setTimeout(m(this.Gcb,this),100)}};
f.Fcb=function(){if(!this.vaa){try{var a=this.getWindow().opener;if(a&&"GCXPC____NIXVBS_container"in a){this.S3=a;if(this.S3.GetAuthToken()!=this.ra)return;var b=this.getWindow().GCXPC____NIXVBS_get_wrapper;this.S3.CreateChannel(b(this,this.ha));this.vaa=!0;uL(this.ld)}}catch(c){return}this.vaa||this.getWindow().setTimeout(m(this.Fcb,this),100)}};f.znc=function(a){this.S3=a;this.S3.GetAuthToken()==this.ra&&uL(this.ld)}; f.Anc=function(a,b){this.getWindow().setTimeout(m(function(){this.ld.ra(a,b)},this),1)};f.send=function(a,b){this.S3.SendMessage(a,b)};f.Sa=function(){WEe.Ea.Sa.call(this);this.S3=null};
var yL=function(a,b){hEe.call(this);for(var c=0,d;d=fEe[c];c++)if(d in a&&!/^https?:\/\//.test(a[d]))throw Error("Me`"+a[d]+"`"+d);this.ha=a;this.name=this.ha.cn||wx(10);this.Jb=b||Ie();this.wa=[];this.Ga=new B(this);a.lpu=a.lpu||ae(this.Jb.getWindow().location.href)+"/robots.txt";a.ppu=a.ppu||ae(a.pu||"")+"/robots.txt";rL[this.name]=this;Yda(window,"unload",YEe)||zd(window,"unload",YEe)};r(yL,hEe);var ZEe=/^%*tp$/,$Ee=/^%+tp$/;f=yL.prototype;f.oV=null;f.EO=null;f.qF=null;f.Eb=1;
f.tq=function(){return 2==this.Eb};f.SF=null;f.s$=null;f.Kb=function(){return this.ha};
var tEe=function(a){try{return!!a.SF&&!a.SF.closed}catch(b){return!1}},aFe=function(a){var b={};b.cn=a.name;b.tp=a.ha.tp;b.osh=a.ha.osh;a.ha.lru&&(b.pru=a.ha.lru);a.ha.lpu&&(b.ppu=a.ha.lpu);a.ha.ppu&&(b.lpu=a.ha.ppu);(a=a.ha.role)&&(b.role=1==a?0:1);return b},dFe=function(a,b,c,d){var e=a.ha.ifrid;e||(e=a.ha.ifrid="xpcpeer"+wx(4));var g=Ie(b).createElement("IFRAME");g.id=g.name=e;c?c(g):g.style.width=g.style.height="100%";bFe(a);a.EO=new Ff(void 0,a);var h=cFe(a,d);Kg(a.Ga,g,"load",a.EO.callback,
!1,a.EO);dd||ed?window.setTimeout(m(function(){b.appendChild(g);g.src=h.toString()},a),1):(g.src=h.toString(),b.appendChild(g));return g},bFe=function(a){a.EO&&(a.EO.cancel(),a.EO=null);a.wa.length=0;a.Ga.removeAll()},cFe=function(a,b){var c=a.ha.pu;xa(c)&&(c=a.ha.pu=new ie(c));!1!==b&&qe(c,"xpc",Fd(aFe(a)));return c};yL.prototype.connect=function(a){this.Aa=a||sa;3==this.Eb&&(this.Eb=1);this.EO?this.EO.addCallback(this.Da):this.Da()};
yL.prototype.Da=function(){this.EO=null;this.ha.ifrid&&(this.s$=this.Jb.Ba(this.ha.ifrid));if(this.s$){var a=this.s$.contentWindow;a||(a=window.frames[this.ha.ifrid]);this.SF=a}if(!this.SF){if(window==window.top)throw Error("Oe");this.SF=window.parent}if(!this.qF){this.ha.tp||(this.ha.tp=Aa(document.postMessage)||Aa(window.postMessage)||u&&window.postMessage?1:dd?2:u&&this.ha.pru?3:u&&XEe()?6:4);switch(this.ha.tp){case 1:this.qF=new xL(this,this.ha.ph,this.Jb,!!this.ha.osh,this.ha.nativeProtocolVersion||
2);break;case 6:this.qF=new WEe(this,this.Jb);break;case 2:this.qF=new oEe(this,this.Jb);break;case 3:this.qF=new wL(this,this.Jb);break;case 4:this.qF=new vL(this,this.Jb);break;case 7:if(a=this.SF)try{a=window.document.domain==this.SF.document.domain}catch(b){a=!1}a&&(this.qF=new jEe(this,this.Jb))}if(!this.qF)throw Error("Ne");}for(this.qF.connect();0<this.wa.length;)this.wa.shift()()};yL.prototype.close=function(){bFe(this);this.Eb=3;x(this.qF);this.Aa=this.qF=null;x(this.oV);this.oV=null};
var uL=function(a,b){a.tq()||a.oV&&a.oV.Gb()||(a.Eb=2,x(a.oV),k(b)?(a.oV=new ck(a.Aa,b),a.oV.start()):(a.oV=null,a.Aa()))};yL.prototype.send=function(a,b){this.tq()&&(tEe(this)?(Ba(b)&&(b=Fd(b)),this.qF.send(eFe(this,a),b)):this.close())};
yL.prototype.ra=function(a,b,c){if(this.EO)this.wa.push(m(this.ra,this,a,b,c));else{var d=this.ha.ph;if((Ma(Na(c))||Ma(Na(d))||c==this.ha.ph)&&!this.isDisposed()&&3!=this.Eb)if(a&&"tp"!=a){if(this.tq()&&(a=a.replace(/%[0-9a-f]{2}/gi,decodeURIComponent),a=$Ee.test(a)?a.substring(1):a,a=this.getService(a,b))){var e;a:{if((c=a.Ryb)&&xa(b))try{e=Dd(b);break a}catch(g){e=null;break a}else if(!c&&!xa(b)){e=Fd(b);break a}e=b}null!=e&&a.callback(e)}}else this.qF.QFa(b)}};
var eFe=function(a,b){ZEe.test(b)&&(b="%"+b);return b.replace(/[%:|]/g,encodeURIComponent)},tL=function(a){var b=a.ha.role;return za(b)?b:window.parent==a.SF?1:0},iEe=function(a,b){delete rL[a.name];a.name=b;rL[b]=a};yL.prototype.Sa=function(){this.close();this.s$=this.SF=null;delete rL[this.name];x(this.Ga);delete this.Ga;yL.Ea.Sa.call(this)};var YEe=function(){for(var a in rL)x(rL[a])};

di(K.Ma(),"sy334");gi(K.Ma(),"sy334");
}catch(e){_DumpException(e)}
try{
fi(K.Ma(),"sy372");var CFe=function(a,b){return Ka(a,b?"/b/"+b:"")};
di(K.Ma(),"sy372");gi(K.Ma(),"sy372");
}catch(e){_DumpException(e)}
try{
fi(K.Ma(),"sy560");var X0f=function(a){return a.get("F4zhRb")};
di(K.Ma(),"sy560");gi(K.Ma(),"sy560");
}catch(e){_DumpException(e)}
try{
var Y0f=function(a){D(this,a,0,-1,null,null)};r(Y0f,C);Y0f.prototype.wj=function(){return E(this,1)};Y0f.prototype.zp=function(){return E(this,2)};Y0f.prototype.getEmail=function(){return E(this,4)};Y0f.prototype.dl=function(){return null!=E(this,4)};var Z0f=function(a){D(this,a,0,-1,null,null)};r(Z0f,C);Z0f.prototype.wj=function(){return E(this,1)};var $0f=[6,19,29,30,34,38,41],a1f=function(a,b){G(a,2,b)},b1f=function(a,b){G(a,1,b)},oV=function(a){D(this,a,0,-1,$0f,null)};r(oV,C);
oV.prototype.eEa=function(a){G(this,9,a)};oV.prototype.getSource=function(){return E(this,12)};oV.prototype.yz=function(a){G(this,17,a)};oV.prototype.XB=function(a){G(this,40,a)};
var c1f=function(a,b,c){if(""==c)throw Error("zj");for(var d=!0,e=0,g=a.length;e<g;e++)if(a.charAt(e)!=b.charAt(0)){d=!1;break}if(d)return c.charAt(0);e={};g=0;for(d=b.length;g<d;g++)e[b.charAt(g)]=g;d=[];for(g=a.length-1;0<=g;g--){var h=a.charAt(g),l=e[h];if("undefined"==typeof l)throw Error("Aj`"+a+"`"+b+"`"+h);d.push(l)}b=b.length;h=c.length;a=[];for(e=d.length-1;0<=e;e--){for(var n=l=0,g=a.length;n<g;n++){var p=a[n],p=p*b+l;if(p>=h)var w=p%h,l=(p-w)/h,p=w;else l=0;a[n]=p}for(;l;)w=l%h,a.push(w),
l=(l-w)/h;l=d[e];for(n=0;l;)n>=a.length&&a.push(0),p=a[n],p+=l,p>=h?(w=p%h,l=(p-w)/h,p=w):l=0,a[n]=p,n++}d=[];e=c.length;for(g=a.length-1;0<=g;g--){b=a[g];if(b>=e||0>b)throw Error("Bj`"+a+"`"+b);d.push(c.charAt(b))}return d.join("")},d1f=function(a){G(a,6,[]);G(a,11,void 0);null!=Fo(a)&&G(Fo(a),5,void 0);G(a,14,void 0);G(a,20,void 0);G(a,30,[])};fi(K.Ma(),"sy558");

di(K.Ma(),"sy558");gi(K.Ma(),"sy558");
}catch(e){_DumpException(e)}
try{
fi(K.Ma(),"sy567");
di(K.Ma(),"sy567");gi(K.Ma(),"sy567");
}catch(e){_DumpException(e)}
try{
fi(K.Ma(),"sy328");var ZDe=function(a){D(this,a,"n_gi",-1,null,null)};r(ZDe,C);H("n_gi",ZDe);
di(K.Ma(),"sy328");gi(K.Ma(),"sy328");
}catch(e){_DumpException(e)}
try{
fi(K.Ma(),"sy339");var hFe=function(a){D(this,a,"n_id",-1,null,null)};r(hFe,C);H("n_id",hFe);
di(K.Ma(),"sy339");gi(K.Ma(),"sy339");
}catch(e){_DumpException(e)}
try{
var H0f=function(){v.call(this)};r(H0f,v);fi(K.Ma(),"cc");





di(K.Ma(),"cc");gi(K.Ma(),"cc");
}catch(e){_DumpException(e)}
try{
var aX=function(a){return ah(a,Y0f,3)},Vag=function(a){D(this,a,0,-1,null,null)};r(Vag,C);var bX=function(a){return bh(a,Z0f,19)},cX=function(a){D(this,a,0,-1,null,null)};r(cX,C);cX.prototype.Il=function(a){G(this,1,a)};cX.prototype.getId=function(){return E(this,2)};cX.prototype.uf=function(a){G(this,2,a)};
var Wag=function(a){return null==a||Ma(Na(E(a,1)))||Ma(Na(a.getId()))?void 0:E(a,1)+"/"+a.getId()},Xag=function(a,b){Ia(b,"/")||(b="/"+b);var c=Vd(a);return Jea(c[1],c[2],c[3],c[4],b,c[6],c[7])},Yag=function(a,b){return Nea(a)+(b?"#"+b:"")},Zag=function(a){a=bX(a);return null!=a&&1==a.length&&null!=aX(a[0])&&null!=aX(a[0]).zp()},$ag=function(a){var b;b=null!=ah(a,cX,18)&&(aba(E(ah(a,cX,18),1),"conversation")||aba(E(ah(a,cX,18),1),"tee"))?Wag(ah(a,cX,18))||E(a,1)||"":E(a,1)||Wag(ah(a,cX,18))||"";switch(E(a,
2)){case 2:a="/hangouts/_/stream";break;case 7:a="/el";break;default:a="/hangouts/_"}return a+"/"+b},abg=function(a){for(var b=[],c=0;c<a.length;c++){var d=E(a[c],4);null!=d&&b.push(d)}return b},bbg=function(a){if(0<E(a,31)){a=bX(a);for(var b=[],c=0;c<a.length&&(null==aX(a[c])||null==E(aX(a[c]),3)||(b.push(E(aX(a[c]),3)),5!=b.length));c++);return b.join(",")}return null},dX=function(a,b,c){null!=c&&(!0===c?a=ny(a,b,"1"):!1!==c&&(va(c)?0<c.length&&(a=ny(a,b,c)):a=ny(a,b,c)));return a},cbg=function(a,
b){a=fh(a);null==E(a,1)&&G(a,1,"");null==E(a,2)&&G(a,2,0);if(b){var c=q()+bb(1E6*Math.random(),6,0);G(a,21,c)}return a},dbg=function(a,b,c,d,e){var g,h=!1;if(a instanceof oV){null!=c&&(a=cbg(a,!0),c.ra(a));var h=bX(a),h=null!=h&&1==h.length&&null!=aX(h[0])&&null!=aX(h[0]).zp(),l=new Vag;ch(a,16,l);var l=ah(a,Vag,16),n=q();G(l,1,n);l=0<E(a,31);n=1<bX(a).length;if(null!=c&&(l||n||c.ha())){c=a;b=Yag(b||"",null);null!=E(c,2)&&(b=dX(b,"ht",E(c,2)));b=dX(b,"hscid",E(c,21));b=Xag(b,$ag(c));l=!!E(c,20);a=
bX(c);var n=[],p=[];if(null!=a)for(var w=0;w<a.length;w++){var z=a[w];null!=aX(z)&&null!=E(aX(z),3)?p.push(E(aX(z),3)):n.push(z.wj())}0==n.length&&(n=E(c,6)||[]);if(l){if(0<n.length){l=[];for(p=0;p<n.length;p++)if(z=n[p],null!=z){w=z.substr(0,z.length-20);for(z=c1f(z.substring(z.length-20),"0123456789","0123456789abcdefghijklmnopqrstuvwxyz");13>z.length;)z="0"+z;l.push(w+z)}if(0<l.length)for(g=l[0],n=1;n<l.length;n++)g=g+"_"+l[n];null!=g&&(b=ny(b,"hpe",g))}a:{g=bX(c);if(0<E(c,31))for(l=0;l<g.length;l++){if(null!=
aX(g[l])&&null!=E(aX(g[l]),3)){g=E(g[l],2);break a}}else if(null!=g&&1==g.length){g=E(g[0],2);break a}g=null}null!=g&&(b=ny(b,"hpn",g));b=dX(b,"hisdn",abg(a));g=bbg(c);null!=g&&(b=ny(b,"hic",g));Zag(c)&&(b=dX(b,"hip",aX(bX(c)[0]).zp()));b=dX(b,"hnc",E(c,31))}null!=Fo(c)&&(b=dX(b,"hii",E(Fo(c),2)),b=dX(b,"hit",E(Fo(c),1)));null!=E(c,26)&&(b=dX(b,"hio",E(c,26)));null!=E(c,22)&&(b=dX(b,"hmv",E(c,22)));null!=E(c,43)&&(b=dX(b,"hma",E(c,43)));g=b=dX(b,"hs",c.getSource())}else{g=cbg(a);c=Yag(b||"",null);
null!=E(g,2)&&(c=dX(c,"ht",E(g,2)));c=dX(c,"had",E(g,9));c=dX(c,"hai",E(g,8));c=dX(c,"hft",$g(g,10,!1)||!1);c=dX(c,"hcb",$g(g,17,0));c=dX(c,"hci",E(g,5));c=dX(c,"hru",E(g,4));c=dX(c,"hti",E(g,7));c=dX(c,"htt",E(g,3));0<E(g,34).length&&(c=dX(c,"hrid",E(g,34).join(",")));c=dX(c,"hgai",E(g,33));0<E(g,38).length&&(c=dX(c,"hht",E(g,38).join(",")));null!=ah(g,Vag,16)&&null!=E(ah(g,Vag,16),1)&&(c=dX(c,"lm1",E(ah(g,Vag,16),1)));null!=Fo(g)&&(c=dX(c,"hii",E(Fo(g),2)),c=dX(c,"hin",E(Fo(g),4)),c=dX(c,"hit",
E(Fo(g),1)),c=dX(c,"htp",$g(Fo(g),3,0)));null!=E(g,26)&&(c=dX(c,"hio",E(g,26)));c=dX(c,"hs",g.getSource());c=dX(c,"hni",E(g,15));c=dX(c,"hscid",E(g,21));c=dX(c,"hsi",E(g,25));null!=E(g,22)&&(c=dX(c,"hmv",E(g,22)));null!=E(g,43)&&(c=dX(c,"hma",E(g,43)));c=dX(c,"heid",E(g,23));c=dX(c,"wpi",E(g,27));null!=$g(g,28,!1)&&(c=dX(c,"hib",$g(g,28,!1)));b=bbg(g);null!=b&&(c=dX(c,"hic",b));b=Fo(g);a=null!=b&&!!E(b,5);b=bX(g);if(!a)if(null!=b&&0<b.length){a=[];l=[];n=[];for(p=0;p<b.length;p++)null!=b[p].wj()&&
a.push(b[p].wj()),w=E(b[p],2),null!=w&&l.push(w),w=E(b[p],4),null!=w&&n.push(w);c=dX(c,"hpi",a);c=dX(c,"hpn",l);c=dX(c,"hisdn",abg(b))}else c=dX(c,"hpi",E(g,6));b=E(g,29);0<b.length&&(c=dX(c,"hso",b.join(",")));c=dX(c,"heeid",E(g,32));Zag(g)&&(c=dX(c,"hip",aX(bX(g)[0]).zp()));c=Xag(c,$ag(g));d1f(g);g=YCd(g.Lg(),!0);g=c=dX(c,"ssc",g)}}else null!=a.wG&&0<a.wG.length?(g=a.wG,null!=a.axc&&(c=Zd(g)||"",Ja(c,"/")||(c+="/"),Ia(c,"/")&&(c=IDd(c,"/")),k(a.Dsb)&&!Ma(Na(a.Dsb))&&(c+=Ta(a.Dsb)+"/"),c+=a.axc.replace(/(\?|%|#)/g,
encodeURIComponent),g=Xag(g,c)),null!=a.SU&&(g=ny(g,"authuser",a.SU)),null!=a.locale&&(g=ny(g,"hl",a.locale)),null!=a.groupId&&(g=ny(g,"groupid",a.groupId)),null!=a.zq&&(g=ny(g,"profileid",a.zq)),null!=a.YM&&!Ma(a.YM)&&(g=ny(g,"eid",a.YM)),null!=a.bJ&&(g=ny(g,"act",a.bJ)),null!=a.X5c&&(g=ny(g,"scw",a.X5c)),null!=a.source&&(g=ny(g,"source",a.source)),null!=a.gad&&(g=Yag(g,"_"+a.gad))):g=null,null!=g&&(g=ny(g,"lm1",q()));return null!=g?(c=Math.min(.9*window.screen.availWidth,h?1024:1490),e={target:e?
"_top":"_blank",directories:!1,location:!1,menubar:!1,status:!1,toolbar:!1,personalbar:!1,resizable:!0,width:c,height:Math.min(.9*window.screen.availHeight,h?768:1E3)},k(window.screen.availTop)&&(e.top=window.screen.availTop),k(window.screen.availLeft)&&(e.left=window.screen.availLeft+(window.screen.availWidth-c)/2),h=ee(window.location.href,"jsmode"),null!=h&&(g=ny(g,"jsmode",h),e.location=!0),d&&(e.noreferrer=!0),bd&&(d=Vd(g),g=Jea(d[1],d[2],"ie.talkgadget.google.com",d[4],d[5],d[6],d[7])),zl(g, e)):null};fi(K.Ma(),"sy566");
var ebg=function(a){D(this,a,"ci:dc",-1,null,null)};r(ebg,C);H("ci:dc",ebg);var fbg=function(a){D(this,a,"ci:ec",-1,null,null)};r(fbg,C);H("ci:ec",fbg);var gbg=function(a){D(this,a,"h_cp",-1,null,null)};r(gbg,C);H("h_cp",gbg);gbg.prototype.Xz=function(){return E(this,1)};var hbg=function(a){D(this,a,"h_hn",-1,null,null)};r(hbg,C);H("h_hn",hbg);hbg.prototype.wa=function(){return E(this,1)};var ibg=function(a){D(this,a,"h_hs",-1,null,null)};r(ibg,C);H("h_hs",ibg);ibg.prototype.wa=function(){return E(this,1)};var kbg=function(a){D(this,a,"h_jm",-1,jbg,null)};r(kbg,C);var jbg=[2];H("h_jm",kbg);var eX=function(a){D(this,a,"rbc_d",-1,null,null)};r(eX,C);H("rbc_d",eX);eX.prototype.getTitle=function(){return E(this,1)};eX.prototype.setTitle=function(a){G(this,1,a)};eX.prototype.Jm=function(){return null!=E(this,1)};eX.prototype.Re=function(){return E(this,2)};
var lbg=function(a){D(this,a,"h_oc",-1,null,null)};r(lbg,C);H("h_oc",lbg);lbg.prototype.Lh=function(){return E(this,1)};lbg.prototype.gF=function(){return ah(this,eX,2)};var mbg=function(a){D(this,a,"h_ogc",-1,null,null)};r(mbg,C);H("h_ogc",mbg);mbg.prototype.Ql=function(){return E(this,1)};mbg.prototype.Ou=function(a){G(this,1,a)};var nbg=function(a){D(this,a,"h_sc",-1,null,null)};r(nbg,C);H("h_sc",nbg);nbg.prototype.ze=function(){return E(this,1)};nbg.prototype.hasFocus=function(){return null!=E(this,3)};nbg.prototype.gF=function(){return ah(this,eX,6)};var pbg=function(a){D(this,a,"h_ssc",-1,obg,null)};r(pbg,C);var obg=[5];H("h_ssc",pbg);pbg.prototype.ze=function(){return E(this,1)};pbg.prototype.hasFocus=function(){return null!=E(this,3)};pbg.prototype.jf=function(){return E(this,4)};var qbg=function(a){D(this,a,"h_usa",-1,null,null)};r(qbg,C);H("h_usa",qbg);qbg.prototype.getType=function(){return E(this,1)};var rbg=function(a){D(this,a,"h_hs",-1,null,null)};r(rbg,C);H("h_hs",rbg);var sbg=function(a,b,c){this.Ui=b;this.ha=c;TA.call(this,a,35,4)};r(sbg,TA);sbg.prototype.Sc=function(a){sbg.Ea.Sc.call(this,a);Rx(a,!0);ul(a,"em",this.Ui);ul(a,"ivit",this.ha)};sbg.prototype.Dl=function(){return"Sending invitation"};var tbg=function(a){v.call(this);this.Oa=a};r(tbg,v);tbg.prototype.ha=function(a,b){var c=a.Nc(Gg);c&&c.dispatchEvent(new yB(c,"Sa",1,b?[b]:[]))};tbg.prototype.ra=function(a,b,c){b=new sbg(a,b,1);var d=dC(a);b.Eg(new ubg(a,c));oB(d,b);b.send()};var ubg=function(a,b){this.Oa=a;this.tf=b};ubg.prototype.ik=function(a){var b=GA(a.La()).Di();Fka(b,"_GM_invitesDone")(a.Da,null,1,0);this.tf&&this.tf(!!a.Oj)};
var vbg=function(a,b){B.call(this);this.Jb=Ie(b);this.wa=b||this.Jb.Ab().body;this.ra=this.Jb.createElement("IFRAME");this.ra.style.position="absolute";this.ra.style.zIndex=-1;this.ra.style.top="1px";this.ra.style.left="1px";this.ra.style.width="1px";this.ra.style.height="1px";this.ra.style.visibility="hidden";this.ra.src=a},wbg;r(vbg,B);vbg.prototype.execute=function(){this.Jb.Wj(this.wa,this.ra);Ig(this,this.Jb.getWindow(),"message",this.Aa,!1,this)}; vbg.prototype.Aa=function(a){try{a.Gf.source==qf(this.ra)&&this.dispose()}catch(b){}};vbg.prototype.Sa=function(){this.Jb.removeNode(this.ra);delete this.wa;delete this.ra;delete this.Jb;vbg.Ea.Sa.call(this)};
var xbg=function(a,b){v.call(this);var c=tA(a);this.Oa=a;this.wa=c.getData("pi:hu");this.ha=YB(a);this.Ke=nB(a);this.Fa=(c=$f())?parseInt(c,10):0;this.Da=b;c=hl(a).Pc();this.Ia=c.Gb(5750);this.Ga=c.Gb(5793)};r(xbg,v);var ybg=function(a,b){var c=new xbg(a,b);a.registerService("F4zhRb",c)};xbg.prototype.ra=function(a,b,c){zbg(this,a,b,c)};
var zbg=function(a,b,c,d){var e,g=new oV;G(g,1,"");G(g,2,0);if(c){var h=[],l;va(c)?t(c,function(a){a.wj()&&a.Xn(1)&&(l=new Z0f,b1f(l,a.wj()),a1f(l,a.getName()),h.push(l))}):c.wj()&&(l=new Z0f,b1f(l,c.wj()),a1f(l,c.getName()),h.push(l));dh(g,19,h);0<h.length&&a.Ga&&(G(g,20,!0),e=a.Da.ha())}G(g,12,b);dbg(g,Abg(a),e);d?a.ha.wb(d):c?a.ha.wb(KIa):a.ha.wb(LIa)};xbg.prototype.Ha=function(){this.ha.wb(NIa)};
xbg.prototype.Aa=function(a,b,c){var d;this.Ga&&Fo(b)&&(d=Fo(b),G(d,5,!0),d=this.Da.ha());G(b,12,a);dbg(b,Abg(this),d);this.ha.wb(c||HIa)};xbg.prototype.Ca=function(){if(this.Ia){var a;a=this.wa;a=Xag(a,"/hangouts/_/pre");null!=ee(a,"authuser")||(a=ny(a,"authuser","0"));if(wbg!=a&&(u&&kd("8")||ed&&kd("530.17")||dd&&kd("1.9.2"))){var b;b=new vbg(a,void 0);b.execute();wbg=a;a=b}else a=null;this.Ya(a)}}; var Abg=function(a){var b=a.wa,c=a.Fa,b=-1==b.indexOf("/")?"https://"+b:b;null!=c&&(b=ny(b,"authuser",c));b=ny(b,"hl","en");Ma(Na(void 0))||(b=ny(b,"eid",void 0));c=new ie(b);qe(c,"pqs",pB(a.Ke,"bx_vesp")?"1":0);return c.toString()};
var Cbg=function(a,b,c){var d=new ie(window.location.href),e=null!=b?b:se(d,"pvt")||"";b=new ie;je(b,"https"==d.ra?"https":"http");rfa(b,d.Aa);ke(b,d.Ga);var g=null!=a?new ie(a):d;a=g.ha;d=se(g,"authuser");g=se(g,"eid");b.Il(a);le(b,"/hangouts/_/hscv");qe(b,"pvt",e);null!=d&&qe(b,"authuser",d);null!=g&&qe(b,"eid",g);e={};e.pu=b.toString();c=c||Bbg();b=new yL(e,c);dFe(b,c.Ab().body,function(a){a&&(a.style.visibility="hidden",a.style.top="0",a.style.left="0",a.style.width="1px",a.style.height="1px", a.style.position="fixed",a.style.zIndex="-1")});c=Od();b.connect(m(c.resolve,c,b));return c.Sj},Bbg=function(){try{var a=window.parent["gth-talk-plugin-frame-id"];if(null!=a)return new Ge(a.document)}catch(b){}return new Ge(document)};
var Dbg=function(a,b){v.call(this);var c;a instanceof yL?c=Ld(a):c=Cbg(a,b).then(function(a){this.Ya(a);return a},null,this);this.wa=c};r(Dbg,v);Dbg.prototype.ra=function(a,b){this.wa.then(function(c){c.send("waitForRequest",{context:a.Lg(),timeoutMs:b})})};Dbg.prototype.ha=Qb;
var Ebg=function(a){var b=tA(a);a=new ie(b.getData("pi:hu"));var c=$f();xa(c)&&qe(a,"authuser",c);je(a,GFd().ra);b=b.getData("ui:ovt");this.ra=new Dbg(a.toString(),b);this.Ya(this.ra)};r(Ebg,v);Ebg.prototype.ha=function(){return this.ra};var Fbg=function(a){D(this,a,"h_bm",-1,null,null)};r(Fbg,C);H("h_bm",Fbg);var Gbg=function(a){D(this,a,"h_br",-1,null,null)};r(Gbg,C);H("h_br",Gbg);var Hbg=function(a){D(this,a,"cmn",-1,null,null)};r(Hbg,C);H("cmn",Hbg);var Jbg=function(a){D(this,a,"h_cd",-1,Ibg,null)};r(Jbg,C);var Ibg=[1,4,5];H("h_cd",Jbg);Jbg.prototype.M1=function(){return E(this,1)};Jbg.prototype.gF=function(){return ah(this,eX,3)};var Kbg=function(a){D(this,a,"h_opc",-1,null,null)};r(Kbg,C);H("h_opc",Kbg);var Lbg=function(a){D(this,a,"h_po",-1,null,null)};r(Lbg,C);H("h_po",Lbg);Lbg.prototype.zp=function(){return E(this,1)};var Mbg=function(a){D(this,a,"h_cc",-1,null,null)};r(Mbg,C);H("h_cc",Mbg);Mbg.prototype.setProperty=function(a){G(this,2,a)};Mbg.prototype.Ps=function(a){G(this,4,a)};Mbg.prototype.aE=function(a){G(this,8,a)};var Nbg=function(a){D(this,a,"h_ccf",-1,null,null)};r(Nbg,C);H("h_ccf",Nbg);var Obg=function(a){D(this,a,"h_cs",-1,null,null)};r(Obg,C);H("h_cs",Obg);Obg.prototype.getState=function(){return E(this,1)};Obg.prototype.le=function(a){G(this,1,a)};var Pbg=function(a){D(this,a,"h_cu",-1,null,null)};r(Pbg,C);H("h_cu",Pbg);f=Pbg.prototype;f.ze=function(){return E(this,1)};f.wj=function(){return E(this,2)};f.getStatus=function(){return E(this,3)};f.getName=function(){return E(this,4)};f.Bf=function(a){G(this,4,a)};f.xi=function(){return null!=E(this,4)};
var Qbg=function(a){D(this,a,"h_fm",-1,null,null)};r(Qbg,C);H("h_fm",Qbg);Qbg.prototype.setPosition=function(a){G(this,3,a)};var Rbg=function(a){D(this,a,"h_gst",-1,null,null)};r(Rbg,C);H("h_gst",Rbg);var Sbg=function(a){D(this,a,"h_hph",-1,null,null)};r(Sbg,C);H("h_hph",Sbg);var Tbg=function(a){D(this,a,"h_icr",-1,null,null)};r(Tbg,C);H("h_icr",Tbg);Tbg.prototype.getId=function(){return E(this,1)};Tbg.prototype.uf=function(a){G(this,1,a)};var Ubg=function(a){D(this,a,"h_mmqm",-1,null,null)};r(Ubg,C);H("h_mmqm",Ubg);Ubg.prototype.Ad=function(){return E(this,3)};Ubg.prototype.Kh=function(a){G(this,3,a)};Ubg.prototype.Jd=function(){return E(this,4)};var Vbg=function(a){D(this,a,"h_maa",-1,null,null)};r(Vbg,C);H("h_maa",Vbg);Vbg.prototype.getId=function(){return E(this,1)};Vbg.prototype.uf=function(a){G(this,1,a)};var Wbg=function(a){D(this,a,"h_mac",-1,null,null)};r(Wbg,C);H("h_mac",Wbg);f=Wbg.prototype;f.getId=function(){return E(this,1)};f.uf=function(a){G(this,1,a)};f.getUrl=function(){return E(this,2)};f.Ad=function(){return E(this,3)};f.Kh=function(a){G(this,3,a)};f.Jd=function(){return E(this,4)};
var Xbg=function(a){D(this,a,"h_maps",-1,null,null)};r(Xbg,C);H("h_maps",Xbg);f=Xbg.prototype;f.getId=function(){return E(this,1)};f.uf=function(a){G(this,1,a)};f.getUrl=function(){return E(this,2)};f.Ad=function(){return E(this,3)};f.Kh=function(a){G(this,3,a)};f.Jd=function(){return E(this,4)};
var Ybg=function(a){D(this,a,"h_mad",-1,null,null)};r(Ybg,C);H("h_mad",Ybg);Ybg.prototype.getId=function(){return E(this,1)};Ybg.prototype.uf=function(a){G(this,1,a)};var Zbg=function(a){D(this,a,"h_mafn",-1,null,null)};r(Zbg,C);H("h_mafn",Zbg);Zbg.prototype.getId=function(){return E(this,1)};Zbg.prototype.uf=function(a){G(this,1,a)};Zbg.prototype.setPosition=function(a){G(this,3,a)};var $bg=function(a){D(this,a,"h_mamx",-1,null,null)};r($bg,C);H("h_mamx",$bg);$bg.prototype.getId=function(){return E(this,1)};$bg.prototype.uf=function(a){G(this,1,a)};var acg=function(a){D(this,a,"h_mami",-1,null,null)};r(acg,C);H("h_mami",acg);acg.prototype.getId=function(){return E(this,1)};acg.prototype.uf=function(a){G(this,1,a)};var bcg=function(a){D(this,a,"h_map",-1,null,null)};r(bcg,C);H("h_map",bcg);bcg.prototype.getId=function(){return E(this,1)};bcg.prototype.uf=function(a){G(this,1,a)};var ccg=function(a){D(this,a,"h_mars",-1,null,null)};r(ccg,C);H("h_mars",ccg);f=ccg.prototype;f.getId=function(){return E(this,1)};f.uf=function(a){G(this,1,a)};f.Ad=function(){return E(this,3)};f.Kh=function(a){G(this,3,a)};f.Jd=function(){return E(this,4)};
var dcg=function(a){D(this,a,"h_mam",-1,null,null)};r(dcg,C);H("h_mam",dcg);dcg.prototype.getId=function(){return E(this,1)};dcg.prototype.uf=function(a){G(this,1,a)};var ecg=function(a){D(this,a,"h_mas",-1,null,null)};r(ecg,C);H("h_mas",ecg);var fcg=function(a){D(this,a,"h_rha",-1,null,null)};r(fcg,C);H("h_rha",fcg);var gcg=function(a){D(this,a,"h_rtp",-1,null,null)};r(gcg,C);H("h_rtp",gcg);var hcg=function(a){D(this,a,"h_sph",-1,null,null)};r(hcg,C);H("h_sph",hcg);hcg.prototype.Lh=function(){return E(this,1)};hcg.prototype.getEmail=function(){return E(this,2)};hcg.prototype.dl=function(){return null!=E(this,2)};var icg=function(a){D(this,a,"h_ssf",-1,null,null)};r(icg,C);H("h_ssf",icg);var kcg=function(a){D(this,a,"h_sm",-1,jcg,null)};r(kcg,C);var jcg=[1,3];H("h_sm",kcg);kcg.prototype.gF=function(){return ah(this,eX,2)};var mcg=function(a){D(this,a,"h_stc",-1,lcg,null)};r(mcg,C);var lcg=[1,2];H("h_stc",mcg);var ocg=function(a){D(this,a,"h_ufc",-1,ncg,null)};r(ocg,C);var ncg=[1,2];H("h_ufc",ocg);var pcg=function(a){D(this,a,"h_usi",-1,null,null)};r(pcg,C);H("h_usi",pcg);var qcg=function(a){D(this,a,"h_usc",-1,null,null)};r(qcg,C);H("h_usc",qcg);qcg.prototype.getState=function(){return E(this,1)};qcg.prototype.le=function(a){G(this,1,a)};var fX=function(a){v.call(this);this.ra=a.get("ITu2td");this.Ca=uG(a)};r(fX,v);fX.prototype.Da=function(a){if(Ma(Na(a)))return null;a=this.ra.U8(a);return a.zY()||0==a.yY()?null:a.j4().Gm};fX.prototype.Ha=function(a,b){var c=this.ra.U8(b);this.Ca.DS(a,c)};fX.prototype.Fa=function(a,b,c,d){this.ra.ra(a,b,c,[d])};

di(K.Ma(),"sy566");gi(K.Ma(),"sy566");
}catch(e){_DumpException(e)}
try{
var Vug=function(a,b){var c=a.wa.Vc.Ad()-8-5-a.Ja()-1;t(a.ha,function(a){var d=this.ra.get(a);d.visible&&!d.Ru&&a!=b&&(c-=d.Fe.Ad())},a);var d=a.wa.Vc.Jd()-a.fK();return new Be(c,d)},Wug={gYb:"mc",p3b:"tl",qXb:"l",o3b:"t"},Xug=function(a){return L('<div class="aJn"><div id="'+O(a.id.gYb)+'"></div><div id="'+O(a.id.o3b)+'" class="aQV aJo"></div><div id="'+O(a.id.qXb)+'" class="aQV aJm"></div><div id="'+O(a.id.p3b)+'" class="aQV aQX"></div></div>')},Yug=function(a){D(this,a,0,-1,null,null)};r(Yug,C);
var Zug=function(a){D(this,a,0,-1,null,null)};r(Zug,C);var $ug=function(a){D(this,a,0,-1,null,null)};r($ug,C);var avg=function(a){D(this,a,0,-1,null,null)};r(avg,C);
var bvg=function(a,b,c,d,e,g){Pi.call(this,a);this.ra=b;this.Ra=c.clone();this.Ca=d.clone();this.ha=d.clone();this.Aa=d.clone();this.Fa=e;this.Za=g;this.Ha=new B(this);this.Ya(this.Ha);this.Oe(e);this.getHandler().listen(this.ra.kc(),"G",this.IAb);this.getHandler().listen(this.ra.kc(),"H",this.IAb);this.getHandler().listen(this.ra.kc(),"I",this.QLc)};r(bvg,bj);f=bvg.prototype;f.Te=function(){bvg.Ea.Te.call(this);var a={id:this.Ce(Wug)};oi(this.yb,Xug,a);P(this.yb,"aJl")};
f.Uv=function(a){bvg.Ea.Uv.call(this,a);this.Fa.Uv(a)};f.Ua=function(){this.Ba("mc").appendChild(this.Fa.Ba());for(var a=this.Ba("l"),b=this.Ba("t"),c=this.Ba("tl"),a=[a,b,c],b=0;c=a[b];b++)this.getHandler().listen(c,"mousedown",this.$ic);bvg.Ea.Ua.call(this)};f.Vl=function(a,b,c){bvg.Ea.Vl.call(this,a,b,c);"x"==a?this.Fa.Tr(a,b,!0):this.Fa.Tr(a,-1,!1)};
f.$ic=function(a){!this.Da&&td(a,0)&&(P(a.target,"aJk"),this.Da=a.target,this.Va=new Ae(a.clientX,a.clientY),this.Ca=this.ha.clone(),this.Ta=Vug(this.Za,this.ra.Ok()),this.Ja=this.Ia=!1,a.target==this.Ba("l")&&(this.Ia=!0),a.target==this.Ba("t")&&(this.Ja=!0),a.target==this.Ba("tl")&&(this.Ja=this.Ia=!0),this.Ha.listen(He(a.target),"mouseup",this.bjc,!0),this.Ha.listen(a.target,"mousemove",this.ajc),a.preventDefault(),a.stopPropagation())};f.bjc=function(){Wi(this.Da,"aJk");this.Da=null;this.Ha.removeAll()};
f.ajc=function(a){if(this.Va&&this.Da){a=Wfa(this.Va,new Ae(a.clientX,a.clientY));var b=this.Ja?a.y:0;this.ha.width=Ub(this.Ca.width+(this.Ia?a.x:0),this.Ra.width,this.Ta.width);this.ha.height=Ub(this.Ca.height+b,this.Ra.height,this.Ta.height);this.ra.resize(this.ha.width,this.ha.height);this.Aa.width=this.ha.width;this.Aa.height=this.ha.height}};
f.resize=function(a){this.ha.width=a.width;this.ha.height=a.height;this.Ca.width=this.ha.width;this.Ca.height=this.ha.height;this.Aa.width=this.ha.width;this.Aa.height=this.ha.height;this.ra.resize(this.ha.width,this.ha.height)};f.IAb=function(){Yi(this.Ba(),"aQW",this.ra.Mo())};f.QLc=function(){this.ha.width=Math.min(this.ha.width,this.Ca.width);this.ha.height=Math.min(this.ha.height,this.Ca.height);this.Aa.width=this.ha.width;this.Aa.height=this.ha.height;this.ra.resize(this.ha.width,this.ha.height)};
var cvg=[2],dvg=[2],evg=function(a,b){A.call(this);this.ha=b;this.ra=a.Nc(Jzd);this.wa=!0;this.Pa=new B(this);this.Ya(this.Pa);this.Pa.listen(this.ha.kc(),"h_rto",this.u6b);this.Pa.listen(this.ha.kc(),"h_trd",this.NPc);this.ra&&this.Pa.listen(this.ra,"Fa",this.t6b)};r(evg,A);f=evg.prototype;f.u6b=function(){this.dispatchEvent("Ha")};f.NPc=function(){this.dispatchEvent("Ia")};f.t6b=function(){"r"==this.ra.Eb&&fvg(this,this.wa)};f.Ljc=function(){var a=new nzd;this.ha.sendMessage(a)};
f.v6b=function(){var a=new qzd;this.ha.sendMessage(a)};f.UQc=function(){var a=new rzd;this.ha.sendMessage(a)};f.KQc=function(){var a=new ozd;this.ha.sendMessage(a)};f.TQc=function(){var a=new pzd;this.ha.sendMessage(a)};var fvg=function(a,b){var c=(a.wa=b)?new eyd:new jyd;SX(a.ha,c)},gvg=function(a){y.call(this,"Ga");this.ha=a};r(gvg,y);var TX=function(a){D(this,a,0,-1,cvg,null)};r(TX,C);var hvg=function(a,b){G(a,2,b||[])};TX.prototype.Fk=function(a,b){Ey(this,2,a,b)};
var ivg=function(a){D(this,a,0,-1,dvg,null)};r(ivg,C);ivg.prototype.Fk=function(a,b){Ey(this,2,a,b)};var jvg=function(a){D(this,a,0,-1,null,null)};r(jvg,C);jvg.prototype.getType=function(){return E(this,1)};jvg.prototype.getKey=function(){return E(this,2)};var kvg=function(a){D(this,a,0,-1,null,null)};r(kvg,C);
var lvg=function(a,b){rj(a,Mzd,function(){return new evg(a,b)})},mvg=function(a){A.call(this);a=a.get(vx);var b=new B(this);b.Ya(b);this.Eb="u";b.listen(a.kc(),"capi:clstup",this.ha);b.listen(a.kc(),"h_fr",this.wa);b.listen(a.kc(),"h_ec",this.ra)};r(mvg,A);mvg.prototype.ha=function(a){var b="r";1==E(new $yd(a.Af),1)&&(b="u");nvg(this,b)};var nvg=function(a,b){var c=b!=a.Eb;a.Eb=b;c&&a.dispatchEvent("Fa")};mvg.prototype.wa=function(){nvg(this,"u")};
mvg.prototype.ra=function(a){a=new kyd(a.Af);a=new gvg(!!E(a,1));this.dispatchEvent(a)};var UX={a9a:1,JGa:2,gC:3,d9a:4,Bab:5,A7a:6,t7a:7,upa:8,c$a:9},ovg=function(a){D(this,a,0,-1,null,null)};r(ovg,C);f=ovg.prototype;f.getId=function(){return E(this,1)};f.uf=function(a){G(this,1,a)};f.setPosition=function(a){G(this,2,a)};f.getContent=function(){return E(this,3)};f.setContent=function(a){G(this,3,a)};f.getSource=function(){return E(this,10)};
var pvg={UTb:0,wXb:1,UJd:2,ujd:4,hgd:5,WJd:6,Ngd:7,VJd:8},qvg=function(a){D(this,a,0,-1,null,null)};r(qvg,C);f=qvg.prototype;f.getId=function(){return E(this,1)};f.uf=function(a){G(this,1,a)};f.setPosition=function(a){G(this,2,a)};f.getContent=function(){return E(this,3)};f.setContent=function(a){G(this,3,a)};f.getSource=function(){return E(this,10)};fi(K.Ma(),"sm");
var rvg=function(){if(Ne("talk_loading_msg")){var a=Ne("talk_loading_msg_error");a&&$e(a)}},svg=function(a){var b=Ne("talk_loading_msg");if(b){rvg();var c=Ue("DIV");Oe(c,{"class":"talk_loading_msg_error",style:"margin: 12px 8px; font-size: 10px"});var d=Ue("DIV");rf(d,"Errors: "+a.join(", "));c.appendChild(d);b.appendChild(c)}};
var tvg=function(){};r(tvg,il);tvg.prototype.ha=function(a){return a};nl(tvg.prototype.ha);tvg.prototype.ra=function(){return!0};nl(tvg.prototype.ra);var uvg=function(a,b){var c=new jvg;G(c,1,b);G(c,2,a);return c},vvg=uvg("?",0),wvg=uvg("q",1),xvg=uvg("<",2),yvg=uvg(">",3),zvg=uvg("~",4),Avg=uvg("s",5),Bvg={LP:vvg,Ia:wvg,Da:xvg,Fa:yvg,wa:zvg,Ja:Avg};var Cvg=function(a,b,c){pl(this);var d=this.Wa.ha(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(Ia(d,"https://talkgadget.google.com/talkgadget/")){var e=(new ija(window.document)).get("WCSDBG",""),e=e.split(";")[0],e=e.split("|")[0],g=["plus.google.com"],h=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<e.length&&!sb(g,e)&&h.test(e)&&(d=ve(d),d=ve("https://"+e+d.getPath()).toString())}this.fV=d;this.wa=c||new fbg;a.notificationsOnly&&G(this.wa,1,!0);this.SU="0";null!=a.authUser?
this.SU=a.authUser:(c=se(new ie(window.location.href),"authuser"),null!=c&&(this.SU=c));this.Ga=a.clientUrl||"notifierclient";c=se(ve(this.Ga),"authuser");null!=c&&(this.SU=c);this.Va=a.propertyName||"Google Talk";this.Da=a.cssUrl;this.locale=a.locale;this.debug=a.debug;this.Bo=a.helpLink;this.qg=a.hostCallback;this.Xc=a.userJid;this.Soa=a.uiVersion;this.Sd=null!=a.rosterExpanded?a.rosterExpanded:!0;this.Hi=a.xpcRelay;this.Uh=a.xpcBlank;this.Tg=a.hostLogHandler;this.Ob=a.hostLogMinValue;this.Xa=a.hideChat;
this.qe=a.refresh;this.Qa=a.hideProfileCard;this.Gc=a.hideStatusMsgs;this.Ta=a.hideRosterOptions;this.Ra=a.hideRecentConversations;this.Ja=a.hideOTR;this.Ie=a.hostServerMessageCallback||!1;this.Fa=a.isCentralRoster;this.Ne=a.isFullFrame||!1;this.ef=a.rosterClass||"talk_roster";this.yc=a.rosterId||"talk_roster";this.ha="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.ha=a.rosterFrameId);this.nh=this.ha+"-b";a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/)&&(this.Gh=
a.rosterIframeIdB);this.Ca=a.parentToken;this.kd=b||!1;this.Pg=k(a.isRtl)?a.isRtl:Wba.test(this.locale);this.position=a.position||"l";if(!(b=a.keyboardShortcuts)){b=[];for(var l in Bvg)b.push(Bvg[l].Pf())}this.Qf=b;this.YM=a.entityId;this.Ia=a.useQuasarPanels||!1;this.Fc=a.silent||!1;this.He=a.ignoreCentralRoster||!1;this.Aa=a.lazy||!1;this.Of=!0;this.Md=a.handleProfileLinks||!1;this.Rb=a.hostSettings;this.Za=a.screen;this.Ha=a.docsConfig;this.Qb=a.jsmode;this.lm=a.moleWidth;this.Yb=a.moleHeight;
this.Wb=a.minimizedMoleHeight||36;this.Og=a.derp;this.zt=window.location.protocol+"//"+window.location.host;this.eh=a.ignoreAutomatedRoster;this.nb="";this.Db=a.optOutAllowed;this.Cb=a.legacyTalkSignedIn;this.Kc=a.useSpareMole;this.ra=a.conversationId};jl(tvg,Cvg);
var Dvg=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 36:return"StartPage"}};
var Evg=function(a,b,c,d,e){this.Aa=a;this.Ga=b;this.ha=this.ra=a;this.Ca=c||0;this.Da=d||2;this.Ha=e||2};Evg.prototype.wa=0;Evg.prototype.Fa=0;Evg.prototype.reset=function(){this.ha=this.ra=this.Aa;this.Fa=this.wa=0};Evg.prototype.qb=function(){return this.ra};var Fvg=function(a){a.ha=Math.min(a.Ga,a.ha*a.Da);a.ra=Math.min(a.Ga,a.ha+(a.Ca?Math.round(a.Ca*(Math.random()-.5)*2*a.ha):0));a.wa++};
var Gvg=function(a){this.ha=a;u||(delete this.ha.lpu,delete this.ha.ppu)},Hvg=["cn","tp"],Ivg=function(a,b){var c;c=Aa(document.postMessage)||Aa(window.postMessage)||u&&window.postMessage?1:dd?2:u&&XEe()?6:4;var d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new Gvg(d)};Gvg.prototype.Kb=function(){return this.ha};pa("GTalk_IFrameChannelConfig.build",Ivg,void 0);
var Jvg=function(a,b,c,d,e){v.call(this);this.ha=a;this.ra=d||window.document;this.wa=new B(this);this.Ya(this.wa);var g=tc;d=new ie(a.fV+a.Ga);$g(a.wa,2,!1)||(qe(d,"ts","0"),qe(d,"re",a.Sd),qe(d,"ref",a.qe));qe(d,"client","sm");qe(d,"prop",a.Va);qe(d,"nav","true");qe(d,"fid",a.ha);a.debug&&qe(d,"debug",a.debug);qe(d,"os",Oca);qe(d,"stime",c);a.Xa&&qe(d,"hc",a.Xa);for(c=0;c<Hvg.length;++c);b=Fd(b.ha);qe(d,"xpc",b);qe(d,"ec",Fd(a.wa.Pf()));a.Za&&qe(d,"screen",a.Za);-1!=g.indexOf("MSIE")&&qe(d,"ua",
g);a.Ca&&qe(d,"pvt",a.Ca);a.Ie&&qe(d,"hsmc","true");k(a.Ob)&&qe(d,"logl",a.Ob);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),qe(d,"href",b.join("?")));b=new ie(window.location.href);"false"==se(b,"uacheck")&&qe(d,"uacheck",!1);(g=a.Qb)&&qe(d,"jsmode",g);(g=se(b,"cssmode"))&&qe(d,"cssmode",g);(g=se(b,"convid"))&&qe(d,"convid",g);(g=MBd(b,"convp"))&&re(d,"convp",g);(g=se(b,"smexp"))&&qe(d,"smexp",g);g=MBd(b,"mods");a.Aa&&g.push("lazy");
e&&(g=Cb(g,e));0<g.length&&qe(d,"mods",g.join(","));if(!a.fV||0>a.fV.indexOf("/u/"))(e=se(b,"authuser"))?qe(d,"authuser",e):null!=a.SU&&qe(d,"authuser",a.SU);e=se(b,"eid");Ma(Na(e))||qe(d,"eid",e);Ma(Na(this.ha.YM))||qe(d,"eid",this.ha.YM);null!=this.ha.position&&qe(d,"pos",this.ha.position);k(a.Soa)&&qe(d,"uiv",this.ha.Soa);a.Da&&qe(d,"css",a.Da);e=a.locale||se(b,"hl");null!=e&&qe(d,"hl",e);k(a.Xc)&&qe(d,"uj",a.Xc);null!=a.Qa&&qe(d,"hpc",a.Qa);null!=a.Gc&&qe(d,"hsm",a.Gc);null!=a.Ta&&qe(d,"hro",
a.Ta);null!=a.Ra&&qe(d,"hrc",a.Ra);null!=a.Ja&&qe(d,"hotr",a.Ja);null!=a.Fa&&qe(d,"pop",a.Fa);a.kd&&qe(d,"pal","1");null!=a.Ia&&qe(d,"uqp",a.Ia);null!=a.Db&&qe(d,"gooa",a.Db);null!=a.Cb&&qe(d,"gltsi",a.Cb);null!=a.Kc&&qe(d,"gusm",a.Kc);null!=a.Fc&&qe(d,"sl",a.Fc);a.He&&qe(d,"icr","1");a.Md&&qe(d,"hpl","1");a.Rb&&qe(d,"hs",a.Rb);a.Ha&&qe(d,"dc",Fd(a.Ha.Pf()));null!=a.lm&&qe(d,"molew",a.lm);null!=a.Yb&&qe(d,"moleh",a.Yb);null!=a.Wb&&qe(d,"mmoleh",a.Wb);a.Og&&qe(d,"derp","1");a.nb&&qe(d,"fcho",a.nb);
null!=a.zt&&qe(d,"two",a.zt);null!=a.ra&&qe(d,"convid",a.ra);qe(d,"host","1");te(d);this.Ga=d.toString()};r(Jvg,v);Jvg.prototype.install=function(a,b){Kvg(this,a,b,sa)};
var Kvg=function(a,b,c,d){var e=a.ra.getElementById(b);e||(e=a.ra.createElement("div"),e.id=b,e.className=a.ha.ef,a.ra.body.appendChild(e));a=m(function(){var a="";this.ha.Of?this.ha.Ne||(a="height:400px"):a="width: 0; height: 0; overflow: hidden;";var b=this.ra.createElement("iframe");Oe(b,{id:this.ha.ha,name:this.ha.ha,"class":"talk_iframe",frameborder:"0",style:a,"aria-hidden":"true"});Ne("talk_loading_msg",e)||We(e);e.appendChild(b);var l=this.ra.getElementById(this.ha.ha);this.wa.ud(l,["load", "error"],function(a){l.contentWindow.postMessage("AllowFrame: Chat","*");d(a)});l.src=this.Ga.toString();c()},a);window.setTimeout(a,0)};
var Lvg=function(a){y.call(this,a[0]);this.Af=a};r(Lvg,y);var VX=function(a,b){v.call(this);this.startTime=q();this.Ra=a;this.document=b||window.document;this.config=new Cvg(a,!0,a.endpointConfig);this.Aa=[];this.Ia=new A;this.Ga=null};r(VX,v);VX.prototype.Sa=function(){VX.Ea.Sa.call(this);Ud(this.Ga);this.ha&&this.Fa&&this.ha.parentNode.removeEventListener("DOMAttrModified",this.Fa,!0)};VX.prototype.ra=function(a,b){if(!this.wa)this.Aa.push(arguments);else if(this.wa[a]){var c=Array.prototype.slice.call(arguments,1);this.wa[a].apply(this.wa,c)}};
VX.prototype.Ca=function(){var a=this.getWindow().GTalkNotifier;if(a){var b=lc(this.Ra);b.endpointConfig=this.config.wa.Pf();this.wa=new a(b,!0);for(a=0;a<this.Aa.length;a++)this.ra.apply(this,this.Aa[a]);this.Aa=[];a=m(this.onMessage,this);this.ra("_addClientMessageCallback",a);this.ra("_addHostBundleMessageCallback",a)}};VX.prototype.onMessage=function(a){switch(a[0]){case "h_ccf":this.Ta=E(new Nbg(a),1)}this.Ia.dispatchEvent(new Lvg(a))};var SX=function(a,b){a.ra("_h",b.Pf())};f=VX.prototype;
f.sendMessage=function(a){SX(this,a)};f.kc=function(){return this.Ia};f.getWindow=function(){return this.document.parentWindow||this.document.defaultView};f.Tvc=function(a,b){if(b.target==a&&("style"==b.attrName||"class"==b.attrName)){var c=new gcg;SX(this,c)}};f.Dxc=function(){var a=this.document.getElementById(this.config.yc);Ne("talk_loading_msg",a)&&(a=this.document.getElementById(this.config.ha),Fh(a,0,0),mh(a,"overflow","hidden"),I(a,!0))};
var Mvg=function(a){var b=a.config.fV+"host-js",b=ny(b,"prop",a.config.Va),c=a.config.Qb;c&&(b=ny(b,"jsmode",c));$g(a.config.wa,2,!1)&&(b=ny(b,"b","1"));var b=ny(b,"zx",db()),d=m(a.Ca,a),e=Te("SCRIPT",{type:"text/javascript",src:b}),g=!1;e.onload=e.onreadystatechange=function(){g||e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(g=!0,d())};e.onerror=m(a.Ja,a,e);a.Ga&&(Ud(a.Ga),a.Ga=null);a.Ga=Td(m(function(){this.jl()||this.Qa(e)},a),25E3);a.document.body.appendChild(e)}; VX.prototype.Ja=function(){};VX.prototype.Qa=function(){};VX.prototype.jl=function(){return null!=this.wa};
var WX=function(a,b,c){var d={},e=$g(a,1,"hangouts.google.com"),g="";0>e.indexOf("://")&&(g="https://",0<=e.indexOf(":")&&23!=E(a,2)&&27!=E(a,2)&&(g="http://"));Xa(e,"talkgadget.")?(d.clientBaseUrl=g+e+"/talkgadget/_/",d.clientUrl="chat"):(d.clientBaseUrl=g+e+"/webchat/u/"+$g(a,8,"0")+"/",d.clientUrl="load");d.authUser=$g(a,8,"0");d.propertyName=Dvg(E(a,2));d.locale=E(a,4);d.hideProfileCard=!0;d.parentToken=E(a,3);d.isRtl=$g(a,6,!1);d.lazy=$g(a,7,!1);d.entityId=E(a,9);d.hostSettings=E(a,5);d.jsmode=
E(a,11);d.isFullFrame=$g(a,13,!1);d.rosterId=$g(a,12,"talk_roster");d.rosterIframeIdB=$g(a,15,"gtn-roster-iframe-id-b");d.derp=!!$g(a,16,!1);e=ah(a,Yug,14);null!=e&&(d.isCentralRoster=$g(e,1,!1),d.useQuasarPanels=$g(e,2,!1));e=ah(a,avg,10);null!=e&&(d.moleManagerLeftMargin=E(e,1),d.moleManagerMiddleMargin=E(e,2),d.moleManagerRightMargin=E(e,3),d.moleManagerNoMoleAreaMargin=E(e,4),d.moleManagerBoundingElementId=E(e,5),d.moleWidth=E(e,6),d.moleHeight=E(e,7),d.minimizedMoleHeight=E(e,8));e=ah(a,$ug,
18);null!=e&&(d.optOutAllowed=$g(e,1,!0),g=ah(e,Zug,3),null!=g&&(d.legacyTalkSignedIn=$g(g,1,!0)),e=E(e,4),null!=e&&(d.useSpareMole=e));d.uiVersion=2;d.hideStatusMsgs=!0;d.hideRecentConversations=!0;e=new fbg;G(e,2,!0);G(e,1,!0);G(e,3,!1);d.endpointConfig=e;d.ignoreAutomatedRoster=$g(a,17,!1);d.conversationId=E(a,19);d.hostCallback=c;VX.call(this,d,b);this.Ha=new Evg(5E3,3E5);this.Yf=null};r(WX,VX);
var Nvg=function(a,b){var c=1+.5*Math.random();a.Yf=Td(function(){this.jl()||(mf(this.document.body,b)&&this.document.body.removeChild(b),Mvg(this))},a.Ha.qb()*c,a);Fvg(a.Ha)};WX.prototype.Qa=function(a){svg(["301"]);Nvg(this,a)};WX.prototype.Ja=function(a){var b=Ne("talk_loading_msg",this.document.body);b&&P(b,"talk_network_warning");svg(["302"]);Nvg(this,a)};WX.prototype.Ca=function(){WX.Ea.Ca.call(this);var a=Ne("talk_loading_msg",this.document.body);a&&Wi(a,"talk_network_warning");rvg()}; WX.prototype.Sa=function(){WX.Ea.Sa.call(this);Ud(this.Yf)};
var Ovg=function(a){A.call(this);this.ha=a;this.Pa=new B(this);this.Ya(this.Pa);this.Pa.listen(this.ha.kc(),"cmn",this.ra)};r(Ovg,A);var Pvg=new dg("Cpr8Ee"),Qvg=function(a){y.call(this,"wk");this.Af=a};r(Qvg,y);Ovg.prototype.ra=function(a){this.dispatchEvent(new Qvg(a.Af[1]))};
var Rvg=function(a){v.call(this);this.Pa=new B(this);this.Ya(this.Pa);this.ra=new A;this.Ya(this.ra);this.ha=YB(a);var b=El(a,sia,!0);b.addCallback(this.BYc,this);b=El(a,Pvg,!0);b.addCallback(this.OGc,this)};r(Rvg,v);f=Rvg.prototype;f.kc=function(){return this.ra};f.OGc=function(a){this.Pa.listen(a,"wk",this.DYc)};
f.DYc=function(a){a=Dd(a.Af);switch(a[0]){case "n_cc":sD(this.ha,UBa);a=new zL(a);XX(this,"n_cc",a);break;case "n_nm":sD(this.ha,TBa);a=new UE(a);XX(this,"n_nm",a);break;case "n_gi":sD(this.ha,VBa);a=new ZDe(a);XX(this,"n_gi",a);break;case "n_id":sD(this.ha,WBa),a=new hFe(a),XX(this,"n_id",a)}};f.BYc=function(a){var b=a.UE("n");this.Pa.listen(b,"Mb",this.EYc);b=a.UE("m");this.Pa.listen(b,"Mb",this.CYc);b=a.UE("x");this.Pa.listen(b,"Mb",this.wa)};
f.EYc=function(a){var b=a.ha;if(va(b)&&2<=b.length&&"n"==b[0])switch(a=Dd(b[1]),a[0]){case "n_nm":b=b[2];a=new UE(a);va(b)&&0<b.length?VE(a,b):VE(a,[]);XX(this,"n_nm",a);break;case "n_cc":a=new zL(a);XX(this,"n_cc",a);break;case "n_gi":a=new ZDe(a);XX(this,"n_gi",a);break;case "n_id":a=new hFe(a),XX(this,"n_id",a)}};
f.CYc=function(a){a=a.ha;if("nm"==a[0]){var b=new UE;G(b,4,a[1]);G(b,5,a[2]);G(b,1,Svg(this,a[3]));G(b,9,a[4]);G(b,3,a[5]);G(b,6,a[6]||[]);b.Eq(a[7]);G(b,8,a[8]);G(b,10,a[9]);11<=a.length&&k(a[10])&&va(a[10])&&0<a[10].length?VE(b,a[10]):VE(b,[]);XX(this,"n_nm",b)}};var Svg=function(a,b){switch(b){case "draft":return 2;case "sent":return 1;case "read_receipt":return 3;case "new":return 0}};Rvg.prototype.wa=function(a){a=a.ha;if("cc"==a[0]){var b=new zL;G(b,1,a[1]);G(b,2,a[2]);XX(this,"n_cc",b)}}; var XX=function(a,b,c){a.ra.dispatchEvent(new YYd(b,c))};
var Tvg=function(){this.config=new ovg};Tvg.prototype.dg=function(){return fh(this.config)};var Uvg=function(){this.config=new ovg;this.config.setContent(1);var a=new TX;ch(this.config,4,a)};r(Uvg,Tvg);var Vvg=function(a,b){hvg(ah(a.config,TX,4),kb(E(ah(a.config,TX,4),2),function(a){return a!=b}));return a};
var Yvg=function(a){v.call(this);this.Oa=a;this.Ca=null;this.ha=[];this.Da=null;this.ra=[];El(this.Oa,Kzd,!0).addCallback(function(a){this.Ca=a;Wvg(this)},this);El(this.Oa,Lzd,!0).addCallback(function(a){this.Da=a;Xvg(this)},this);this.wa=this.Oa.get(Jzd);this.Fa=a.get(Hzd);this.Ga=[];this.Aa=[];a=new B(this);this.Ya(a);a.listen(this.wa,"Fa",this.Ha)};r(Yvg,v);
var awg=function(a,b,c,d,e,g){var h=e||Od();g&&(h=Od());if(null===a.Ca||"r"!=a.wa.Eb){var l={id:d,Yg:c,config:b,Tx:h,FL:!1};h.Sj.then(function(){l.FL=!0});a.ha.push(l);return h.Sj}Zvg(a.Ca,null!=b?new qvg(b.Pf()):new qvg,c,d).then(function(a){$vg(this.Fa,a);h.resolve(a);this.Ga.push({id:d,Yg:c,config:b,Tx:h,FL:!0})},void 0,a);return h.Sj},bwg=function(a,b,c,d,e){var g=d||Od();e&&(g=Od());if(null===a.Da||"r"!=a.wa.Eb){var h={config:b,Yg:c,Tx:g,FL:!1};g.Sj.then(function(){h.FL=!0});a.ra.push(h);return g.Sj}Zvg(a.Da,
null!=b?new qvg(b.Pf()):new qvg,c).then(function(a){$vg(this.Fa,a);g.resolve(a);this.Aa.push({Yg:c,config:b,Tx:g,FL:!0})},void 0,a);return g.Sj};Yvg.prototype.Ha=function(){"r"==this.wa.Eb?(Wvg(this),Xvg(this)):(this.ha=this.Ga,this.Ga=[],this.ra=this.Aa,this.Aa=[])};
var Wvg=function(a){if(0!=a.ha.length){var b=a.ha;a.ha=[];t(b,function(a){awg(this,a.config,a.Yg,a.id,a.Tx,a.FL)},a)}},Xvg=function(a){if(0!=a.ra.length){var b=a.ra;a.ra=[];t(b,function(a){bwg(this,a.config,a.Yg,a.Tx,a.FL)},a)}},ewg=function(a,b){this.wa=a;var c=this.ra=b,d="wblh"+cwg+"-"+dwg++;c.config.uf(d)},dwg=0,cwg=Math.random(),fwg=function(a,b,c){var d=a.ra;d.config.setPosition(2);d=d.dg();return awg(a.wa,d,c,b)},gwg=function(a){this.ha=new Uvg;ewg.call(this,a,this.ha)};r(gwg,ewg); var hwg=function(a,b){Vvg(a.ha,b);return a},iwg=function(a,b){var c=a.ha;if(!sb(E(ah(c.config,TX,4),2),b)){var d=E(ah(c.config,TX,4),2)||[];d.push(b);hvg(ah(c.config,TX,4),d)}return a};
var jwg=function(a){A.call(this);this.Aa=a.Nc(vx);this.wa="i";a=new B(this);this.Ya(a);null!=this.Aa&&(a.listen(this.Aa.kc(),"capii_l_ucm",this.Da),a.listen(this.Aa.kc(),"capi:clstup",this.Ca));this.ra={};this.ra[UX.a9a]="i";this.ra[UX.gC]="s";this.ra[UX.JGa]="c";this.ra[UX.d9a]="in";this.ra[UX.Bab]="v";this.ra[UX.A7a]="bu";this.ra[UX.t7a]="ar";this.ra[UX.upa]="ct";this.ra[UX.c$a]="p";this.ha={};this.ha.i=UX.a9a;this.ha.s=UX.gC;this.ha.c=UX.JGa;this.ha["in"]=UX.d9a;this.ha.v=UX.Bab;this.ha.bu=UX.A7a;
this.ha.ar=UX.t7a;this.ha.ct=UX.upa;this.ha.p=UX.c$a};r(jwg,A);var kwg=function(a,b){var c=a.wa!=b;a.wa=b;c&&a.dispatchEvent("xk");return c},lwg=function(a){if(null!=a.Aa){var b=new szd;G(b,1,a.ha[a.wa]);a.Aa.sendMessage(b)}};jwg.prototype.Da=function(a){a=new szd(a.Af);kwg(this,this.ra[E(a,1)])};jwg.prototype.Ca=function(a){1!=E(new $yd(a.Af),1)&&lwg(this)};
var mwg=function(a){A.call(this);this.ha=a};r(mwg,A);var YX=new dg("O9EQob"),nwg=function(a,b){rj(a,YX,function(){return new mwg(b)})};mwg.prototype.Lv=function(a){var b=new Kbg;ch(b,1,a);SX(this.ha,b)};var pwg=function(a){A.call(this);this.wa=a;this.Eb=owg.LOADING;this.ra=!1;this.ha=!0;this.Pa=new B(this);this.Ya(this.Pa);this.Pa.listen(this.wa.kc(),"h_cs",this.Aa)};r(pwg,A);var owg={LOADING:0,KTb:1,Ajd:2,jDd:3,ERROR:4,LOADED:5,y7a:6},qwg=new dg("HwdKC"),rwg=function(a,b){rj(a,qwg,function(){return new pwg(b)})};pwg.prototype.getState=function(){return this.Eb};
pwg.prototype.Aa=function(a){a=new Obg(a.Af);var b=a.getState();null!=b&&this.Eb!=b&&(this.Eb=b,this.dispatchEvent("Ak"));b=E(a,2);null!=b&&this.ra!=b&&(this.ra=b,this.dispatchEvent("zk"));a=E(a,3);null!=a&&this.ha!=a&&(this.ha=a,this.dispatchEvent("yk"))};
var swg=function(a){A.call(this);this.ra=a.get(vx);this.ha=0;a=new B(this);this.Ya(a);a.listen(this.ra.kc(),"capi:ceu",this.wa)};r(swg,A);swg.prototype.wa=function(a){a=(new fzd(a.Af)).getMetadata();null!=a&&(a=E(a,1),za(a)&&a!=this.ha&&(this.ha=a,this.dispatchEvent("Bk")))};
var twg=function(a){A.call(this);this.ha=a;this.Pa=new B(this);this.Ya(this.Pa);this.Pa.listen(this.ha.kc(),"h_cu",this.ra)};r(twg,A);var uwg=function(a){y.call(this,"Ck");this.ha=a};r(uwg,y);var vwg=new dg("OBxvo");twg.prototype.ra=function(a){a=new Pbg(a.Af);this.dispatchEvent(new uwg(a))};
var wwg=function(a){A.call(this);this.ra=a.get(vx);this.Aa=this.ha=0;this.wg=this.wa=!1;a=new B(this);this.Ya(a);a.listen(this.ra.kc(),"capii_c_ucmc",this.Ca);this.ra.sendMessage(new oyd)};r(wwg,A);wwg.prototype.Ca=function(a){a=new oyd(a.Af);this.wa||(this.wa=!0,this.wg&&(G(a,5,!0),this.wg=!1));var b=this.ha!=E(a,1);this.ha=Number(E(a,1));var c=this.Aa!=E(a,2);this.Aa=Number(E(a,2));E(a,5)?this.dispatchEvent("Dk"):(b&&this.dispatchEvent("Fk"),c&&this.dispatchEvent("Ek"))}; var xwg=function(a){rj(a,Fzd,function(){return new wwg(a)})};
var ywg=function(){v.call(this)};r(ywg,v);var Zvg=function(a,b,c,d){a=c||Ie();c=a.Ba(b.getId());a.removeNode(c);b=new zwg(a,a.Ba(d),b);return Ld(b)},zwg=function(a,b,c){this.ra=b;this.Jb=a;this.ha=c};r(zwg,A);f=zwg.prototype;f.kc=function(){return this};f.getId=function(){return this.ha.getId()};f.Ka=function(){return this.Jb};f.getExtension=function(){return null};f.le=sa;f.Kb=function(){return fh(this.ha)};
var Awg=function(a){A.call(this);this.ha=a.get(vx);a=new B(this);this.Ya(a);a.listen(this.ha.kc(),"capi:rfc",this.wa);a.listen(this.ha.kc(),"capii_c_cel",this.ra)};r(Awg,A);var Bwg=function(a){y.call(this,"Gk");this.email=a};r(Bwg,y);Awg.prototype.wa=function(a){a=new nyd(a.Af);2==E(a,1)&&this.ha.sendMessage(a)};Awg.prototype.ra=function(a){a=new myd(a.Af);this.dispatchEvent(new Bwg(a.getEmail()))};
var Cwg=function(a){v.call(this);this.ha=a};r(Cwg,v);var Dwg={tXb:0,lUb:1,uXb:2},Ewg={DTb:0,bUb:1,FTb:2},Fwg=new dg("lHqLwe"),Gwg=function(a,b){rj(a,Fwg,function(){return new Cwg(b)})};var Hwg=function(a,b,c){this.wa=b||"e";this.ra=c||"en";this.ha=new Kd(function(b){a.get(vx).kc().listen("capi:fsc",function(a){b(new kzd(a.Af))})});md(this,this.ha.cancel,this.ha)};r(Hwg,v);
var $vg=function(a,b){var c=b.Kb();Iwg(a,c).then(function(a){var d=0==E(c,2);a={id:c.getId(),src:a,frameBorder:"0",tabIndex:"0",allowTransparency:"true",style:d?"background-color: transparent; width: 0; height: 0; border: 0px; overflow-y: hidden; position: absolute;":"background-color: transparent; width: 100%; height: 100%; border: 0px; overflow-y: hidden; position: absolute;"};a:{switch(c.getContent()){case pvg.UTb:d="a1k";break a;case pvg.wXb:d=E(ah(c,ivg,4),1)?"a1j":"a1i";break a}d=null}d&&(a["class"]=
d);a=b.Ka().Na("IFRAME",a);b.ra.appendChild(a)},void 0,a)},Iwg=function(a,b){return a.ha.then(function(a){var c=we(E(a,1),"frame2");qe(c,"v",a.Py());qe(c,"pvt",E(a,10));qe(c,"prop",E(a,11));null==c.toString().match(/\/u\/\d+\//)&&qe(c,"authuser",E(a,4));qe(c,"hl",this.ra);ne(c,this.wa+b.Lg());return c.toString()},void 0,a)};
var Jwg=function(a){A.call(this);this.ha=a.get(vx);a=new B(this);this.Ya(a);a.listen(this.ha.kc(),"h_bm",this.ra);a.listen(this.ha.kc(),"h_br",this.wa)};r(Jwg,A);var Kwg=function(a){y.call(this,"Hk");this.frameId=a};r(Kwg,y);Jwg.prototype.ra=function(a){a=new Fbg(a.Af);a=new Kwg(E(a,1));this.dispatchEvent(a)};Jwg.prototype.wa=function(){this.dispatchEvent("Ik")};
var Lwg=function(a){A.call(this);this.ha=a;this.Pa=new B(this);this.Pa.listen(this.ha.kc(),"h_maa h_mac h_maps h_mad h_mafn h_map h_mars h_mam h_mas".split(" "),this.ra)};r(Lwg,A);var Mwg=function(a,b,c,d,e){y.call(this,"Jk");this.id=a;this.ra=b;this.ha=c;this.maxWidth=d;this.maxHeight=e};r(Mwg,y);var Nwg=function(a,b,c,d,e){y.call(this,"Kk");this.id=a;this.url=b;this.width=c;this.height=d;this.ha=e};r(Nwg,y);var Owg=function(a){y.call(this,"Mk");this.id=a};r(Owg,y);
var Pwg=function(a,b,c){y.call(this,"Nk");this.id=a;this.direction=b;this.position=c};r(Pwg,y);var Qwg=function(a,b,c,d){y.call(this,"Lk");this.id=a;this.url=b;this.width=c;this.height=d};r(Qwg,y);var Rwg=function(a,b,c,d,e){y.call(this,"Pk");this.id=a;this.ra=b;this.width=c;this.height=d;this.ha=e};r(Rwg,y);var Swg=function(a){y.call(this,"Ok");this.id=a};r(Swg,y);var Twg=function(a,b){y.call(this,"Qk");this.id=a;this.ha=b};r(Twg,y);var Uwg=function(a){y.call(this,"Rk");this.Ru=a};r(Uwg,y);
var Vwg=new dg("ho5I5b");
Lwg.prototype.ra=function(a){switch(a.type){case "h_maa":a=new Vbg(a.Af);a=new Mwg(a.getId(),E(a,2),E(a,3),E(a,4),E(a,5));break;case "h_mac":a=new Wbg(a.Af);var b=E(a,5);a=new Nwg(a.getId(),a.getUrl(),a.Ad(),a.Jd(),za(b)?b:void 0);break;case "h_maps":a=new Xbg(a.Af);a=new Qwg(a.getId(),a.getUrl(),a.Ad(),a.Jd());break;case "h_mad":a=new Ybg(a.Af);a=new Owg(a.getId());break;case "h_mafn":a=new Zbg(a.Af);a=new Pwg(a.getId(),E(a,2),E(a,3));break;case "h_map":a=new bcg(a.Af);a=new Swg(a.getId());break;
case "h_mars":a=new ccg(a.Af);b=E(a,5);a=new Rwg(a.getId(),E(a,2),a.Ad(),a.Jd(),za(b)?b:void 0);break;case "h_mam":a=new dcg(a.Af);a=new Twg(a.getId(),E(a,2));break;case "h_mas":a=new ecg(a.Af);a=new Uwg(E(a,1));break;default:return}this.dispatchEvent(a)};Lwg.prototype.Sa=function(){x(this.Pa);Lwg.Ea.Sa.call(this)};
var Wwg=function(a){A.call(this);this.Aa=a;this.wa=void 0;this.ra=null;this.ha=!1;this.Pa=new B(this);this.Ya(this.Pa);this.Pa.listen(this.Aa.kc(),"h_usi",this.Ca);this.Pa.listen(this.Aa.kc(),"h_usc",this.Da)};r(Wwg,A);var Xwg=new dg("mv5C0"),Ywg=function(a,b){rj(a,Xwg,function(){return new Wwg(b)})};Wwg.prototype.Ca=function(a){a=E(new pcg(a.Af),2);null!=a&&this.wa!=a&&(this.wa=a,this.dispatchEvent("Sk"))}; Wwg.prototype.Da=function(a){a=(new qcg(a.Af)).getState();null!=a&&a!=this.ra&&(this.ra=a,3==this.ra?this.ha=!0:0==this.ra&&(this.ha=!1),this.dispatchEvent("Tk"))};
var Zwg=function(a,b,c,d,e,g,h){v.call(this);this.og=b;this.Ui=d;this.wa=a;this.Hd=e;this.Ga=c;this.ha=g;this.ra=new Zc(h)};r(Zwg,v);f=Zwg.prototype;f.ze=function(){return this.og};f.Xn=function(a){return this.ra.contains(a)};f.yY=Ob(0);f.j4=function(){return{title:"",Gm:"aKW"}};f.getName=function(){return this.Hd};f.DBa=function(){return this.Hd};f.getEmail=function(){return this.Ui};f.wj=function(){return this.Ga};f.YZa=Ob("");f.AY=Pb;f.OUa=Pb;f.kba=function(){return!!this.og&&lO(this.og)}; f.ZZa=Pb;f.zY=function(){return this.wa};f.isAvailable=function(){return this.ha};
var ZX=function(a){v.call(this);this.Oa=a;var b=tA(a);this.Fa=b.getData("ui:e");this.Qa=b.jf();this.Ha=b.getData("ui:oid");this.Da=new A;this.Ya(this.Da);this.Pa=new B(this);this.Ya(this.Pa);this.ha=a.get(vwg);this.wa=new Uc;this.Ga=new Uc;this.Aa=new Uc;this.Ca=new Uc;this.Ia=hl(a).Pc().Gb(6112);this.Pa.listen(this.ha,"Ck",this.Ta)};r(ZX,H0f);ZX.prototype.U8=function(a,b,c){if(!a&&!b)throw Error("ad");var d=$wg(this,a,b);return d?d:axg(this,a,b,void 0,void 0,c)};
var $wg=function(a,b,c){return c&&a.Ca.Nd(c)?a.Ca.get(c):b&&a.Aa.Nd(b)?a.Aa.get(b):null};
ZX.prototype.ra=function(a,b,c,d,e){if(!a.isDisposed()){var g=new B(this);a.Ya(g);var h,l,n;n=[];var p=[];if(d){for(h=0;h<d.length;h++){l=d[h];var w=this.wa.get(l,0);0==w&&n.push(l);this.wa.set(l,w+1)}0<n.length&&(h=this.ha,xa(n)&&(n=[n]),w=new mcg,G(w,2,n||[]),SX(h.ha,w))}if(e){for(h=0;h<e.length;h++)n=e[h],w=this.Ga.get(n,0),0==w&&p.push(n),this.Ga.set(n,w+1);0<p.length&&(h=this.ha,xa(p)&&(p=[p]),n=new mcg,G(n,1,p||[]),SX(h.ha,n))}g.listen(this.Da,"Uk",Fa(this.Gc,new Zc(d),new Zc(e),b,c));md(a,
m(this.Va,this,d,e),this)}};ZX.prototype.Va=function(a,b){var c,d,e;e=[];var g=[];if(a){for(c=0;c<a.length;c++){d=a[c];var h=this.wa.get(d,0)-1;0<h?this.wa.set(d,h):(this.wa.remove(d),e.push(d),this.Aa.remove(d))}0<e.length&&(c=this.ha,xa(e)&&(e=[e]),h=new ocg,G(h,2,e||[]),SX(c.ha,h))}if(b){for(c=0;c<b.length;c++)e=b[c],h=this.Ga.get(e,0)-1,0<h?this.Ga.set(e,h):(this.Ga.remove(e),g.push(e),this.Ca.remove(e));0<g.length&&(c=this.ha,xa(g)&&(g=[g]),e=new ocg,G(e,1,g||[]),SX(c.ha,e))}};
ZX.prototype.Ta=function(a){2!=a.ha.getStatus()&&(axg(this,a.ha.ze()||void 0,a.ha.wj()||void 0,a.ha,void 0,a.ha.getName()||void 0),this.Da.dispatchEvent(new bxg(a.ha.ze(),a.ha.wj())))};
var axg=function(a,b,c,d,e,g){if(!b&&!c)throw Error("ad");var h=$wg(a,b,c);b=b||h&&h.ze()||"";c=c||h&&h.wj()||"";e=e||h&&h.getEmail()||!lO(b)&&b||"";if(!(g=g||h&&h.getName())&&(g=e))a:{if((g=bA(a.Oa))&&(g=g.m4(e,1))&&0<g.length&&(g=g[0])){g=g.getName();break a}g=null}g=g||"";var l=!1;if(b==a.Fa||c==a.Ha)l=!0,g=a.Qa,b=b||a.Fa,c=c||a.Ha;d=d&&k(d.getStatus())?0==d.getStatus():!!h&&h.isAvailable();d=new Zwg(l,b,c,e,g,d,!l&&d?cxg:void 0);b&&a.Aa.set(b,d);c&&a.Ca.set(c,d);h||a.Ia&&!Ma(Na(d.wj()))&&Ma(Na(d.getEmail()))&&
El(a.Oa,Hk,!0).addCallback(m(a.Ja,a,d.wj()),a);return d},cxg=[4,9,8,1];ZX.prototype.Gc=function(a,b,c,d,e){a.isEmpty()&&b.isEmpty()?c.call(d):e.jid&&a.contains(e.jid)?c.call(d):e.zq&&b.contains(e.zq)&&c.call(d)};ZX.prototype.Ja=function(a,b){b.Hua([a],m(this.Ra,this,a))};ZX.prototype.Ra=function(a,b,c){if(a=$wg(this,void 0,a)){b=c.uc().Ku();for(var d,e=0;e<b&&!(d=H3d(c.uc(),e));e++);d&&(axg(this,a.ze(),a.wj(),void 0,d),this.Da.dispatchEvent(new bxg(a.ze(),a.wj())))}}; var bxg=function(a,b){y.call(this,"Uk");this.jid=a;this.zq=b};r(bxg,y);
var dxg=function(a){v.call(this);this.Oa=a};r(dxg,v);f=dxg.prototype;f.DS=function(a,b){var c=b.wj(),d=a.get(YX);if(Ma(Na(c))){var c=b.ze(),e=new nbg;G(e,1,c);SX(d.ha,e)}else e=new Jbg,G(e,1,[c]),d.Lv(e)};f.DY=function(){};f.lZa=function(a,b){var c=a.get(YX),d=[],e=new kcg;b&&G(e,1,b||[]);d&&G(e,3,d||[]);SX(c.ha,e)};f.VAa=function(a,b){var c=a.get(YX),d=new mbg;d.Ou(b);G(d,2,0);SX(c.ha,d);return 6};f.VBb=function(a,b){var c=a.get(YX),d=new mbg;d.Ou(b);G(d,2,1);SX(c.ha,d)};f.Kdb=function(){return!1}; f.Lv=function(a,b){var c=new Jbg;G(c,2,b);a.get(YX).Lv(c)};
var exg=function(a){fX.call(this,a);this.ha=iE(a)};r(exg,fX);exg.prototype.Ga=function(a){this.ha.ra()&&a()};exg.prototype.Aa=function(){return this.ha.ra()};exg.prototype.wa=function(a,b){this.ha.ha(a,b)};var fxg=function(a){v.call(this);this.ra=new hG(a);var b=new B(this);this.Ya(b);b.listen(a.get(Gzd),"Gk",this.ha)};r(fxg,v);fxg.prototype.ha=function(a){q3d(this.ra,a.email)};var gxg=function(a){return L('<div class="a07"><div class="T-P a06"><div class="T-P-Jz-UR" id="'+O(a.Ifa)+'"></div><div class="T-P-hFsbo-UR T-P-hFsbo"><div class="T-P-atD"></div><div class="T-P-atC"></div></div></div></div>')};var $X=function(a,b,c,d){Ej.call(this,b);this.Aa=a.get(via);this.ha=new ik("T-P",!0);this.ha.Uy=!0;this.ha.setPosition(void 0,0,50,void 0);this.ra=c;this.Qc=new Im;this.Qc.Mf(this);Gm(this.Qc,!1);this.wa=d;this.Ee=null};r($X,Ej);f=$X.prototype;f.Na=function(){this.Qd(qi(gxg,{Ifa:this.wa},void 0,this.Ka()));I(this.Ba(),!1);hxg(this,0);this.Qc.bD(this.Ba())};
f.Ua=function(){$X.Ea.Ua.call(this);var a=this.Mb("T-P-hFsbo-UR"),b=this.ha,c=this.Ba();b.ha=c;b.wa=a;this.Qc.setPosition(this.ha);a=He(this.Ba());this.Ee||(this.Ee=new Cj(a,!0),this.Ya(this.Ee));this.getHandler().listen(this.Ee,"key",this.qwa);this.getHandler().listen(a,"click",this.qwa,!0)};f.Nb=function(){var a=He(this.Ba());this.getHandler().ha(a,"click",this.qwa,!0);this.getHandler().ha(this.Ee,"key",this.qwa);$X.Ea.Nb.call(this)};f.qwa=function(a){this.Qc.$b()&&(mf(this.Ba(),a.target)||this.setVisible(!1))};
f.setVisible=function(a){if(a){var b=this.Ka().Mb(this.ra);this.ha.qk(b)}this.Qc.setVisible(a)};var hxg=function(a,b){var c=413+78*Math.floor((b+2)/3),d=a.Ka().Mb(a.ra),d=26+Ry(a.Aa,d),c=Math.max(c,d);Fh(a.Mb("T-P-Jz-UR"),263,c)};$X.prototype.Cd=function(){this.Qc.Cd()};$X.prototype.Sa=function(){this.Qc.dispose();delete this.Qc;$X.Ea.Sa.call(this)};
var ixg=function(a,b,c){v.call(this);this.Jb=eo(a).Ka();this.Da=BG(a);this.Aa=b;this.wa=a.get(Ezd);this.Ga=c;this.ra=new B(this);this.Ya(this.ra);this.Ca=this.wa.wa;a=new $X(a,this.Jb,"aTf","talk_flyout");a.render();a.setVisible(!1);hxg(a,this.Ga.ha);this.ha=a;this.Ya(this.ha);this.ra.listen(this.ha,"hide",this.Ia);a=new gwg(this.Aa);b=a.ha;c=ah(b.config,TX,4);G(c,1,!0);hvg(ah(b.config,TX,4),[2,3,4,5]);fwg(hwg(hwg(hwg(hwg(a,2),3),4),5),"talk_roster",this.Jb);fwg(iwg(iwg(iwg(iwg(new gwg(this.Aa),2),
3),4),5),"talk_flyout",this.Jb);this.ra.listen(this.wa,"xk",m(this.Ja,this));this.ra.listen(this.Ga,"Bk",this.Ha);(a=this.Da.Xl("gadget"))&&this.ra.listen(a.qn(),"tc",m(this.Fa,this))};r(ixg,v);ixg.prototype.Ja=function(){var a=jxg(this);a||(this.Ca=this.wa.wa);this.ha.setVisible(a)};ixg.prototype.Ha=function(){hxg(this.ha,this.Ga.ha)};ixg.prototype.Ia=function(){var a=this.wa;kwg(a,this.Ca)&&lwg(a)};var jxg=function(a){a=a.wa.wa;return"s"==a||"in"==a||"c"==a||"v"==a}; ixg.prototype.Fa=function(){hxg(this.ha,this.Ga.ha);jxg(this)&&(80>this.Da.Xl("gadget").Jd()?this.ha.setVisible(!1):this.ha.Cd())};
var kxg=function(a,b,c,d){b.listen(a.kc(),"h_sph",function(a){c.call(d,new hcg(a.Af))})},lxg=function(a,b,c,d){b.listen(a.kc(),"h_hph",function(a){c.call(d,new Sbg(a.Af))})},mxg=function(a,b,c){var d=c.createElement("DIV"),e=b.Lh();e&&d.setAttribute("oid",e);(e=b.getEmail())&&d.setAttribute("email",e);c.appendChild(c.Ab().body,d);a=c.Ba(a);a=lh(Hh(a));c=E(b,5);e=E(b,6);c+a.left<d.ownerDocument.body.clientWidth/2&&(c+=E(b,7));b=new Ae;b.x=a.left+c;b.y=a.top+e;d.style.position="absolute";gk(b,d,4); return d};
var nxg=function(a){v.call(this);this.Jb=eo(a).Ka();this.ra=new B(this);this.Ya(this.ra);this.ha=null;jce(a).addCallback(this.Aa,this)};r(nxg,v);nxg.prototype.Aa=function(a){this.ha=a};nxg.prototype.wa=function(a){if(this.ha){var b=E(a,9);null!=b||(b="gtn-roster-iframe-id-b");var c=mxg(b,a,this.Jb);a=new SKd(null,0,null,c,uh(c),!0,!0);this.ha.jBb(a);this.ra.ud(this.ha,"Te",function(){this.Jb.removeNode(c)})}};nxg.prototype.Ga=function(){this.ha&&this.ha.hAb(new yB(null,"Xa",!0))};
var oxg=function(a){v.call(this);this.Ga=a.get(Izd);this.wa=a.get(Ag);this.ha=new B(this);this.Ya(this.ha);this.ha.listen(this.Ga,["Hk","Ik"],this.ra)};r(oxg,v);oxg.prototype.ra=function(){this.wa.ha()};var pxg=function(a){v.call(this);this.Oa=a;this.Ub=tA(a);this.Lb=nB(a);this.wa=a.get(Xwg)};r(pxg,v);pxg.prototype.ha=function(a,b){var c=a.get(YX),d=new gbg;b&&G(d,1,b);SX(c.ha,d)};pxg.prototype.ra=function(){return!!this.wa.wa};var qxg=function(a){this.Oa=a};qxg.prototype.ha=function(a){if(a){var b=eo(this.Oa).Ka().getWindow();a.left+=b.screenLeft;a.top+=b.screenTop}else a=new kh(0,0,0,0);var b=this.Oa.get(Vwg),c=new Ubg;G(c,1,a.top);G(c,2,a.left);c.Kh(a.width);G(c,4,a.height);SX(b.ha,c)};
var rxg=function(a,b){Pm.call(this,!0,eo(a).Ka());this.ha=b;this.render()};r(rxg,Pm);var sxg={LHa:"oi",RYb:"nn",St:"cl"};f=rxg.prototype;f.Ac=function(){return"Kj-JD"};f.Na=function(){rxg.Ea.Na.call(this);var a={Dd:this.Ce(sxg),productName:ka};lA(this.Ba(),this.$ob(a));qn(this.Ba(),"aTA")};
f.Ua=function(){rxg.Ea.Ua.call(this);var a=new Am(null);this.Ya(a);a.Tb(this.Vb("nn"));Ng(this.getHandler(),a.Ba(),ym,this.$Za);a=new Am(null);this.Ya(a);a.Tb(this.Vb("oi"));Ng(this.getHandler(),a.Ba(),ym,this.eVc);this.getHandler().listen(this.Vb("cl"),"click",this.$Za);this.getHandler().listen(this.Ba(),"keydown",this.dVc)};f.$Za=function(){this.setVisible(!1)}; f.dVc=function(a){"keydown"==a.type&&27==a.keyCode?(this.$Za(),a.stopPropagation(),a.preventDefault()):9==a.keyCode&&a.shiftKey&&a.target==this.Ba()&&Pra(this)};f.eVc=function(){AFe(this.ha)};f.$ob=function(){return null};
var txg=function(a){this.Oa=a;var b=hl(a).Pc();this.Fa=b.Gb(6422);this.Aa=b.Gb(6479);b=qA(tA(a),438);this.ha=a.get(sg).Xl(b?"right":"gadget");this.Pa=new B(this);this.Ya(this.Pa);this.ra=a.get(Ezd);this.Ga=a.get(Fzd);this.Ha=a.get(hpa);this.Ca=a.get(Xwg);this.Ja=0;this.Da();this.Pa.listen(this.ha,"oc",this.Da);this.Pa.listen(this.ra,"xk",this.Ia);this.Pa.listen(this.Ga,"Fk",this.wa);this.Pa.listen(this.Ca,"Tk",this.wa)};r(txg,v);var uxg="a65 a66 a67 a68 a69 a7a a7b a7c a7d a7e a7f a64".split(" ");
txg.prototype.Da=function(){var a=this.ha.wa,b=this.ra.wa;"chat"==a&&"i"!=b?(a=this.ra,kwg(a,"i")&&lwg(a)):"contacts"==a&&"ct"!=b?(a=this.ra,kwg(a,"ct")&&lwg(a)):this.Aa&&"phone"==a&&"p"!=b&&(a=this.ra,kwg(a,"p")&&lwg(a));this.wa()};txg.prototype.Ia=function(){var a=this.ra.wa,b=this.ha.wa;if("contacts"==b||"chat"==b||"phone"==b)"ct"==a&&"contacts"!=b?this.ha.Qa("contacts"):"i"==a&&"chat"!=b?this.ha.Qa("chat"):this.Aa&&"p"==a&&"phone"!=b&&this.ha.Qa("phone");this.wa()};
txg.prototype.wa=function(){if(this.Fa){var a=["a65"],b=this.ha.wa,c="Hangouts conversations.";if(this.Ca.ha){var d=this.Ga.ha;"chat"!=b&&(a=0<d&&9>=d?["a64",uxg[d]]:9<d?["a64","a7f"]:["a65"]);1<=d&&(c=(new Hn("Hangouts conversations. {COUNT, plural, =0 {unused plural form}=1 {You have one unread conversation.}other {You have # unread conversations.}}")).format({COUNT:d}))}this.Ha.ra("chat",a,uxg,c)}};
var vxg=function(a){this.Oa=a;this.Lb=a.get(Qk);var b=qA(tA(a),438),c=gC(a);this.Aa=b?null:c.Ja;vG(a).Xca()&&(b=new txg(a),this.Ya(b));this.Pa=new B(this);this.Ya(this.Pa);this.Ca=new yFe(a);this.Ya(this.Ca);this.Da=a.get(Ezd);this.wa=a.get(Xwg);El(a,Mzd,!0).addCallback(this.ONc,this);this.Ga=null};r(vxg,v);f=vxg.prototype;f.ONc=function(a){this.ra=a;this.Pa.listen(this.ra,"Ha",this.fVc);this.ha=BG(this.Oa);this.Aa&&this.Pa.listen(this.Aa,"tc",this.dMc);this.Pa.listen(this.wa,"Tk",this.kQc)};
f.fVc=function(a){var b=new rxg(this.Oa,this.Ca);this.Ya(b);b.setVisible(!0);a.preventDefault()};f.qEb=function(){var a=BG(this.Oa).Xl("gadget");a&&"chat"!=a.Ia()&&a.Xa("chat");if(this.ra){var a=this.ra,b=new fyd;SX(a.ha,b)}};f.dMc=function(){var a=this.ra,b=new hyd;SX(a.ha,b);if(a=this.ha.Xl("gadget"))a="chat"==a.Ia(),this.Ga!=a&&(this.Ga=a,fvg(this.ra,a))};f.kQc=function(){var a=null;this.wa.ha?a=!0:!this.wa.ha&&(a=!1);ya(a)&&this.Lb.ha({bx_wyjps:a},!1)};
var wxg=function(a){return L('<iframe src="'+O(Ei(a.url))+'" frameborder="0" scrolling="no" class="a7A"></iframe>')};var yxg=function(a,b,c,d,e,g){Pi.call(this,a);this.Ja=a.get(Vwg);this.Ta=c;this.ha="sm:"+b;this.Ha=b;this.Aa=d;this.ra=this.Ca=e;this.Ra=g;this.Ia=40;this.Da=!1;this.Va=q();a=this.Ba();qn(a,"aAl");oi(a,wxg,{url:this.Ta});xxg(this)};r(yxg,bj);f=yxg.prototype;f.getType=function(){return"sm"};f.Ok=function(){return this.ha};f.focus=function(a){var b=0;2==a&&(b=2);1==a&&(b=1);a=this.Ja;var c=this.Ha,d=new Qbg;G(d,1,c);d.setPosition(b);G(d,4,!1);SX(a.ha,d);this.Aa.qz(this.ha);this.Aa.Va(this.ha)};
f.UFa=function(){};f.X0=function(){return!0};f.Oja=function(){return!1};f.jB=function(){var a=this.Ja,b=this.Ha,c=new $bg;c.uf(b);SX(a.ha,c)};f.tx=function(){var a=this.Ja,b=this.Ha,c=new acg;c.uf(b);SX(a.ha,c)};f.Mo=function(){return this.Da};f.Gta=function(){};f.Sga=function(){};f.uva=function(){return this.Mo()?0:Math.max(0,this.ra-this.Ca)};f.HDa=function(){this.dispatchEvent("I");this.tx()};f.kc=function(){return this}; f.resize=function(a,b){a!=this.ra&&(this.ra=a,MTf(this.Aa,this.ha,this.ra));this.Ra=b;xxg(this)};var xxg=function(a){var b=a.Ba(),c=b.getElementsByTagName("iframe")[0];c.width=a.Da?Math.min(a.ra,a.Ca):a.ra;a=a.Da?a.Ia:a.Ra;c.height=a;Eh(b,a)};
var zxg=function(a){v.call(this);this.Oa=a;this.wa=!1;this.ra=[];this.Pa=new B(this);this.ha={};this.Aa=a.get(pg);this.Ga=a.get("b8dsi").Pc().Gb(6524)?vBa:uBa;El(a,Vwg,!0).addCallback(this.bCc,this)};r(zxg,v);f=zxg.prototype;
f.bCc=function(){var a=this.Oa.get(Vwg);this.Pa.listen(a,"Kk",this.KLc);this.Pa.listen(a,"Mk",this.LLc);this.Pa.listen(a,"Ok",this.NLc);this.Pa.listen(a,"Qk",this.PLc);this.Pa.listen(a,"Rk",this.RLc);this.Pa.listen(a,"Nk",this.MLc);this.Pa.listen(a,"Lk",this.JLc);this.Pa.listen(a,"Pk",this.OLc)};f.KLc=function(a){this.ha[a.id]=q();var b=Axg(this),c=Bxg(this,a.id),d="sm:"+a.id;c?(Ab(this.ra,d),b.HL(d,this.wa,!0)):(Cxg(this,a.id,a.url,a.width,a.height,this.wa),c=Bxg(this,a.id));k(a.ha)&&(c.Ia=a.ha)};
f.LLc=function(a){var b=Bxg(this,a.id);b&&Axg(this).Xa(b.Ok(),!0);Ab(this.ra,"sm:"+a.id)};f.JLc=function(a){this.ha[a.id]=q();Cxg(this,a.id,a.url,a.width,a.height,!0);this.ra.push("sm:"+a.id)};f.OLc=function(a){var b=Bxg(this,a.id);if(b){fc(this.ha,a.id)&&(this.ha[a.ra]=this.ha[a.id],ic(this.ha,a.id));var c=a.ra,d=a.width,e=a.height,g=b.ha;b.ha="sm:"+c;b.Ha=c;b.Aa.Rb(g,b.ha);c=new Be(d,e);(e=rU(b.Aa,b.ha))&&e.Fe&&e.Fe.resize(c);b.Ca=d;k(a.ha)&&(b.Ia=a.ha)}};
f.NLc=function(a){Axg(this).qz("sm:"+a.id);if(fc(this.ha,a.id)){var b=q(),c=this.ha[a.id];ic(this.ha,a.id);this.Aa.ha(this.Ga,b-c)}};f.PLc=function(a){var b=Bxg(this,a.id);b&&(a=a.ha,b.Da=a,b.ra>b.Ca&&MTf(b.Aa,b.ha,a?b.Ca:b.ra),xxg(b),a?b.dispatchEvent("G"):b.dispatchEvent("H"))};f.MLc=function(a){var b=Axg(this),c="sm:"+a.id,d=0==a.direction?-1:1;switch(a.position){case 0:a=0;break;case 2:a=2;break;case 1:a=1;break;default:a=0}b.Ca(c,d,a,!1)};
f.RLc=function(a){for(var b=Axg(this),c=b.r9("sm"),d=0,e;e=c[d];d++)sb(this.ra,e)||b.HL(e,a.Ru,!0);this.wa=a.Ru};var Cxg=function(a,b,c,d,e,g){a=Axg(a);b=new yxg(a.getContext(),b,c,a,d,e);c=new Be(180,175);d=new Be(d,e);e=q();var h=new ETf(b,0,d.width,g,!0);h.Fe=new bvg(a.wa.getContext(),h.Hu,c,d,h.Hu,a);Wx(h.Fe,1);Xx(h.Fe,0);Vx(h.Fe,d.width+5);FTf(a,b,h,!1,e);a.Qa&&!g&&xTf(h.Fe,a.Qa)},Axg=function(a){return a.Oa.get("IaE3y").Pc()},Bxg=function(a,b){return Axg(a).xx("sm:"+b)}; zxg.prototype.Sa=function(){x(this.Pa);zxg.Ea.Sa.call(this)};
var Dxg=function(a){this.ha=jD(a);this.Pa=new B(this);this.Ya(this.Pa);El(a,Fwg,!0).addCallback(this.wa,this)};r(Dxg,v);Dxg.prototype.wa=function(a){this.ra=a;this.Pa.listen(this.ha,"Bb",this.Ga)};Dxg.prototype.Ga=function(){var a=this.ra,b=Exg(this),c=Fxg(this),d=new kvg;G(d,1,b);G(d,2,c);b=new Rbg;ch(b,1,d);SX(a.ha,b)}; var Fxg=function(a){switch(a.ha.Rd()){case "t":return Ewg.FTb;case "s":return Ewg.bUb;default:return Ewg.DTb}},Exg=function(a){a=aSd(a.ha);k(a)||(a=Kaa);switch(a){case 2:return Dwg.lUb;case 0:return Dwg.uXb;default:return Dwg.tXb}};
var Gxg=function(a,b){v.call(this);this.ha=new B(this);this.Ya(this.ha);this.ha.listen(a.kc(),"h_ssf",function(a){a=E(new icg(a.Af),1);var c;if(null!=a&&JSON&&JSON.parse)try{c=JSON.parse(a)}catch(g){}b(c)});var c=new fcg;G(c,1,1);SX(a,c)};r(Gxg,v);var Hxg=function(a){v.call(this);this.Ya(new Gxg(a,m(this.ha,this)))};r(Hxg,v);Hxg.prototype.ha=function(a){var b={productId:83052,locale:"en"},c=$f();c&&(b.authuser=c);dWd(b,a,window.top)};var Ixg=function(a){v.call(this);this.Oa=a;this.Pa=new B(this);this.Ya(this.Pa);this.wa=new Dxg(a);this.Ya(this.wa);a=a.get("b8dsi").Pc();this.ra=a.Gb(6199);this.Da=a.Gb(6524)};r(Ixg,v);var Jxg=/^([a-z0-9_-]+[.])?hangouts$/;
Ixg.prototype.init=function(){var a=eo(this.Oa).Ka().Ab(),b=tA(this.Oa),c=new Mbg;c.setProperty(18);G(c,6,!1);c.Ps("en");G(c,12,"talk_roster");G(c,15,"gtn-roster-iframe-id-b");G(c,13,!0);var d;a:{if((d=Jha.get())&&Jxg.test(d)){if("hangouts"==d){d="hangouts.google.com";break a}if(Ja(d,".hangouts")){d+=".sandbox.google.com";break a}}d=b.getData("pi:tgu")}G(c,1,d);d=b.getData("ui:ovt");G(c,3,d);d=$f()||"0";c.aE(d);this.ra&&G(c,17,!0);d=new rbg;var e=this.wa,g=new kvg,h=Fxg(e);G(g,2,h);G(g,1,Exg(e));
ch(d,3,g);d=d.Lg();G(c,5,d);d=new avg;G(d,7,380);ch(c,10,d);e=!b.getData("ui:wf");d=new $ug;G(d,1,e);b=!!b.getData("ui:yjsi");e=new Zug;G(e,1,b);ch(d,3,e);this.Da&&G(d,4,!0);ch(c,18,d);this.ha=new WX(c,a);this.Ya(this.ha);a=this.ha;c=this.Oa.Ro();c.registerService(Dzd,a);c.registerService(vx,a);b=new Lwg(a);c.registerService(Vwg,b);nwg(c,a);nF(mF(c),YX);Ywg(c,a);rwg(c,a);b=new twg(a);c.registerService(vwg,b);b=new Ovg(a);c.registerService(Pvg,b);lvg(c,a);Gwg(c,a);b=this.Oa;d=new nxg(b);b.registerService("EBRLyf",
d);kxg(a,d.ra,d.wa,d);lxg(a,d.ra,d.Ga,d);this.Ya(new Hxg(a));this.Oa.registerService(Gzd,new Awg(this.Oa));this.Oa.registerService(Izd,new Jwg(this.Oa));this.Oa.registerService(Ezd,new jwg(this.Oa));xwg(this.Oa);this.ra&&(c.registerService(Jzd,new mvg(c)),this.Oa.registerService(Hzd,new Hwg(this.Oa)),this.Oa.registerService(Kzd,new ywg(this.Oa)),this.Ya(new ixg(this.Oa,new Yvg(this.Oa),new swg(this.Oa))));this.Ca=q();a=this.ha;xa(void 0)&&(a.config.Ca=void 0);c=a.config;g=a.config.fV;b=a.config.SU;
if(Xa(g,"talkgadget."))if(d=ve(g),e=d.getPath(),0<=e.indexOf("/u/"))b=g;else{g=e.lastIndexOf("_/");if(0>g||g!=e.length-2)e+="_/";le(d,"/u/"+b+e);b=d.toString()}else b=g;c.fV=b;a.config.Ga=a.config.Ga.replace("notifierclient","chat");a.Da||(c=Ivg(a.config.fV,a.config.ha),a.Da=new Jvg(a.config,c,a.startTime,a.document,void 0),a.Ya(a.Da));Kvg(a.Da,a.config.yc,m(a.Dxc,a),m(a.ra,a,"_rosterIframeLoaded"));Tg&&(a.ha=a.document.createElement("IFRAME"),a.ha.id="gth-talk-plugin-frame-id",a.ha.name="gth-talk-plugin-frame-id",
a.ha.src=a.config.fV+"blank",a.ha.style.cssText="width: 0px; height: 0px; position: absolute; top: 0px; left: 0px; visibility:hidden;",a.document.documentElement.appendChild(a.ha),a.Fa=m(a.Tvc,a,a.ha.parentNode),a.ha.parentNode.addEventListener("DOMAttrModified",a.Fa,!0));Mvg(a);a=this.Oa.get(qwg);this.Pa.listen(a,"Ak",this.Ga);a=this.Oa.Ro();a.registerService("ciN9Rb",new dxg(a));nF(mF(a),"ciN9Rb");a.registerService("pLPUQe",new pxg(a));a.registerService("lcB75",new tbg(a));c=this.Oa;c.registerService("SnoUld",
new qxg(c));a.registerService("ITu2td",new ZX(a));nF(mF(a),"ITu2td");c=this.Oa;b=new vxg(c);c.registerService("N6bPGc",b);c=this.Oa;c.registerService("u",new exg(c));c=new Rvg(a);a.registerService("hgSKib",c);ybg(a,new Ebg(a));nF(mF(a),"F4zhRb");this.Ya(new fxg(this.Oa));this.Ya(new oxg(this.Oa));vG(this.Oa).OXa();El(this.Oa,"IaE3y").addCallback(m(this.Aa,this))};Ixg.prototype.Aa=function(){var a=new zxg(this.Oa);this.Ya(a)}; Ixg.prototype.Ga=function(){var a=this.Oa.get(qwg);a.getState()==owg.KTb&&(YB(this.Oa).ha(tBa,q()-this.Ca),vG(this.Oa).aFc(),this.Pa.ha(a,"Ak",this.Ga))};
var Kxg=function(){v.call(this)};r(Kxg,Yh);$h(ai(K.Ma(),"sm"),Kxg);Kxg.prototype.Zc=function(a){rj(a,"HCW0Vb",function(a){return new Ixg(a)})};
rxg.prototype.$ob=function(a,b,c){b="";var d="By reverting to the old chat you will lose access to your group Hangouts from "+(M(a.productName)+". You can always upgrade to Hangouts again by opening the chat menu by clicking on your profile picture.");b+='<div id="'+O(a.Dd.St)+'" class="T-P-aut-UR T-P-aut" aria-label="'+Ai("Close")+'" role="button" tabindex="0"></div><h3 class="Kj-JD-K7">Revert to old chat</h3><div class="Kj-JD-Jz aTB aQo"><p>'+d+'</p><p>Please let us know your reason for reverting by filling out a <a href="https://support.google.com/hangouts/contact/switch_chat" class="e" target="_blank">short survey</a>.</p></div><div class="Kj-JD-Jl">'+ M(Zj({id:a.Dd.RYb,style:2,content:xi("Stay with Hangouts")},null,c))+M(Zj({id:a.Dd.LHa,style:0,content:xi("Revert to old chat")},null,c))+"</div>";return L(b)};

di(K.Ma(),"sm");gi(K.Ma(),"sm");
}catch(e){_DumpException(e)}
// Google Inc.
