try{
var nFg=function(a){D(this,a,0,-1,null,null)};r(nFg,C);f=nFg.prototype;f.getTitle=function(){return E(this,2)};f.setTitle=function(a){G(this,2,a)};f.Jm=function(){return null!=E(this,2)};f.getTime=function(){return E(this,3)};f.setTime=function(a){G(this,3,a)};var oFg=[2],pFg=function(a){D(this,a,0,-1,oFg,null)};r(pFg,C);pFg.prototype.B6=function(a,b){return eh(this,2,a,nFg,b)};
var qFg=/^(\d{4})(?:(?:-?(\d{2})(?:-?(\d{2}))?)|(?:-?(\d{3}))|(?:-?W(\d{2})(?:-?([1-7]))?))?$/,rFg=/^(\d{2})(?::?(\d{2})(?::?(\d{2})(\.\d+)?)?)?$/,sFg=/Z|(?:([-+])(\d{2})(?::?(\d{2}))?)$/,tFg=function(a){if(!a)return null;var b=new pSe(a);a={};var c;c=(c=E(b,1))?40>=c.length?c:Ya(c).substring(0,37)+"\u2026":"<i>{No Title}</i>";a.gH=jA(c);a.eventTime=jA(E(b,2));a.OA=E(b,3);c=E(b,4);a.Cga=jA(c||"");if(c=E(b,5)){b=new Ol(2E3);c=Pa(c);var d=-1==c.indexOf("T")?" ":"T";c=c.split(d);var e=c[0].match(qFg);
if(e){var g=Number(e[2]),h=Number(e[3]),l=Number(e[4]),d=Number(e[5]),n=Number(e[6])||1;b.setFullYear(Number(e[1]));l?(b.setDate(1),b.setMonth(0),b.add(new Ml("d",l-1))):d?(b.setMonth(0),b.setDate(1),e=b.getDay()||7,b.add(new Ml("d",(4>=e?1-e:8-e)+(Number(n)+7*(Number(d)-1))-1))):(g&&(b.setDate(1),b.setMonth(g-1)),h&&b.setDate(h));d=!0}else d=!1;d&&!(d=2>c.length)&&(c=c[1],d=c.match(sFg),n=0,d&&("Z"!=d[0]&&(n=60*Number(d[2])+Number(d[3]),n*="-"==d[1]?1:-1),n-=b.getTimezoneOffset(),c=c.substr(0,c.length-
d[0].length)),(d=c.match(rFg))?(b.setHours(Number(d[1])),b.setMinutes(Number(d[2])||0),b.setSeconds(Number(d[3])||0),b.setMilliseconds(d[4]?1E3*Number(d[4]):0),0!=n&&b.setTime(b.getTime()+6E4*n),d=!0):d=!1);b=d?b:null;a.SNa=Ll.Ypa[b.getMonth()];a.RNa=b.getDate();a.TNa=Ll.Wda[b.getDay()]}return a},uFg=function(a){return L('<span class="cD">'+M(xz(a.name))+"</span>")},vFg=function(a){if(!a)return null;var b={};b.name=a[0];b.Rr=a[1];return b},wFg=function(a){D(this,a,0,-1,null,null)};r(wFg,C); var xFg=[1],yFg=function(a){D(this,a,0,-1,xFg,null)};r(yFg,C);yFg.prototype.B6=function(a,b){return eh(this,1,a,wFg,b)};fi(K.Ma(),"ca");
var zFg=function(){};var AFg=function(a,b,c,d){GG.call(this,a,239);this.Ta=c;this.Xa=d;this.ty(b);this.Ja="FAIL"};r(AFg,GG);AFg.prototype.Sc=function(a){AFg.Ea.Sc.call(this,a);ul(a,"eid",this.Ta)};AFg.prototype.Hs=function(){AFg.Ea.Hs.call(this);this.Xa(this)};AFg.prototype.rB=function(a,b){if(!this.aq)return null;if(!this.ha){for(var c={},d=bh(new yFg(this.aq),wFg,1),e=0;e<d.length;++e){var g=E(d[e],1),h=E(d[e],2),l=E(d[e],3);l&&(c[g+"_"+h]=l)}this.ha=c}return this.ha[a+"_"+b]};
var CFg=function(a,b,c){b=L;var d='<div class="aHn"><div id="'+O(a.Oc.HXb)+'" class="aHm">',e;e=L('<div class="aFM"><img class="aFN" src="//ssl.gstatic.com/ui/v1/icons/mail/images/cleardot.gif"><span class="aFV">Events in this message</span></div>');d+=e;e='<table class="aFI">';if(a.o8)for(var g=a.o8,h=g.length,l=0;l<h;l++)e+='<tr class="OTt0qb">'+BFg(vi({Oc:a.Oc},g[l]),null,c)+"</tr>";if(a.pHa)for(g=a.pHa,h=g.length,l=0;l<h;l++)for(var n=g[l].o8,p=n.length,w=0;w<p;w++)e+='<tr class="OTt0qb">'+BFg(vi({Oc:a.Oc},
n[w]),null,c)+"</tr>";e=L(e+"</table>");d+=e;c=c||{};e='<div class="aMX aFL">';a.Q8a&&(g=In(new Hn("{NUM_EVENTS,plural,=0{unused plural form}=1{This event has been added to your calendar.}other{These events have been added to your calendar.}}"),{NUM_EVENTS:a.BWb}),e+="<span>"+M(zm({id:a.Oc.yGa,Yu:zi("OlDBYd"),content:xi("Add to Google Calendar"),style:5},null,c))+'</span><span style="'+(c.kb?"/*"+c.kb+"*/":"")+'display:none"><span class="aFX">An error occurred.</span> '+M(zm({id:a.Oc.SHa,Yu:zi("OlDBYd"),
content:xi("Try again"),style:5},null,c))+'</span><span style="'+(c.kb?"/*"+c.kb+"*/":"")+'display:none"><img class="aFP" src="//ssl.gstatic.com/ui/v1/icons/mail/spinner.gif"></img><span class="aFX" id="'+O(a.Oc.xGa)+'">Adding</span></span><span style="'+(c.kb?"/*"+c.kb+"*/":"")+'display:none"><span class="aFX" id="'+O(a.Oc.wGa)+'">'+g+"</span></span>");a.qSb&&(e+='<span id="'+O(a.Oc.LVb)+'" class="aFO">Enter feedback</span>');a=L(e+"</div>");return b(d+a+"</div></div>")},BFg=function(a){return L('<td class="aFW"><div class="aFK"><a id="'+ O(a.Oc.D8a)+O(a.id)+'">'+M(a.title)+'</a></div></td><td class="aFU"><div class="aFJ">'+M(a.time)+"</div></td>")};
var PY=function(a,b,c,d,e){Pi.call(this,a);this.ra=b;this.ha=this.Ce(DFg);this.ra.Oc=this.ha;b=tA(a);b=Ja(b.getData("ui:e"),"@google.com");this.ra.qSb=!!e&&b;this.Ia=c;this.Ja=dC(a);this.Qa=e||null;this.Aa=d;this.Fa=!0;this.wa=YB(a)};r(PY,Pi);var DFg={HXb:"md",yGa:"addAll",xGa:"addingAll",SHa:"retryAll",wGa:"addedAll",D8a:"eventTitle",LVb:"feedback"};PY.prototype.Na=function(){PY.Ea.Na.call(this);this.yb=qi(CFg,this.ra);this.wa.ha(XKa);this.ra.Q8a&&this.wa.ha(YKa)};
PY.prototype.Ua=function(){PY.Ea.Ua.call(this);for(var a=this.getHandler(),b=this.Ka().zk("OlDBYd",this.Ba()),c=0;c<b.length;++c){var d=b[c],e=new Am(null);this.Ya(e);e.Tb(d);Mg(a,d,ym,this.Roc,void 0)}(b=this.Ka().Mb("aFO",this.Ba()))&&Mg(a,b,ym,this.Vrc,void 0);EFg(this,this.hQb);b=this.Ka().zk("aFK",this.Ba());t(b,function(b){a.listen(b,"mouseover",this.ytc);a.listen(b,"mouseout",this.stc)},this);this.Fa&&(a.listen(this.Aa,"lp_start",this.Da),a.listen(this.Aa,"lp_end",this.Ca),0<this.Aa.ha||this.Ca())};
PY.prototype.Da=function(){if(this.Ba().clientWidth){var a=this.Ka().Mb("aFI",this.Ba());FFg(this,a)}};
PY.prototype.Ca=function(){if(this.Ba().clientWidth){var a=this.Ka().Mb("aFI",this.Ba()),b=a.tBodies[0];FFg(this,b);for(var a=a.clientWidth-20,c,d=0,e=c=0,g=0;g<b.rows.length;++g){var h=b.rows[g],l=h.cells[0].firstChild;l.style.whiteSpace="nowrap";var n=l.clientWidth+1;l.style.whiteSpace="";n>d&&(d=n);h=h.cells[1].firstChild;h.style.whiteSpace="nowrap";l=h.clientWidth+1;h.style.whiteSpace="";l>c&&(c=l);n+=l;n>e&&(e=n)}c={title:d,time:c,row:e};if(!(c.row<a)){d=Math.ceil(.35*a);e=a-c.title;e>d&&(d=
e);e=Math.ceil(c.time/2.5);e>d&&(d=e);a=Math.ceil(.45*a);a<d&&(d=a);if(c.time>d)for(a=0;a<b.rows.length;++a)b.rows[a].cells[1].firstChild.style.width=d+"px";a=b.rows[0].cells[0].firstChild.clientWidth+1;for(d=0;d<b.rows.length;++d)c=b.rows[d].cells[0].firstChild,c.style.width=a+"px",c.style.whiteSpace="nowrap"}}};
var FFg=function(a,b){for(var c=0;c<b.rows.length;++c){var d=b.rows[c],e=d.cells[0].firstChild;e.style.width="";e.style.whiteSpace="";d.cells[1].firstChild.style.width=""}},EFg=function(a,b){var c=a.ra.o8;if(c)for(var d=0;d<c.length;++d)b.call(a,c[d]);if(c=a.ra.pHa)for(var e=0;e<c.length;++e)for(var g=c[e].o8,d=0;d<g.length;++d)b.call(a,g[d])};f=PY.prototype;
f.Roc=function(){var a;a=m(this.Ha,this);a=new AFg(this.getContext(),this.Ia,null,a);QY(this,this.ha.xGa,!0);QY(this,this.ha.yGa,!1);QY(this,this.ha.SHa,!1);QY(this,this.ha.wGa,!1);oB(this.Ja,a);a.send();this.wa.ha(ZKa)};f.Vrc=function(){var a={productId:"88",bucket:"internal",locale:"en"},b=$f();b&&(a.authuser=b);dWd(a)};f.ytc=function(a){a=a.target;a.title=a.clientWidth<a.scrollWidth?a.textContent:""};f.stc=function(a){rn(a.target,"ZihcV")};
f.hQb=function(a){a.link&&this.Ka().Ba(this.ha.D8a+a.id).setAttribute("href",this.ra.ha+a.link)};var GFg=function(a,b){QY(a,a.ha.xGa,!1);QY(a,a.ha.yGa,!1);QY(a,a.ha.SHa,!b);QY(a,a.ha.wGa,b)},QY=function(a,b,c){if(b=a.Ka().Ba(b))a=a.Ka().ria(b),I(a,c)};PY.prototype.Ha=function(a){var b=!!a.Oj;b&&EFg(this,function(b){var c;c=b.id;var e=c.indexOf("_");c=c.substring(0,e);var e=b.id,g=e.indexOf("_");b.link=a.rB(c,e.substring(g+1));b.Xzc=!!b.link;G(b.g$c,4,b.link)});GFg(this,b);EFg(this,this.hQb)};
var HFg=function(a,b,c,d,e,g){this.BWb=a;this.Q8a=b;this.ra=c;this.o8=d;this.pHa=e;this.ha=g},IFg=function(a,b,c,d,e,g){this.id=a;this.title=b;this.time=c;this.ha=d;this.link=e;this.Xzc=!1;this.g$c=g},JFg=function(a){this.o8=a};var KFg=function(){};var LFg=function(a){v.call(this);this.Oa=a;this.ra=new KFg};r(LFg,v);
LFg.prototype.ha=function(a,b){var c;c=this.Oa;var d;if(a){d=new WEd(a);var e=!(!E(d,15)&&!E(d,16)),g=bh(d,pFg,14);if(g&&0!=g.length){for(var h=[],l=[],n=0,p=!0,w=tA(c).getData("ui:cru"),z=0;z<g.length;++z){var F=g[z],J=E(F,1),F=bh(F,nFg,2),n=n+F.length,T=h;1<F.length&&(T=[],l.push(new JFg(T)));for(var la=0;la<F.length;++la){var Ca=F[la],Da=E(Ca,1),Ca=new IFg(J+"_"+Da,jA(Ca.getTitle()||""),jA(Ca.getTime()||""),e,E(Ca,4),Ca);T.push(Ca);p=p&&!!Ca.link}}d=new HFg(n,!p&&e&&0<n,!!E(d,15),0<h.length?h:
null,0<l.length?l:null,w)}else d=null}else d=null;c=d?new PY(c,d,b.ue().Je(),b.Zg().oh(),new zFg):void 0;if(!c){c=this.Oa;if(a){d={};e=a[18];g=a[14];k(g)?d.Pub=g:d.Pub=3!=a[0];d.NTa=a[1];d.Cy=tFg(a[2]);e&&(d.xla=tFg(a[17]));d.bSa=a[16];d.OU=[];g=a[3];h=0;for(l=g.length;h<l;++h)d.OU[h]=vFg(g[h]);d.XAa=vFg(a[4]);if(g=a[5]){h={};h.hOb=jA(g[0]);h.WT=[];l=g[1];n=0;for(p=l.length;n<p;++n)h.WT[n]=tFg(l[n]);h.QJ=g[2];h.UQb=g[3];g=h}else g=null;d.Kq=g;d.TIa=a[6];d.IQd=vFg(a[7]);d.ENa=a[8];d.e8b=a[12];d.Eo=
vFg(a[9]);d.m8=a[10];d.f0=jA(a[11]);d.Sv=xSe;if("expanded"==d.m8){if(d.bSa)g=jA("The guest list is not available");else if(0!=d.OU.length||d.XAa){g=[];l=h=0;for(n=d.OU.length;l<n&&80>h;++l)if(p=d.OU[l],1==p.Rr)0<h&&(g.push(", "),h+=2),g.push(jA(p.name)),h+=p.name.length;else if(0==p.Rr||3==p.Rr||6==p.Rr)0<h&&(g.push(", "),h+=2),g.push(uFg({name:p.name})),h+=p.name.length;if(80>h){if(d.XAa&&d.XAa.name)if(l=d.XAa,1==l.Rr)0<h&&g.push(", "),g.push(jA(l.name)),g.push("*");else if(0==l.Rr||3==l.Rr||5==
l.Rr)0<h&&g.push(", "),g.push(uFg({name:l.name+"*"}))}else g.push("...");g=kA(g)}else g=null;d.KJa=g;d.$O=d.Pub?0==d.NTa&&d.TIa?"add_to_cal":d.ENa&&1==d.NTa&&d.Eo&&4!=d.Eo.Rr&&5!=d.Eo.Rr?"standard":e&&d.ENa&&6==d.NTa?"counter":"none":"sign_up"}}else d=null;c=new MM(c,d,b.ue().hd(),b.ue().Ol())}return c};
var MFg=function(){v.call(this)};r(MFg,Yh);$h(ai(K.Ma(),"ca"),MFg);MFg.prototype.Zc=function(a){rj(a,foa,NFg)};var NFg=function(a){return new LFg(a)};
var QFg=function(a,b,c){b=L;if("expanded"==a.m8){var d;d=c||{};c=L;var e='<div id="'+O(a.Dd.F8a)+'"><table cellpadding="0" class="cf aU9"><tr><td class="aRi">'+M(Dcf(a.Cy,null,d))+"</td>";if(a.Kq&&(2<=a.Kq.WT.length||!a.Kq.QJ&&1<=a.Kq.WT.length)){var g='<td style="'+(d.kb?"/*"+d.kb+"*/":"")+'width:52%" class="aU4">'+OFg(a,null,d)+'</td><td class="aRc">',h=d;d='<div class="aQ3"><div class="aRo">Agenda</div><div class="aRn">'+M(a.Kq.hOb)+"</div>";var h=h||{},l='<table id="'+O(a.Dd.k7a)+'" class="cf aU2" style="'+
(h.kb?"/*"+h.kb+"*/":"")+'table-layout:auto">';if(0==a.Kq.WT.length)l+=M(Acf(null,null,h));else{for(var l=l+(0==a.Kq.QJ?M(Bcf(null,null,h)):""),n=a.Kq.WT,p=n.length,w=0;w<p;w++)var z=n[w],l=l+(w==a.Kq.QJ?M(eQ({lea:zi("aQ6"),eventTime:z.eventTime,hB:z.gH},null,h)):w>=a.Kq.QJ-2&&w<=a.Kq.QJ+2||!a.Kq.QJ&&0<=w&&5>w?M(eQ({eventTime:z.eventTime,hB:xi(""+(z.OA?PFg({TI:z.OA,ZH:z.gH,Jp:a.Jp},null,h):M(z.gH)))},null,h)):"");l+=a.Kq.QJ==a.Kq.WT.length-1?M(Ccf(null,null,h)):""}a=L(l+"</table>");a=L(""+(d+a+"</div>"));
a=g+a+"</td>"}else a='<td style="'+(d.kb?"/*"+d.kb+"*/":"")+'width:100%" class="aU4">'+OFg(a,null,d)+"</td>";a=c(e+a+"</tr></table></div>")}else"collapsed"==a.m8&&a.f0?(c=c||{},e=""+('<div id="'+O(a.Dd.U7a)+'"><table cellpadding="0" class="cf aU9"><tr><td class="aRi">'+M(Dcf(a.Cy,null,c))+'</td><td style="'+(c.kb?"/*"+c.kb+"*/":"")+'width:100%" class="aU4"><div class="aRo">'+M(a.Cy.gH)+'</div><div class="aRn">From Google Calendar</div>'+(a.f0?'<div id="'+O(a.Dd.V7a)+'" class="ZY9NGb">'+M(a.f0)+"</div>":
"")),a.Cy.OA&&(e+='<div class="aVa">'+PFg({TI:a.Cy.OA,ZH:xi("View updated information on Google Calendar"),Jp:a.Jp,className:zi("aU8")},null,c)+"</div>"),a=L(e+"</td></tr></table></div>")):a="";return b('<div class="aRb">'+a+"</div>")},OFg=function(a,b,c){b=M(Fcf({Dd:a.Dd,ZCa:xi("Google Calendar"),n8:a.Cy.gH,iRc:a.xla?a.xla.eventTime:null,eventTime:a.Cy.eventTime,QNa:a.Cy.Cga,OU:a.KJa,JQ:vla(""+(a.xla&&a.xla.OA?Ei(a.Jp+a.xla.OA):a.Cy.OA?Ei(a.Jp+a.Cy.OA):""))},null,c));var d="";"none"!=a.$O&&(d+='<div class="aRm">',
"standard"==a.$O?d+='<span id="'+O(a.Dd.r$a)+'">'+RFg({Rr:a.Eo.Rr,Sv:a.Sv,Dd:a.Dd},null,c)+"</span>":"sign_up"==a.$O?d+=PFg({TI:"",ZH:xi("Sign up for calendar &raquo;"),Jp:a.Jp},null,c):"add_to_cal"==a.$O?d+=PFg({TI:"",ZH:xi("Add to calendar &raquo;"),Jp:a.sbb},null,c):"counter"==a.$O&&(a=""+M(Zj({id:N(""+a.Dd.sRb),zy:!0,className:zi("aQ9"),content:xi("Accept")},null,c)),a=L(a),d+=a),d+="</div>");a=L(d);return L(""+(b+a))},RFg=function(a,b,c){b="";a.Rr==a.Sv.U9a?b+="You are the organizer.":a.Rr==
a.Sv.nab?b+="You are not invited.":a.Rr!=a.Sv.UNKNOWN&&(b+=M(Zj({id:N(""+(a.Rr!=a.Sv.ACCEPTED?""+a.Dd.c7a:"")),zy:!0,className:zi(""+(a.Rr==a.Sv.ACCEPTED?"aRa":"aQ9")),content:xi("Yes")},null,c))+M(Zj({id:N(""+(a.Rr!=a.Sv.$pa?""+a.Dd.$$a:"")),Lz:!0,zy:!0,className:zi(""+(a.Rr==a.Sv.$pa?"aQ7":"aQ9")),content:xi("Maybe")},null,c))+M(Zj({id:N(""+(a.Rr!=a.Sv.wpa?""+a.Dd.k8a:"")),Lz:!0,className:zi(""+(a.Rr==a.Sv.wpa?"aQ8":"aQ9")),content:xi("No")},null,c)));return L(b)},PFg=function(a){return L('<a href="'+ O(Ei(a.Jp+a.TI))+'" target="_blank" class='+(a.className?' "'+O(a.className)+'"':' "aU7"')+">"+M(a.ZH)+"</a>")};
var SFg=function(a){this.wd=a;var b=a.La();this.Aa=hl(b).Pc().Gb(6084);this.ha=a.Ol()};Q(SFg,wSe);SFg.prototype.ra=function(a){if(this.Aa){if(this.ha&&KJ(this.ha)[0]){var b=KJ(this.ha)[0];a.ZCa=ah(b,MJ,11)&&ah(b,MJ,11).getName()}!a.f0&&a.Eo&&4==a.Eo.Rr&&(a.f0="You are no longer invited to this event",a.m8="collapsed",a.RQd=!1);return qi(QFg,a)}};SFg.prototype.wa=function(a){if(this.Aa)return pi(RFg,a)};

di(K.Ma(),"ca");gi(K.Ma(),"ca");
}catch(e){_DumpException(e)}
// Google Inc.
