try{
fi(K.Ma(),"f");var DYe=function(a,b,c){c=c||{};b=!!a.S8c;return L('<div class="l2 ov"><div id="'+O(a.id.LGa)+'"></div><div id="'+O(a.id.Qpa)+'" class="aeV"></div><div class="aeU"><div id="'+O(a.id.GHa)+'"></div></div><div id="'+O(a.id.OGa)+'" class="ae3"></div><div style="'+(c.kb?"/*"+c.kb+"*/":"")+'clear: both;"></div>'+(b?'<div id="'+O(a.id.vpa)+'"></div>':"")+"</div>")},EYe=function(a,b,c){c=c||{};b=a.E3c;var d=!!a.kNb,e=a.vna,g=a.o1a,h=a.p1a,l=a.$Ca,n=a.bXa,p=!!a.rtl,w=!!a.EXa,z='<div class="md"><span class="'+
(w?"mi":"mj")+'">';a=a.Uoa?p?"You are currently using"+('<span dir="'+O(e)+'">'+(" "+(M(l)+" GB</span>."))):"You are currently using "+(M(l)+" GB."):p?"You are currently using"+('<span dir="'+O(e)+'">'+(" "+(M(l)+(' GB </span><span dir="ltr"> ('+(M(g)+(" %) </span> of your "+('<span dir="'+O(e)+'">'+(" "+(M(h)+" GB </span>."))))))))):"You are currently using "+(M(l)+(" GB ("+(M(g)+(" %) of your "+(M(h)+" GB.")))));z+=a;z+="</span>";n&&(z+='<span> &ndash; <a target="_blank" href="'+O(Ei(n))+'" class="l8">Manage</a></span>');
z+=(d?'<div class="aeZ '+(w?"ae2":"")+'"><div class="'+(w?"ae1":"ae0")+'" style="'+(c.kb?"/*"+c.kb+"*/":"")+"width: "+O(Gi(b))+'%" /></div>':"")+"</div>";return L(z)},FYe=function(a){a=a||{};var b=a.wib;a=a.vib;return L((b?'<iframe src="'+O(Ei(b))+'" class="ci"></iframe>':"")+(a?'<div class="l4">'+M(a)+"</div>":""))},IYe=function(a,b,c){b=L;if(a.iA){var d=a.CCa,e=a.V1c,g=!!a.r9c,h=a.Goa,l=a.Tma,n="";h&&(n+=GYe({link:h,content:xi("Terms of Service")},null,c)+" ");l&&(n+=(h?"- ":"")+GYe({link:l,content:xi("Privacy")},
null,c)+" ");e&&(n+=(h||l?"- ":"")+GYe({link:e,content:xi("Program Policies")},null,c)+" ");n+=d?HYe(a,null,c)+" ":"";g&&(n+='<div class="mb">',c=xi('<a target="_blank" href="https://www.google.com/"><div class="a2Z"><div class="a3I">Google</div></div></a>'),c="Powered by "+M(c),n+=c+"</div>");c=L(n)}else n=a||{},a=n.CCa,d=n.Tma,c=""+(GYe({link:n.Goa,content:xi("Terms")},null,c)+" - "+GYe({link:d,content:xi("Privacy")},null,c)+" "+(a?HYe(n,null,c)+" ":"")),c=L(c);return b('<div class="ma">'+c+"</div>")}, GYe=function(a){var b=a.content;return L('<a href="'+O(Ei(a.link))+'" target="_blank" class="l9">'+M(b)+"</a>")},HYe=function(a){a="(updated on "+(M(a.CCa)+")");return L(""+("<span>"+a+"</span>"))},JYe=function(a){return L(Ki(1,M(a.F3c)))};
var KYe=function(a){this.i1=a};r(KYe,il);KYe.prototype.ha=ol();KYe.prototype.Ua=ol();KYe.prototype.Nb=ol();var LYe=function(a){this.ha=a};r(LYe,il);var HN=function(a){Pi.call(this,a);this.Ub=tA(a);this.ra=this.Ub.iA();this.Fb=ok(a).Fb;this.Da=this.Fb.Pb("domainInfo");this.Ca=iA(this.Fb);this.getHandler().listen(this.Ub,"user:ui:udc",this.Aa);this.Fa=hl(a).Pc().Gb(6490);pl(this)};r(HN,Pi);jl(LYe,HN);HN.prototype.ha=!0;HN.prototype.wa=!0;HN.prototype.Te=function(){HN.Ea.Te.call(this);MYe(this)};
var MYe=function(a){if(a.wa&&a.ha){var b;if(a.ra){var c=a.Ca,d=a.Da;b=d.qb("tl");var e=d.qb("vl");if(d.qb("ppl")){var g=c.qb("l"),h=d.qb("pl");h&&(g=h)}c=c.qb("p");d=!!d.qb("spg");b={iA:a.ra,Goa:b,Tma:e,V1c:g,CCa:c,r9c:d}}else g=a.Ca,b=g.qb("tou"),e=g.qb("pp"),g=g.qb("p"),b={iA:a.ra,Goa:b,Tma:e,CCa:g};oi(a.Ba(),IYe,b);a.ha=!1}};HN.prototype.Aa=function(){this.ha=!0;MYe(this)};HN.prototype.nY=function(){this.wa=!1};HN.prototype.Yq=function(){this.wa=!0;MYe(this)};
var NYe=function(a){this.ra=a};r(NYe,il);NYe.prototype.ha=ml();var IN=function(a,b){Pi.call(this,a);this.Ub=tA(a);this.Fb=ok(a).Fb;this.wa=b;this.getHandler().listen(this.Ub,"user:qu:ug",this.Aa);pl(this);if(qA(this.Ub,63)&&!this.Wa.ha){debugger;delete this.Wa;pl(this)}};r(IN,Pi);jl(NYe,IN);var OYe=new Gn(1);IN.prototype.ha=!0;IN.prototype.ra=!0;IN.prototype.Te=function(){IN.Ea.Te.call(this);PYe(this)};
var PYe=function(a){if(a.ra&&a.ha){try{var b=a.Wa.ha(QYe(a))}catch(l){if(qA(a.Ub,63))debugger;throw l;}if(!b)if(a.wa)b=EYe(QYe(a));else{var c=QYe(a),d=c.vna,e=c.o1a,g=c.p1a,h=c.$Ca,b='<div class="md '+(c.EXa?"mi":"mj")+'">';c.Uoa?(e="Using "+('<span dir="'+O(d)+'">'+(M(h)+" GB</span>")),b+='<div class="aeW">'+e+"</div>"):(c="Using "+('<span dir="'+O(d)+'">'+(M(h)+(" GB</span> of your "+('<span dir="'+O(d)+'">'+(M(g)+" GB</span>"))))),e=M(e)+"% full",b+="<div>"+e+'</div><div class="aeW">'+c+"</div>");
b=L(b+"</div>")}oi(a.Ba(),JYe,{F3c:b});a.ha=!1}};IN.prototype.Aa=function(){this.ha=!0;PYe(this)};var QYe=function(a){var b=a.Fb.Pb("quota"),c=b.qb("up"),d=b.qb("ul");return{$Ca:OYe.format(b.qb("ug")),o1a:OYe.format(c),p1a:OYe.format(b.qb("tg")),Uoa:d,EXa:!!b.qb("nq"),rtl:!1,vna:"ltr",kNb:a.wa&&!d,E3c:Math.min(100,c)}};IN.prototype.nY=function(){this.ra=!1};IN.prototype.Yq=function(){this.ra=!0;PYe(this)};
var JN=function(a){Pi.call(this,a);pl(this);this.Fb=ok(a).Fb;this.wa=this.Fb.Pb("domainInfo");this.getHandler().listen(this.wa.Kd().kc(),this.wa.Ta("cfu"),this.Ha);this.ha=new IN(a,!1);this.Da=[];this.Aa=new HN(a);this.Oe(this.ha);this.Wa.ha();this.Oe(this.Aa);this.ra&&this.Oe(this.ra)};r(JN,HD);jl(KYe,JN);var RYe={LGa:"cf",OGa:"d",vpa:"db",GHa:"pc",Qpa:"q",FWb:"rc",vId:"tip",pKd:"vl"};JN.prototype.Ca=!0;JN.prototype.Te=function(){var a={id:this.Ce(RYe),S8c:!!this.ra};this.yb=qi(DYe,a,null,this.Ka())};
var SYe=function(a){var b=a.wa.qb("cfh");return{wib:a.wa.qb("cfu"),vib:b}};JN.prototype.nY=function(){this.Fa=!1;this.ha.nY();this.Aa.nY()};JN.prototype.Yq=function(){this.Fa=!0;this.ha.Yq();this.Aa.Yq();TYe(this)};JN.prototype.Ha=function(){this.Ca=!0;TYe(this)};var TYe=function(a){if(a.jd()&&a.Fa&&a.Ca){oi(a.Ba(RYe.LGa),FYe,SYe(a));var b=SYe(a);I(a.Ba(RYe.LGa),!Ma(b.vib)||!Ma(b.wib));a.Ca=!1}};
JN.prototype.Ua=function(){this.Ba(RYe.Qpa).appendChild(this.ha.Ba());this.ra&&this.Ba(RYe.vpa).appendChild(this.ra.Ba());var a=this.Ba(RYe.OGa);t(this.Da,function(b){a.appendChild(b.Ba())});this.Ba(RYe.GHa).appendChild(this.Aa.Ba());JN.Ea.Ua.call(this);this.Wa.Ua();this.Yq()};JN.prototype.Nb=function(){JN.Ea.Nb.call(this);this.Wa.Nb()};
var UYe=function(a,b,c){b=a.mRc;var d=a.S7;a=""+('<div class="l6"><div>'+M(a.GBc)+"</div>"+(b?M(b)+" &nbsp;":"")+M(hE({id:d,kf:N("Details"),className:N("l8 ou")},null,c))+"</div>");return L(a)};var VYe=function(a){Pi.call(this,a);this.Fb=ok(a).Fb};r(VYe,Pi);f=VYe.prototype;f.Te=function(){VYe.Ea.Te.call(this);this.jr()};f.Ua=function(){VYe.Ea.Ua.call(this);Ng(this.getHandler(),this.Ba(),ym,this.$Kc);this.getHandler().listen(this.Fb.kc(),"$root/lastActivity",this.iwb)};f.Nb=function(){this.getHandler().ha(this.Fb.kc(),"$root/lastActivity",this.iwb);VYe.Ea.Nb.call(this)};f.$Kc=function(a){a.target.id==this.hb("ld")&&vFe(tFe(),this.getContext())};f.iwb=function(){this.jr()};
f.jr=function(){var a=this.Fb.Pb("lastActivity",!0);if(a.wa){var b=null,c=a.qb("na");0<c?1<c?(b="Currently being used in "+(M(c)+" other locations"),b=L(""+('<span class="l7">'+b+"</span>"))):(a.qb("la"),b=L('<span class="l7">Currently being used in 1 other location</span>')):(c=a.qb("no"),0<c&&(1<c?(b="Open in "+(M(c)+" other locations"),b=L(""+b)):(a.qb("lo"),b=L("Open in 1 other location"))));var c=a.qb("l"),d=a.qb("d"),e;e=a.qb("at");e=NC(1E3*e);a={FBc:d,hwb:e,OAc:c==a.qb("lt"),HBc:c};if(a.hwb){c=
a;d=!!c.OAc;e=c.hwb;var g=c.HBc,h=c.PQd,a="",c=c.MPd?"Last account activity: "+(M(e)+" on this computer"):h?d?"Last account activity: "+(M(e)+(" at this IP ("+(M(g)+")"))):"Last account activity: "+(M(e)+(" at IP "+M(g))):"Last account activity: "+M(e),a=a+c,a=L(a)}else a="Last account activity: "+M(a.FBc),a=L(""+a);a={mRc:b,GBc:a,S7:this.hb("ld")};oi(this.Ba(),UYe,a)}};
var WYe=function(a){v.call(this);this.Oa=a};r(WYe,v);WYe.prototype.ha=function(a){return new JN(a)};WYe.prototype.ra=function(){return this.ha(this.Oa)};WYe.prototype.wa=function(){return{quota:new IN(this.Oa,!0),lastact:new VYe(this.Oa),policy:new HN(this.Oa)}};
var XYe=function(){v.call(this)};r(XYe,Yh);$h(ai(K.Ma(),"f"),XYe);XYe.prototype.Zc=function(a){rj(a,roa,YYe)};var YYe=function(a){return new WYe(a)};

var $Ye=function(a){this.i1=a;this.Oa=a.La()};Q($Ye,KYe,3);$Ye.prototype.ha=function(){this.ra=new VYe(this.Oa);var a=this.i1,b=this.ra;a.Oe(b);a.Da.push(b)};
var aZe=function(a){this.ra=a;this.Ub=tA(a.La())};Q(aZe,NYe);
aZe.prototype.ha=function(a){a.bXa=this.Ub.getData("pi:msu");if(a.kNb)a=EYe(a);else{var b='<div class="md '+(a.EXa?"mi":"mj")+'"><div>',c=a.Uoa?"Using "+('<span dir="'+O(a.vna)+'">'+(M(a.$Ca)+" GB</span>")):'<span dir="'+O(a.vna)+'">'+(M(a.$Ca)+(" GB</span> ("+(M(a.o1a)+("%) of "+('<span dir="'+O(a.vna)+'">'+(M(a.p1a)+" GB</span> used")))))),b=b+c,b=b+"</div>";a.bXa&&(b+='<div class="aeW"><a target="_blank" href="'+O(Ei(a.bXa))+'" class="l8">Manage</a></div>');a=L(b+"</div>")}return a};

di(K.Ma(),"f");gi(K.Ma(),"f");
}catch(e){_DumpException(e)}
// Google Inc.
