try{
var qXe=function(a){a=a.Fb.Pb("domainInfo").qb("dots");return void 0==a?!0:!!a},rXe=function(){return L(M(Li(1,"Google+")))},sXe=function(a){if(!a)return!1;a=a.toLowerCase();return"gmail.com"==a||"googlemail.com"==a},tXe=/\./g,uXe=function(a,b,c){if(!a&&!b)return!0;if(!a||!b)return!1;var d=eA(a.toLowerCase(),"@");a=d[0].toLowerCase();var e=d[1].toLowerCase(),d=eA(b.toLowerCase(),"@");b=d[0];d=d[1];if(!(e==d||sXe(e)&&sXe(d)))return!1;a=eA(a,"+")[0];c&&(a=a.replace(tXe,""));b=eA(b,"+")[0];c&&(b=b.replace(tXe,
""));return a==b},vXe=function(a,b,c,d){this.ha=a;this.ra=b;this.wa=c;this.yb=d||null;this.Ga=null},yN=function(a,b,c,d,e,g,h,l,n,p,w){y.call(this,a);this.ra=b;this.wa=c;this.jq=d;this.ha=e;this.Aa=g;this.clientX=h;this.clientY=l;this.Ca=n;this.Da=p;this.Ga=w};r(yN,y);
var wXe=function(a){for(var b=a.cloneNode(!0),c=Ke("TEXTAREA",a),d=Ke("TEXTAREA",b),e=0;e<c.length;e++)d[e].value=c[e].value;switch(a.tagName){case "TR":return Te("TABLE",null,Te("TBODY",null,b));case "TD":case "TH":return Te("TABLE",null,Te("TBODY",null,Te("TR",null,b)));case "TEXTAREA":b.value=a.value;default:return b}},zN=function(a,b){A.call(this);this.element=Je(a);this.data=b;this.Dh=null;this.Pa=new B(this);this.Ya(this.Pa);this.Fa=null;if(!this.element)throw Error("$d");};r(zN,A);
zN.prototype.getData=function(){return this.data};zN.prototype.Ra=function(a){if(ud(a)){var b=a.target;b&&xXe(this,a,b)}};zN.prototype.Xf=function(a){this.Dh=a};var xXe=function(a,b,c){a.Pa.listen(c,"mousemove",a.Va,!1).listen(c,"mouseout",a.Va,!1);a.Pa.listen(He(c),"mouseup",a.Rb,!0);a.Fa=c;a.Ha=new Ae(b.clientX,b.clientY)};
zN.prototype.Va=function(a){var b=this.Fa,b="mouseout"==a.type&&a.target==b;if(5<Math.abs(a.clientX-this.Ha.x)+Math.abs(a.clientY-this.Ha.y)||b)this.Pa.removeAll(),this.Dh.l2(a,this);a.preventDefault()};zN.prototype.Rb=function(){this.Pa.removeAll();delete this.Ha;this.Fa=null};var AN=function(){A.call(this);this.ek=[];this.Fz=[];this.Qa=[];this.Kc=this.Sd=this.kd=!1};r(AN,A);AN.prototype.jl=function(){return this.Kc};var BN=function(a,b){a.Fz.push(b);b.Sd=!0;a.kd=!0};
AN.prototype.init=function(){if(!this.Kc){for(var a,b=0;a=this.ek[b];b++)this.tja(a);this.Kc=!0}};AN.prototype.tja=function(a){this.kd&&(wd(a.element,"mousedown",a.Ra,!1,a),this.Ne&&P(a.element,this.Ne));this.Sd&&this.ef&&P(a.element,this.ef)};AN.prototype.mga=function(a){this.kd&&(Ad(a.element,"mousedown",a.Ra,!1,a),this.Ne&&Wi(a.element,this.Ne));this.Sd&&this.ef&&Wi(a.element,this.ef);a.dispose()};var CN=function(a){for(var b,c=0;b=a.ek[c];c++)a.mga(b);a.ek.length=0};
AN.prototype.l2=function(a,b){if(!this.Aa)if(this.Aa=b,0==this.dispatchEvent(new yN("dragstart",this,this.Aa)))this.Aa=null;else{var c=b.Fa;this.Ha=this.iMa(c);var d=He(c);d.body.appendChild(this.Ha);this.Ff=this.Hhb(c,this.Ha,a);this.Ff.Ra=this.Xc;wd(this.Ff,"drag",this.cyb,!1,this);wd(this.Ff,"end",this.LW,!1,this);wd(d.body,"selectstart",this.yOb);yXe(this);this.N4();this.Fa=null;for(d=0;c=this.Qa[d];d++)wd(c.yb,"scroll",this.Og,!1,this);this.Ff.wa(a);a.preventDefault()}};
var yXe=function(a){a.nb=[];for(var b,c=0;b=a.Fz[c];c++)for(var d,e=0;d=b.ek[e];e++)for(var g=a,h=b,l=[d.element],n=0;n<l.length;n++){var p=l[n],w,z=p;w=uh(z);z=Gh(z);w=new jh(w.y,w.x+z.width,w.y+z.height,w.x);g.nb.push(new vXe(w,h,d,p));zXe(g,w)}a.Ra||(a.Ra=new jh(0,0,0,0))};f=AN.prototype;
f.N4=function(){var a,b,c,d;for(b=0;a=this.Qa[b];b++)a.ha=[],a.wa=a.yb.scrollLeft,a.Ga=a.yb.scrollTop,c=uh(a.yb),d=Gh(a.yb),a.ra=new jh(c.y,c.x+d.width,c.y+d.height,c.x);for(b=0;d=this.nb[b];b++)for(c=0;a=this.Qa[c];c++)mf(a.yb,d.yb)&&(a.ha.push(d),d.Ga=a)};f.Hhb=function(a,b,c){a=this.EPa(a,b,c);b.style.position="absolute";b.style.left=a.x+"px";b.style.top=a.y+"px";return new Mm(b)};
f.LW=function(a){var b=a.wa?null:this.Fa;if(b&&b.ra){var c=a.clientX;a=a.clientY;var d=Df(Ie(this.Ha)),e=c+d.x,d=a+d.y,g;this.Xa&&(g=this.Xa(b.wa,b.ha,e,d));this.dispatchEvent(new yN("drag",this,this.Aa,b.ra,b.wa,b.yb,c,a,e,d));b.ra.dispatchEvent(new yN("drop",this,this.Aa,b.ra,b.wa,b.yb,c,a,e,d,g))}this.dispatchEvent(new yN("dragend",this,this.Aa,b?b.ra:void 0,b?b.wa:void 0,b?b.yb:void 0));Ad(this.Ff,"drag",this.cyb,!1,this);Ad(this.Ff,"end",this.LW,!1,this);Ad(He(this.Aa.Fa).body,"selectstart",
this.yOb);this.Gbb(this.Fa?this.Fa.wa:null)};f.Gbb=function(){this.lga()};f.lga=function(){AXe(this);this.Ff.dispose();$e(this.Ha);delete this.Aa;delete this.Ha;delete this.Ff;delete this.nb;delete this.Fa};
f.cyb=function(a){var b=this.qg(a),c=b.x,d=b.y,e=this.Fa;this.dispatchEvent(new yN("drag",this,this.Aa,e?e.ra:void 0,e?e.wa:void 0,e?e.yb:void 0,a.clientX,a.clientY,c,d));var g;if(e){this.Xa&&e.ra&&(g=this.Xa(e.wa,e.ha,c,d));if(e.ha.contains(b)&&g==this.Of)return;e.ra&&(this.dispatchEvent(new yN("dragout",this,this.Aa,e.ra,e.wa,e.yb)),e.ra.dispatchEvent(new yN("dragout",this,this.Aa,e.ra,e.wa,e.yb,void 0,void 0,void 0,void 0,this.Of)));this.Of=g;this.Fa=null}if(this.Ra.contains(b)){a:{for(var h=0;e=
this.nb[h];h++)if(e.ha.contains(b))if(e.Ga){if(e.Ga.ra.contains(b)){b=e;break a}}else{b=e;break a}b=null}if((e=this.Fa=b)&&e.ra)this.Xa&&(g=this.Xa(e.wa,e.ha,c,d)),c=new yN("dragover",this,this.Aa,e.ra,e.wa,e.yb),c.Ga=g,this.dispatchEvent(c),e.ra.dispatchEvent(new yN("dragover",this,this.Aa,e.ra,e.wa,e.yb,a.clientX,a.clientY,void 0,void 0,g));else if(!e){this.Da||(this.Da=new vXe(this.Ra.clone()));a=this.Da.ha;a.top=this.Ra.top;a.right=this.Ra.right;a.bottom=this.Ra.bottom;a.left=this.Ra.left;for(g=
0;e=this.nb[g];g++)b=e.ha,e.Ga&&(e=e.Ga.ra,b=new jh(Math.max(b.top,e.top),Math.min(b.right,e.right),Math.min(b.bottom,e.bottom),Math.max(b.left,e.left))),e=null,c>=b.right?e=b.right>a.left?b.right:a.left:c<b.left&&(e=b.left<a.right?b.left:a.right),h=null,d>=b.bottom?h=b.bottom>a.top?b.bottom:a.top:d<b.top&&(h=b.top<a.bottom?b.top:a.bottom),null===e||null===h||(Math.abs(e-c)>Math.abs(h-d)?h=null:e=null),null!==e?e<=c?a.left=e:a.right=e:null!==h&&(h<=d?a.top=h:a.bottom=h);this.Fa=10<=(a.right-a.left)*
(a.bottom-a.top)?this.Da:null}}};f.yOb=function(){return!1};var AXe=function(a){for(var b=0,c;c=a.Qa[b];b++)Ad(c.yb,"scroll",a.Og,!1,a),c.ha=[]};
AN.prototype.Og=function(a){for(var b=0,c;c=this.Qa[b];b++)if(a.target==c.yb){var d=c.Ga-c.yb.scrollTop,e=c.wa-c.yb.scrollLeft;c.Ga=c.yb.scrollTop;c.wa=c.yb.scrollLeft;this.Da&&this.Fa==this.Da&&(0<d?this.Da.ha.top+=d:this.Da.ha.bottom+=d,0<e?this.Da.ha.left+=e:this.Da.ha.right+=e);for(var g=0,h;h=c.ha[g];g++)h=h.ha,h.top+=d,h.left+=e,h.bottom+=d,h.right+=e,zXe(this,h)}this.Ff.Xa(a)};AN.prototype.iMa=function(a){a=wXe(a);this.Qf&&P(a,this.Qf);return a};
AN.prototype.EPa=function(a){var b=uh(a);a=Rh(a);b.x-=2*(a.left||0);b.y-=2*(a.top||0);return b};var zXe=function(a,b){if(1==a.nb.length)a.Ra=new jh(b.top,b.right,b.bottom,b.left);else{var c=a.Ra;c.left=Math.min(b.left,c.left);c.right=Math.max(b.right,c.right);c.top=Math.min(b.top,c.top);c.bottom=Math.max(b.bottom,c.bottom)}};AN.prototype.qg=function(a){var b=Df(Ie(this.Ha));return new Ae(a.clientX+b.x,a.clientY+b.y)};AN.prototype.Sa=function(){AN.Ea.Sa.call(this);CN(this)};fi(K.Ma(),"sy421");
var BXe=function(a,b,c){TA.call(this,a,116,c);this.Fb=ok(a).Fb;this.ha=b;this.Aa=!0};r(BXe,TA);BXe.prototype.Dl=function(){return"Show/hide all labels"};BXe.prototype.Rh=function(){return UA(this,0==this.ha?"All labels are hidden.":4==this.ha?"Labels will be shown whenever they have unread messages.":"All labels are shown.",6560)};BXe.prototype.Sc=function(a){BXe.Ea.Sc.call(this,a);ul(a,"fcn",this.ha)}; BXe.prototype.rna=function(){for(var a=this.Fb.Pb("labels").Pb("custom").getChildren().zc(),b=0;b<a.length;b++){var c=a[b];ZA(c)||c.get().q5(this.ha)}};
var CXe=function(a,b,c){TA.call(this,a,116,c);this.Fb=ok(a).Fb;this.ha=b;this.Aa=!0};r(CXe,TA);CXe.prototype.Dl=function(){return"Show/hide all labels in message list"};CXe.prototype.Rh=function(){return UA(this,this.ha?"All labels are now shown in the message list.":"All labels are now hidden in the message list.",6560)};CXe.prototype.Sc=function(a){CXe.Ea.Sc.call(this,a);ul(a,"mcn",this.ha?"1":"0")}; CXe.prototype.rna=function(){for(var a=this.Fb.Pb("labels").Pb("custom").getChildren().zc(),b=0;b<a.length;b++){var c=a[b];if(!ZA(c)){var c=c.get(),d=this.ha;d!=c.wa&&(c.wa=d,c.onChange(8))}}};
var DN=function(a,b,c,d){TA.call(this,a,b,d);this.Ta=c};r(DN,TA);DN.prototype.Sk=function(){return!0};DN.prototype.Rh=function(){return this.Da};DN.prototype.Sc=function(a){DN.Ea.Sc.call(this,a);ul(a,"act",this.cM+this.Ta)};var DXe=function(a,b,c){DN.call(this,a,52,b,c)};r(DXe,DN);DXe.prototype.Dl=function(){return"Create label"};var EXe=function(a,b,c,d,e){TA.call(this,a,65,d);this.ha=b;this.wa=c;this.Ta=e||null};r(EXe,TA);EXe.prototype.Dl=function(){return"Change label color"};EXe.prototype.hs=function(){return this.wa};EXe.prototype.Rh=function(){var a;-1==this.wa?(a=this.ha.length,a=1<a?"The color of "+(a+" labels were cleared."):'The color for label "'+(this.Ta+'" was cleared.')):(a=this.ha.length,a=1<a?"The color of "+(a+" labels were adjusted."):'The color for label "'+(this.Ta+'" was adjusted.'));return UA(this,a)}; EXe.prototype.Sc=function(a){EXe.Ea.Sc.call(this,a);vl(a,"ecn",this.ha);ul(a,"c4",this.wa)};
var FXe=function(a,b,c){TA.call(this,a,53,c);this.Ai=b};r(FXe,TA);f=FXe.prototype;f.Dl=function(){return"Remove label"};f.Sc=function(a){FXe.Ea.Sc.call(this,a);vl(a,"ecn",this.Ai)};f.Sk=function(){return!0};f.Rh=function(){return this.Da};f.getLabels=function(){return this.Ai};
var GXe=function(a,b,c,d){TA.call(this,a,54,d);this.fwb=b;this.tyb=c};r(GXe,TA);GXe.prototype.Sc=function(a){GXe.Ea.Sc.call(this,a);vl(a,"ecn",this.fwb);vl(a,"nct",this.tyb)};GXe.prototype.Dl=function(){return"Rename label"};GXe.prototype.Sk=function(){return!0};GXe.prototype.Rh=function(){return this.Da};
var HXe=function(a,b,c){c=c||{};b='<div class="xy asN">';b=0<a.A7?b+"The following labels will be removed from your messages and then deleted. No messages will be deleted.":b+"The following labels will be deleted.";b+='</div><div class="ajL"><div class="ajQ" id="'+O(a.ABc)+'" style="'+(c.kb?"/*"+c.kb+"*/":"")+"max-height: "+O(Gi(a.$Cc))+'px;"><ul class="ajN">';for(var d=a.labels,e=d.length,g=0;g<e;g++){var h=d[g];b+='<li class="OpuOab"><span class="ajP" style="'+(c.kb?"/*"+c.kb+"*//*"+c.kb+"*/":"")+
"margin-left:"+O(Gi(a.yzc*h.level))+'px">'+M(h.QBc)+'</span><span class="ajO">';1==h.A7?b=a.jj?b+"(1 message)":b+"(1 conversation)":1<h.A7&&(h=a.jj?"("+(M(h.A7)+"&nbsp;messages)"):"("+(M(h.A7)+"&nbsp;conversations)"),b+=h);b+="</span></li>"}return L(b+"</ul></div></div>")};
var JXe=function(a,b,c){var d=a.La().Ag();UC.call(this,d);this.Dp=a;this.ra=c;this.ha=b;this.Fa=tB(d).jj();this.setTitle("Remove Labels");IXe(this);Ym(this,(new Vm).Hf({key:"ok",caption:"Delete"},!1).Hf($m,!0,!0));this.getHandler().listen(this,"dialogselect",this.Ha)};r(JXe,UC);
var IXe=function(a){var b=0,c=a.ha.pH(a.ra[0].getId()),d=!0,e=lb(a.ra,function(a){b+=a.ra;var e;d?(e=DLd(a),d=!1):e=RB(this.ha.qH(a.getId())||a.getMessage());return{A7:a.ra,level:this.ha.pH(a.getId())-c,QBc:e}},a),e=HXe({yzc:12,$Cc:250,A7:b,ABc:a.hb("lr"),labels:e,jj:a.Fa});VC(a,e)};JXe.prototype.setVisible=function(a){JXe.Ea.setVisible.call(this,a);a&&(a=this.Vb("lr"),250<a.scrollHeight&&qn(a,"ajM"))};JXe.prototype.Ha=function(a){"ok"==a.key&&this.Dp.Ga(lb(this.ra,function(a){return a.getId()}))};
var EN=function(a,b){this.Oa=a;this.ha=b;this.Ae=zB(a);this.Aa=DB(a);this.ra=dC(a);this.wa=SC(FB(this.Aa))};f=EN.prototype;f.X6c=function(a){iC(this.Oa,wNd);a=new BXe(this.Oa,a,this.ha);oB(this.ra,a);a.send()};f.Y6c=function(a){iC(this.Oa,wNd);a=new CXe(this.Oa,a,this.ha);oB(this.ra,a);a.send()};f.l4a=function(a){var b=this;o3d(this.Oa,function(c){b.YBa(c);a&&a.call(b,c)},null)};f.YBa=function(a){iC(this.Oa,rNd);a=new DXe(this.Oa,a,this.ha);oB(this.ra,a);a.send()};
f.FJb=function(a,b){var c=a.getId(),d=xLd(this.wa,c),e=[],g=[];KXe(c,b,d,e,g);iC(this.Oa,sNd);c=new GXe(this.Oa,e,g,this.ha);oB(this.ra,c);c.send()};var KXe=function(a,b,c,d,e){var g=new Uc;g.set(a,b);Yc(c,function(c){c=c.getId();d.push(c);if(a==c)e.push(b);else{var h=vKd(g,c)||a,n=uKd(h,c),h=g.get(h),n=tKd(h,n);e.push(n);g.set(c,n)}})};
EN.prototype.Rv=function(a){var b=xLd(this.wa,a.getId());if(1>=b.length){var c=a.ra,b=new jF(m(this.Ga,this,[a.getId()]),this.Oa.Ag(),"Remove Label");a={message:a.getMessage(),l8c:DLd(a),count:c,mbc:Sl(c)};c='<span title="'+O(a.message)+'">'+M(a.l8c)+"</span>";c=xi(c);a=In(new Hn('{COUNT,plural,=0{Delete the label {START_BOLD}"{LABEL}"{END_BOLD}?}=1{Remove the label {START_BOLD}"{LABEL}"{END_BOLD} from 1 conversation and delete the label?}other{Remove the label {START_BOLD}"{LABEL}"{END_BOLD} from {COUNT_STRING} conversations and delete the label?}}'),
{COUNT:a.count,START_BOLD:"<b>",LABEL:M(c),END_BOLD:"</b>",COUNT_STRING:M(a.mbc)});a=L(""+a);Sm(b,a.Df());Ym(b,(new Vm).Hf({key:"ok",caption:"Delete"},!1).Hf($m,!0,!0));b.setVisible(!0)}else(new JXe(this,this.wa,b)).setVisible(!0)};EN.prototype.Ga=function(a){iC(this.Oa,uNd);a=new FXe(this.Oa,a,this.ha);oB(this.ra,a);a.send()};EN.prototype.Ca=function(a,b,c,d){a=kb(d?a:[a[0]],function(a){return a.eW()!=b});0<a.length&&LXe(this,a,b,c)}; var LXe=function(a,b,c,d){c=c?c:-1;iC(a.Oa,tNd);b=new EXe(a.Oa,lb(b,function(a){return a.getId()}),c,a.ha,b[0].getMessage());oB(a.ra,b);b.send();d&&d()};EN.prototype.La=function(){return this.Oa};

di(K.Ma(),"sy421");gi(K.Ma(),"sy421");
}catch(e){_DumpException(e)}
try{
var bZe=function(a,b){try{return Xb(a).next()}catch(c){if(c!=Vb)throw c;return b}};fi(K.Ma(),"sy423");var KN=function(){};r(KN,Hj);ta(KN);var cZe=0;KN.prototype.Na=function(a){var b=this.Uq(a);a=a.Ka().Na("DIV",b?b.join(" "):null,dZe(this,a.getContent(),a.Rd(),a.Ka()));wj(a,"grid");return a};var dZe=function(a,b,c,d){for(var e=[],g=0,h=0;g<c.height;g++){for(var l=[],n=0;n<c.width;n++){var p=b&&b[h++];l.push(eZe(a,p,d))}e.push(a.ha(l,d))}return a.cB(e,d)};KN.prototype.cB=function(a,b){var c=b.Na("TABLE",this.Ac()+"-KW",b.Na("TBODY",this.Ac()+"-atU",a));c.cellSpacing="0";c.cellPadding="0";return c};
KN.prototype.ha=function(a,b){var c=b.Na("TR",this.Ac()+"-axF",a);wj(c,"row");return c};var eZe=function(a,b,c){a=c.Na("TD",{"class":a.Ac()+"-Jn",id:a.Ac()+"-Jn"+cZe++},b);wj(a,"gridcell");xj(a,"selected",!1);if(!uf(a)&&!Aj(a)){var d;b=new ko(a);for(c="";!c&&(d=bZe(b,null));)1==d.nodeType&&(c=Aj(d)||d.title);(d=c)&&Bj(a,d)}return a};KN.prototype.ul=function(){return!1};KN.prototype.Tb=function(){return null};
KN.prototype.setContent=function(a,b){if(a){var c=Le("TBODY",this.Ac()+"-atU",a)[0];if(c){var d=0;t(c.rows,function(a){t(a.cells,function(a){We(a);if(b){var c=b[d++];c&&a.appendChild(c)}})});if(d<b.length){for(var e=[],g=Ie(a),h=c.rows[0].cells.length;d<b.length;){var l=b[d++];e.push(eZe(this,l,g));e.length==h&&(l=this.ha(e,g),c.appendChild(l),e.length=0)}if(0<e.length){for(;e.length<h;)e.push(eZe(this,"",g));l=this.ha(e,g);c.appendChild(l)}}}Nh(a,!0,dd)}}; var fZe=function(a,b,c){for(b=b.Ba();c&&1==c.nodeType&&c!=b;){if("TD"==c.tagName&&Ui(c,a.Ac()+"-Jn"))return c.firstChild;c=c.parentNode}return null};KN.prototype.Ac=function(){return"J-Kw"};
var LN=function(a,b,c){Lj.call(this,a,b||KN.Ma(),c);Tj(this,88,!1);this.ha=new gZe;this.ha.Mf(this);this.Qa=-1};r(LN,Lj);f=LN.prototype;f.AH=null;f.DN=-1;f.Se=null;f.Sa=function(){LN.Ea.Sa.call(this);this.Se&&(this.Se.dispose(),this.Se=null);this.AH=null;this.ha.dispose()};f.uca=function(a){LN.Ea.uca.call(this,a);hZe(this);this.Se?(this.Se.clear(),cra(this.Se,a)):(this.Se=new xm(a),a=m(this.Ta,this),this.Se.wa=a,this.getHandler().listen(this.Se,"select",this.uK));this.DN=-1};f.vm=function(){return""};
f.or=function(){};f.Du=function(a){LN.Ea.Du.call(this,a);var b=fZe(this.Ue(),this,a.target);b&&a.relatedTarget&&mf(b,a.relatedTarget)||b!=iZe(this)&&jZe(this,b)};f.Wo=function(a){LN.Ea.Wo.call(this,a);this.Gb()&&(a=fZe(this.Ue(),this,a.target),a!=iZe(this)&&jZe(this,a))};f.qo=function(a){var b=iZe(this);return b?(a&&(this.Ch()?"mouseup"!=a.type||fZe(this.Ue(),this,a.target):1)&&this.Hj(b),LN.Ea.qo.call(this,a)):!1};
f.Jj=function(a){var b=this.getContent(),b=b?b.length:0,c=this.AH.width;if(0==b||!this.isEnabled())return!1;if(13==a.keyCode||32==a.keyCode)return this.qo(a);if(36==a.keyCode)return this.Om(0),!0;if(35==a.keyCode)return this.Om(b-1),!0;var d=0>this.DN?this.So():this.DN;switch(a.keyCode){case 37:if(-1==d||0==d)d=b;this.Om(d-1);a.preventDefault();return!0;case 39:return d==b-1&&(d=-1),this.Om(d+1),a.preventDefault(),!0;case 38:-1==d&&(d=b+c-1);if(d>=c)return this.Om(d-c),a.preventDefault(),!0;break;
case 40:if(-1==d&&(d=-c),d<b-c)return this.Om(d+c),a.preventDefault(),!0}return!1};f.uK=function(){};f.Rd=function(){return this.AH};var MN=function(a,b,c){if(a.Ba())throw Error("Ga");a.AH=za(b)?new Be(b,c):b;hZe(a)};LN.prototype.wx=function(){return this.DN};var iZe=function(a){var b=a.getContent();return b&&b[a.DN]};LN.prototype.Om=function(a){a!=this.DN&&(kZe(this,this.DN,!1),this.Qa=this.DN,this.DN=a,kZe(this,a,!0),this.dispatchEvent("Pe"))};
var jZe=function(a,b){var c=a.getContent();a.Om(c&&b?ib(c,b):-1)};LN.prototype.So=function(){return this.Se?this.Se.So():-1};LN.prototype.Ch=function(){return this.Se?this.Se.Ch():null};LN.prototype.Nj=function(a){this.Se&&this.Se.Nj(a)};LN.prototype.Hj=function(a){this.Se&&this.Se.Hj(a)};
var kZe=function(a,b,c){if(a.Ba()){var d=a.getContent();if(d&&0<=b&&b<d.length){var e;e=(e=iZe(a))?e.parentNode:null;a.ha.Ba()!=e&&a.ha.Qd(e);e=a.ha;e.Dn(c);Qj(e,2)==c&&(e=a.Ue(),b=d[b])&&(b=b?b.parentNode:null,Yi(b,e.Ac()+"-Jn-JW",c),c?xj(a.yb,"activedescendant",b.id):b.id==zj(a.yb,"activedescendant")&&yj(a.yb,"activedescendant"))}}};LN.prototype.Dn=function(a){a&&-1==this.DN?this.Om(-1<this.Qa?this.Qa:0):a||this.Om(-1);LN.Ea.Dn.call(this,a)};
LN.prototype.Ta=function(a,b){if(this.Ba()&&a){var c=a.parentNode;Yi(c,this.Ue().Ac()+"-Jn-KO",b);xj(c,"selected",b)}};var hZe=function(a){var b=a.getContent();if(b)if(a.AH&&a.AH.width){if(b=Math.ceil(b.length/a.AH.width),!za(a.AH.height)||a.AH.height<b)a.AH.height=b}else b=Math.ceil(Math.sqrt(b.length)),a.AH=new Be(b,b);else a.AH=new Be(0,0)},gZe=function(){Lj.call(this,null);Uj(this,2,!0)};r(gZe,Lj);
var NN=function(a,b,c){this.ra=a||[];LN.call(this,null,b||KN.Ma(),c);lZe(this,this.ra)};r(NN,LN);NN.prototype.Ja=null;NN.prototype.Ai=null;var lZe=function(a,b,c){a.ra=b;a.Ai=c||null;a.Ja=null;a.setContent(mZe(a))};NN.prototype.hK=function(){var a=this.Ch();return a?(a=nh(a,"background-color"),nZe(a)):null};NN.prototype.vI=function(a){a=nZe(a);this.Ja||(this.Ja=lb(this.ra,function(a){return nZe(a)}));this.Nj(a?ib(this.Ja,a):-1)};
var mZe=function(a){return lb(a.ra,function(a,c){var b=this.Ka().Na("DIV",{"class":this.Ue().Ac()+"-Jt",style:"background-color:"+a}),e;this.Ai&&this.Ai[c]?e=this.Ai[c]:"#"==a.charAt(0)?(e=hsa(a),e="RGB ("+[parseInt(e.substr(1,2),16),parseInt(e.substr(3,2),16),parseInt(e.substr(5,2),16)].join(", ")+")"):e=a;b.title=e;return b},a)},nZe=function(a){if(a)try{return en(a).OR}catch(b){}return null};

di(K.Ma(),"sy423");gi(K.Ma(),"sy423");
}catch(e){_DumpException(e)}
try{
fi(K.Ma(),"sy424");var pZe=function(a){v.call(this);this.ha=a;this.Pa=new B(this);this.Pa.listen(a,"highlight",this.YJc);this.Pa.listen(a,"enter",this.Cnc);this.Pa.listen(a,"aftershow",this.Bnc);this.Pa.listen(a,"hide",this.Dnc);oZe(this,!0)};r(pZe,v);f=pZe.prototype;f.ska=null;f.z2a=null;f.ZMa=!1;f.Cnc=function(a){this.ZMa?a.preventDefault():this.ska=a.target};f.YJc=function(){oZe(this)};f.Bnc=function(){null!=this.z2a?(this.ha.Ba().scrollTop=this.z2a,oZe(this,!1)):oZe(this,!0)};
f.Dnc=function(a){a.target==this.ha&&(this.ska=null,this.z2a=this.ha.Ba().scrollTop)};var oZe=function(a,b){var c=a.ha.Po();if(a.ha.$b()&&c&&c!=a.ska){var d=a.ha.Ba();yh(c.Ba(),d,b);qZe(a);a.ska=null}},qZe=function(a){a.ZMa=!0;Td(function(){this.ZMa=!1},0,a)};pZe.prototype.Sa=function(){pZe.Ea.Sa.call(this);this.Pa.dispose();this.ska=null};

di(K.Ma(),"sy424");gi(K.Ma(),"sy424");
}catch(e){_DumpException(e)}
try{
var rZe=function(a,b,c){UC.call(this,a);this.Oa=a;this.ra=b;this.ha=c;this.setTitle("Changing color on multiple labels");a={QIb:this.hb("radio"),SBb:this.hb("lbl"),nOb:this.hb("sub"),gz:this.ra[0].getMessage()};b="";c='Label <b>"'+(M(a.gz)+'"</b> and its sublabels</label>');var d='Only label <b>"'+(M(a.gz)+'"</b>');b+='<div class="ajF">Set color for:</div><div class="ajG"><input class="ajH" type="radio" name="'+O(a.QIb)+'" id="'+O(a.SBb)+'" checked><label for="'+O(a.SBb)+'">'+d+'</label></div><div class="ajG"><input class="ajH" type="radio" name="'+
O(a.QIb)+'" id="'+O(a.nOb)+'"><label for="'+O(a.nOb)+'">'+c+"</div>";a=L(b);VC(this,a);a=new Vm;a.Hf({key:"sc",caption:"Set color"},!0);a.Hf($m,!1,!0);this.getHandler().listen(this,"dialogselect",this.Fa);Ym(this,a)};r(rZe,UC);rZe.prototype.Fa=function(a){"sc"==a.key&&(a=this.Vb("sub"),this.ha(a.checked))};var sZe=function(a,b,c,d){TA.call(this,a,67,d);this.Ai=b;this.ha=c;this.Aa=!0};r(sZe,TA);sZe.prototype.Dl=function(){return"Show/hide label in message list"};
sZe.prototype.Rh=function(){var a=this.Ai[0],b=1<this.Ai.length,c=!b&&a&&a.Wq(),a=this.ha?a.Wq()&&"^cff"!=a.getId()&&!b?'The circle "'+(a.getMessage()+'" will now be shown in the message list and in messages.'):a.Wq()&&!b?'"Circles" will now be shown in the message list and in messages.':b?"The labels will now be shown in the message list.":'The label "'+(a.getMessage()+'" will now be shown in the message list.'):a.Wq()&&"^cff"!=a.getId()&&!b?'The circle "'+(a.getMessage()+'" will no longer be shown in the message list or in messages.'):
a.Wq()&&!b?'"Circles" will no longer be shown in the message list or in messages.':b?"The labels will no longer show in the message list.":'The label "'+(a.getMessage()+'" will no longer show in the message list.');return UA(this,a,c?1734792:6560)};sZe.prototype.Sc=function(a){sZe.Ea.Sc.call(this,a);var b=lb(this.Ai,function(a){return a.getName()});vl(a,"cn",b);ul(a,"mcn",this.ha?"1":"0")};
sZe.prototype.rna=function(){var a=DB(this.La());t(this.Ai,function(b){if(b=HB(a,b.getName())){var c=this.ha;c!=b.wa&&(b.wa=c,b.onChange(8))}},this)};var tZe=function(a,b,c,d){TA.call(this,a,67,d);this.Ai=b;this.ha=c;this.Aa=!0};r(tZe,TA);f=tZe.prototype;f.Dl=function(){return"Show/hide label"};
f.Rh=function(){var a=this.getLabels()[0],b=1<this.getLabels().length,c=!b&&a&&a.Wq();switch(this.ha){case 2:a=a.Wq()&&"^cff"!=a.getId()&&!b?'The circle "'+(a.getMessage()+'" will always be shown in the circle list.'):a.Wq()&&!b?'"Circles" will always be shown in the label list.':"^sl_root"==a.getId()?'"Categories" will always be shown in the label list.':QB(a)&&!b?'The category "'+(a.getMessage()+'" will always be shown in the Categories list.'):b?"The labels will always be shown in the label list.":
'The label "'+(a.getMessage()+'" will always be shown in the label list.');break;case 4:a=a.Wq()&&"^cff"!=a.getId()&&!b?'The circle "'+(a.getMessage()+'" will be shown in the circle list whenever it has unread messages.'):a.Wq()&&!b?'"Circles" will be shown in the circle list whenever it has unread messages.':b?"The labels will be shown in the label list whenever they have unread messages.":'The label "'+(a.getMessage()+'" will be shown in the label list whenever it has unread messages.');break;case 0:a=
a.Wq()&&"^cff"!=a.getId()&&!b?'The circle "'+(a.getMessage()+'" was hidden from the circle list.'):a.Wq()&&"^cff"==a.getId()?'"Circles" was hidden from the label list.':"^sl_root"==a.getId()?'The "Categories" list was hidden.':QB(a)&&!b?'The category "'+(a.getMessage()+'" was hidden from the Categories list'):b?"The labels were hidden from the label list.":'The label "'+(a.getMessage()+'" was hidden from the label list.');break;default:a=a.Wq()&&"^cff"!=a.getId()&&!b?'The circle "'+(a.getMessage()+
'" was shown.'):a.Wq()&&!b?'"Circles" was shown.':b?"The labels were shown.":'The label "'+(a.getMessage()+'" was shown.')}return UA(this,a,c?1734792:6560)};f.Sc=function(a){tZe.Ea.Sc.call(this,a);var b=lb(this.getLabels(),function(a){return a.getName()});vl(a,"cn",b);ul(a,"fcn",this.ha)};f.rna=function(){var a=DB(this.La());t(this.getLabels(),function(b){(b=HB(a,b.getName()))&&b.q5(this.ha)},this)};f.getLabels=function(){return this.Ai};
var uZe=function(a){this.ha=[];this.yb=a;this.Ga=this.wa=0;this.ra=null},vZe=function(a,b,c,d){var e=QB(b)?[b]:xLd(a.wa,b.getId());(1>=e.length?0:nb(e,function(a){return a.eW()!=c},a))?(new rZe(a.Oa.Ag()||a.Oa,e,m(a.Ca,a,e,c,d))).setVisible(!0):b.eW()!=c&&LXe(a,[b],c,d)},wZe=function(a,b){var c=QQd(a.wa,b.getId());(new gG(a.La().Ag()||a.La(),"Edit label","Label name:","Save",b,c,null,m(a.FJb,a,b))).setVisible(!0)},xZe=function(a,b,c){iC(a.Oa,vNd);b=new sZe(a.Oa,b,c,a.ha);oB(a.ra,b);b.send()},yZe=
function(a,b,c){var d;NB(b.Hd)||QB(b)||b.Wq()||b.Aa?d=wLd(b).Fa(b,c):d=xLd(a.wa,b.getId());b=d;iC(a.Oa,vNd);c=new tZe(a.Oa,b,c,a.ha);oB(a.ra,c);c.send()},zZe=function(a,b){a.Qa.push(new uZe(b))},AZe=function(a,b,c,d){b=HB(DB(a.La()),b);a.Ia==b&&NB(b.Hd)||Py(c,"nY",d)},BZe=function(a,b,c,d){hH(a,function(a){a.$Ba&&a.$Ba(b,c)},d);return b},CZe=function(a,b,c,d){hH(a,function(a){c==a instanceof OL&&a.Q9&&a.Q9(b)},d);return b},DZe=function(a,b){var c=sA(tA(a.Oa)),c=Tz(c);if(b==c)return!1;c=(c=OB(FB(a), b))?c.getParent():null;return!c||!c.Za||c.Za(b,a.Oa)},EZe=function(a){var b=a.Wa.ha();return k(b)?b:0!=CGd(a.Ec())};fi(K.Ma(),"ml");
var FZe=function(a){D(this,a,"",-1,null,null)};r(FZe,C);FZe.prototype.getUrl=function(){return E(this,1)};var ZL=function(a){v.call(this);this.Ca=YB(a);this.Aa=[];this.Ga=new Fz(18E4,a.get(fg));wd(this.Ga,"idle",this.Ra,!1,this);wd(this.Ga,"active",this.Qa,!1,this);wd(Al(a).Bj(),pz("jsurl"),this.Ha,!1,this)};r(ZL,v);ZL.prototype.Ha=function(a){this.ha||(a=(new FZe(a.data)).getUrl(),this.wa==a||0<=a.indexOf(fa)&&0<=a.indexOf(ga)||(this.ra&&(Xh(this.ra),this.ra=0),this.Da=!1,GZe(this),this.wa=a,sb(this.Aa,a)||(this.ra=Wh("of",this.Ia,Tb(72E5),this))))};ZL.prototype.Ia=function(){this.Da=!0;this.Fa&&HZe(this)};
var HZe=function(a){a.ha||(a.ha=new fe,wd(a.ha,"complete",a.Ja,!1,a),a.ha.send(a.wa))};ZL.prototype.Ja=function(){var a=!1;this.ha.Xj()?this.Ca.ha(GLa):7==this.ha.ku()?(a=!0,this.Ca.ha(ILa)):this.Ca.ha(HLa);this.ha.dispose();this.ha=null;a||this.Aa.unshift(this.wa)};ZL.prototype.Ra=function(){this.Fa=!0;this.wa&&this.Da&&!sb(this.Aa,this.wa)&&HZe(this)};ZL.prototype.Qa=function(){this.Fa=!1;GZe(this)};var GZe=function(a){a.ha&&(a.ha.abort(),a.ha&&(a.ha.dispose(),a.ha=null))}; ZL.prototype.dispose=function(){this.Ga&&(this.Ga.dispose(),this.Ga=null);this.ra&&(Xh(this.ra),this.ra=0);GZe(this)};
var THe=function(a,b){v.call(this);this.Ca=b;this.wa=new Fz(1E3,a);this.Pa=new B(this);this.Pa.listen(this.wa,"idle",this.Da)};r(THe,v);THe.prototype.ra=0;THe.prototype.Da=function(){var a=q();36E5<a-this.ra&&(this.ra=a,this.ha=new Image,this.Aa=q(),this.Pa.listen(this.ha,["load","error"],this.Ga),this.ha.src="images/cleardot.gif?zx="+db())};
THe.prototype.Ga=function(a){var b=q(),c=this.Aa;a="load"==a.type;this.Pa.ha(this.ha,["load","error"],this.Ga);this.ha.onload=null;this.ha.onerror=null;this.ha.onabort=null;delete this.ha;a&&this.Ca.ha(eDa,b-c)};THe.prototype.Sa=function(){this.Pa.dispose();this.wa.dispose()};
var IZe=function(a){a=""+('<div class="pJ"><div id="'+O(a.id)+'"></div><b>Preview Label Color</b> - <span class="pK">pick colors below.</span></div>');return L(a)},JZe=function(a){a=""+('<table cellpadding="0" class="cf RURSBc"><tr><td width="42%"><b>Background Color</b></td><td class="pL"></td><td width="42%"><b>Text Color</b></td></tr><tr><td width="42%"><div id="'+O(a.Sb.zSb)+'"></div></td><td class="pL"></td><td width="42%"><div id="'+O(a.Sb.V2b)+'"></div></td></tr></table>');return L(a)};
var MZe=function(a,b,c,d){UC.call(this,a);this.Oa=a;this.Jb=eo(a).Ka();this.Ie=dC(a);this.Fh=GA(a);this.Fa=KZe;this.Ha=b;this.Dp=c;this.Md=d;this.Xa=(b=sb(this.Fa,"#"+ALd(this.Ha))&&sb(this.Fa,"#"+zLd(this.Ha)))?"#"+ALd(this.Ha):"#999";this.Qb=b?"#"+zLd(this.Ha):"#f3f3f3";this.Xc=DB(a);this.Kc=this.Xc.ha;a=this.Jc();qn(Um(this),"pD");rf(Kx(this),"Add custom color");b=this.hb("np_clcp_lp");a.appendChild(qi(IZe,{id:b},null,this.Jb));a=this.Jb;b=new LZe;this.ra=new NN(this.Fa,b,a);MN(this.ra,8);this.ha=
new NN(this.Fa,b,a);MN(this.ha,8);this.Jc().appendChild(qi(JZe,{Sb:{zSb:"np_clcp_bcp",V2b:"np_clcp_tcp"}},null,a));c=a.Ab().getElementById("np_clcp_tcp");this.ra.render(c);c=a.Ab().getElementById("np_clcp_bcp");this.ha.render(c);a=Af(a,void 0,b.Ac()+"-Jt",this.Jc());for(b=0;4>b;b++)qn(a[b],"pC");for(b=40;64>b;b++)qn(a[b],"pC");for(b=64;68>b;b++)qn(a[b],"pC");for(b=104;128>b;b++)qn(a[b],"pC");this.ra.vI(this.Qb);this.ha.vI(this.Xa);a=this.Vb("np_clcp_lp");lA(a,MLd(this.Xc,this.Ha.getMessage(),this.Kc.hs(this.Ha)));
this.nb=Af(this.Jb,"div","at",a)[0];this.nb.style.backgroundColor=this.Xa;this.nb.style.borderColor=this.Xa;this.Wb=Af(this.Jb,"div","au",a)[0];this.Wb.style.borderColor=this.Xa;this.Ob=Af(this.Jb,"div","av",a)[0];this.Ob.style.color=this.Qb;a=(new Vm).set("np_clcp_a","Apply",!0).set("cancel","Cancel",!1,!0);Ym(this,a);XC(this);wd(this,"dialogselect",this.yc,!1,this);wd(this.ra,"action",this.Db,!1,this);wd(this.ha,"action",this.Db,!1,this)};r(MZe,UC);var KZe="#000000 #434343 #666666 #999999 #cccccc #efefef #f3f3f3 #ffffff #fb4c2f #ffad47 #fad165 #16a766 #43d692 #4a86e8 #a479e2 #f691b3 #f6c5be #ffe6c7 #fef1d1 #b9e4d0 #c6f3de #c9daf8 #e4d7f5 #fcdee8 #efa093 #ffd6a2 #fce8b3 #89d3b2 #a0eac9 #a4c2f4 #d0bcf1 #fbc8d9 #e66550 #ffbc6b #fcda83 #44b984 #68dfa9 #6d9eeb #b694e8 #f7a7c0 #cc3a21 #eaa041 #f2c960 #149e60 #3dc789 #3c78d8 #8e63ce #e07798 #ac2b16 #cf8933 #d5ae49 #0b804b #2a9c68 #285bac #653e9b #b65775 #822111 #a46a21 #aa8831 #076239 #1a764d #1c4587 #41236d #83334c".split(" ");
MZe.prototype.Sa=function(){Ad(this,"dialogselect",this.yc,!1,this);this.ra&&Ad(this.ra,"action",this.Db,!1,this);this.ha&&Ad(this.ha,"action",this.Db,!1,this);MZe.Ea.Sa.call(this)};MZe.prototype.yc=function(a){if("np_clcp_a"==a.key){a=this.ra.hK();var b=this.ha.hK();a=this.Kc.eW(a,b);null===a?(this.Fh.$r("You have created too many custom colors.  Please use an existing color."),this.dispose()):vZe(this.Dp,this.Ha,a,this.Md)}else this.dispose()};
MZe.prototype.Db=function(a){if(a.target==this.ra)this.Ob.style.color=this.ra.hK();else if(a.target==this.ha){this.nb.style.backgroundColor=this.nb.style.borderColor=this.Wb.style.borderColor=this.ha.hK();var b=this.ha.So();a=Math.floor(b/8);b%=8;a=0==a?4>b?this.Fa[7]:this.Fa[0]:5>a?this.Fa[56+b]:this.Fa[16+b];this.Ob.style.color=a;this.ra.vI(a)}};var LZe=function(){};r(LZe,KN);
LZe.prototype.Na=function(a){var b=this.Uq(a),c=a.Ka().Na("DIV",b?{"class":b.join(" ")}:null,dZe(this,Gb(a.getContent(),0,8),new Be(8,1),a.Ka())),d=a.Ka().Na("DIV",b?{"class":b.join(" ")}:null,dZe(this,Gb(a.getContent(),8,16),new Be(8,1),a.Ka())),b=a.Ka().Na("DIV",b?{"class":b.join(" ")}:null,dZe(this,Gb(a.getContent(),16),new Be(8,6),a.Ka()));a=a.Ka().Na("DIV",{"class":"pI"});a.appendChild(c);a.appendChild(d);a.appendChild(b);return a};LZe.prototype.Ac=function(){return"ajZ"};
var NZe=function(a){this.ha=a};r(NZe,il);f=NZe.prototype;f.Qxb=ol();f.pva=ml();f.yw=ll();f.updateMenuItems=ol();f.cLb=ml();f.xdb=ml();var ON=function(a,b,c){v.call(this);this.xd=a;this.Ja=b;this.Ca=DB(a);this.Ia=this.Ca.ha;this.Ha=[new BB("#464646","#e7e7e7"),new BB("#0d3472","#b6cff5"),new BB("#0d3b44","#98d7e4"),new BB("#3d188e","#e3d7ff"),new BB("#711a36","#fbd3e0"),new BB("#8a1c0a","#f2b2a8"),new BB("#7a2e0b","#ffc8af"),new BB("#7a4706","#ffdeb5"),new BB("#594c05","#fbe983"),new BB("#684e07","#fdedc1"),new BB("#0b4f30","#b3efd3"),new BB("#04502e","#a2dcc1"),new BB("#ffffff","#c2c2c2"),new BB("#ffffff","#4986e7"),new BB("#ffffff",
"#2da2bb"),new BB("#ffffff","#b99aff"),new BB("#994a64","#f691b2"),new BB("#ffffff","#fb4c2f"),new BB("#ffffff","#ff7537"),new BB("#ffffff","#ffad46"),new BB("#662e37","#ebdbde"),new BB("#ffffff","#cca6ac"),new BB("#094228","#42d692"),new BB("#ffffff","#16a765")];this.Dp=c;this.Da=new Uc;this.Za=QD(a);this.Ga={};this.Fa={};this.Va=SC(FB(this.Ca));pl(this)};r(ON,v);jl(NZe,ON);ON.prototype.gG=function(a,b){this.ha||OZe(this);this.ra=a;this.ha.kP(b,zA().je(27),zA().je(28))};
var OZe=function(a){var b=Ie(a.Ja);a.ha=new Eo(b);a.ha.Cq(!1);a.ha.Dz(!0);a.ha.render(a.Ja);qn(a.ha.Ba(),"aka");a.Ra=new pZe(a.ha);PN(a,new dm("Label color:",b),1);PZe(a,b);PN(a,a.wa,1);QZe(a,a.wa);for(var c=Le(void 0,"JA-Kn-Jr-Kw-Jt",a.wa.Ba()),d,e=0;d=c[e];e++)d.style.color=a.Ha[a.Qa[e]].Tu;c=RZe(a);c=lb(c,function(a){return a.bgColor});d=Ima(KN,"JA-Kn-Jr-Kw");a.Aa=new NN(c,d,b);MN(a.Aa,6,1);PN(a,a.Aa,1);a.dQb();SZe(a,"Add custom color",1,"hcc");SZe(a,"Remove color",1,"hrc");PN(a,new jm(b),2);c=
new dm("In label list:",b);PN(a,c,2);TZe(a,"Show",2,"las");TZe(a,"Show if unread",2,"lsu");TZe(a,"Hide",2,"lh");PN(a,new jm(b),4);PN(a,new dm("In message list:",b),4);TZe(a,"Show",4,"ms");TZe(a,"Hide",4,"mh");PN(a,new jm(b),8);SZe(a,"Edit",8,"hrn");SZe(a,"Remove label",8,"ld");b=new fm("Add sublabel","lac",b);PN(a,b,8);UZe(a);a.Wa.Qxb(a.ha)},PZe=function(a,b){var c=Ima(KN,"JA-Kn-Jr-Kw");a.wa=new NN(VZe(a),c,b);MN(a.wa,6)},VZe=function(a){var b=lb(a.Ha,function(a){return a.bgColor}),c=b.length/4,b=
Cb(b.slice(0,c),b.slice(2*c,3*c),b.slice(c,2*c),b.slice(3*c,4*c)),d=0,e=lb(b,function(){return d++});a.Qa=Cb(e.slice(0,c),e.slice(2*c,3*c),e.slice(c,2*c),e.slice(3*c,4*c));return b},PN=function(a,b,c,d,e){if(a.Wa.cLb(c)&&!(c in a.Fa)){var g=a.Wa.xdb(c);a.Fa[c]=g;a.ha.tb(g,!0);a.Ga[c]||(a.Ga[c]=[]);a.Ga[c].push(g)}g=c in a.Fa?a.Fa[c].Ic():a.ha;e?g.ri(b,0,!0):g.tb(b,!0);d&&a.Da.set(d,b);a.Ga[c]||(a.Ga[c]=[]);a.Ga[c].push(b)},TZe=function(a,b,c,d){b=new MSe(b,d,a.ha.Ka());PN(a,b,c,d);return b},SZe=function(a,
b,c,d){b=new fm(b,d,a.ha.Ka());PN(a,b,c,d);return b},QZe=function(a,b){for(var c=Le(null,"JA-Kn-Jr-Kw-axF",b.Ba()),d=0,e=c.length;d<e;d++)qn(c[d],0==d%2?"qb":"pR")},UZe=function(a){wd(a.ha,"beforeshow",a.Gc,!1,a);wd(a.ha,"show",a.yLc,!1,a);wd(a.ha,"hide",a.vLc,!1,a);wd(a.ha,"action",a.TXc,!1,a);wd(a.wa,"action",a.zzb,!1,a);wd(a.Aa,"action",a.zzb,!1,a)};
ON.prototype.Gc=function(){for(var a=this.ra,b=Le(void 0,"JA-Kn-Jr-Kw-Jt",this.wa.Ba()),c=this.wa.ra,d,e=0;d=b[e];e++)c[e]==ALd(a)?(rf(d,""),qn(d.parentNode,"JA-Kn-Jr-Kw-Jn-KO")):(rf(d,"a"),rn(d.parentNode,"JA-Kn-Jr-Kw-Jn-KO"));a=this.ra;c=DZe(this.Ca,a.getId());b=this.Wa.pva(a);k(b)||(b=13);c&&(b|=2);var c=0,g;for(g in this.Ga){d=this.Ga[g];for(var e=0,h;h=d[e];e++){var l=!c&&h instanceof jm;(l=!!(b&g)&&!l)&&c++;h.setVisible(l,!0)}}EZe(a)||(h=this.Da.get("lsu"),h.setVisible(!1));DZe(this.Ca,this.ra.getId())&&
(g=this.ra.Ga,WZe(this,"las",2==g||1==g),WZe(this,"lsu",4==g),WZe(this,"lh",0==g));g=this.ra.wa;WZe(this,"ms",g);WZe(this,"mh",!g);this.Wa.updateMenuItems(this.ra);qn(this.ha.Wt,"aj1")};var WZe=function(a,b,c){(a=a.Da.get(b))&&a.Wf(c)};f=ON.prototype;f.yLc=function(){var a=this.ha.Wt;u&&Mqa(this.ha,a);this.ha.Nk().focus()};f.vLc=function(){rn(this.ha.Wt,"aj1")};
f.TXc=function(a){var b=this.ra,c=this.Dp;a=a.target;this.ra=null;if(Ij(a,16)&&!a.ij())a.Wf(!0);else if(!this.Wa.yw(b,c,a))switch(a.Zf()){case "hcc":(new MZe(this.La(),b,c,m(this.dQb,this))).setVisible(!0);break;case "hrc":vZe(c,b);break;case "hrn":wZe(c,b);break;case "las":yZe(c,b,2);break;case "lsu":yZe(c,b,4);break;case "lh":yZe(c,b,0);break;case "ms":xZe(c,[b],!0);break;case "mh":xZe(c,[b],!1);break;case "ld":c.Rv(b);break;case "lac":o3d(this.xd,m(c.YBa,c),b)}};
f.zzb=function(a){var b=this.ra,c=a.target.Ch();a=en(nh(c,"background-color")).OR;c=en(nh(c,"color")).OR;a=this.Ia.eW(c,a)||void 0;vZe(this.Dp,b,a);this.ha.hide();this.ra=null};f.dQb=function(){var a=RZe(this),b=lb(a,function(a){return a.bgColor});lZe(this.Aa,b);for(var b=Le(null,"JA-Kn-Jr-Kw-Jt",this.Aa.Ba()),c=0,d=b.length;c<d&&c<a.length;c++)b[c].style.color=a[c].Tu,rf(b[c],"a")};
var RZe=function(a){for(var b=nLd(a.Ia).zc(),c=[],d=b.length-1;0<=d;d--){var e=b[d];if(!XZe(a,e)&&(c.push(e),6<=c.length))break}return c},XZe=function(a,b){return 0<=pb(a.Ha,function(a){return a.bgColor==b.bgColor&&a.Tu==b.Tu})};AA(zA(),27,function(){return 9});AA(zA(),28,function(){return 8});ON.prototype.La=function(){return this.xd};ON.prototype.Ta=function(a){return!!this.ha&&this.ha.ix(a)}; ON.prototype.Sa=function(){this.ha&&(Cd(this.ha),Cd(this.wa),Cd(this.Aa),this.ha.dispose(),this.wa.dispose(),this.Aa.dispose());x(this.Ra);ON.Ea.Sa.call(this)};
hi(K.Ma(),function(a){rj(a,zoa,function(a){return new YZe(a)})});var YZe=function(a){v.call(this);this.Oa=a};r(YZe,v);YZe.prototype.ha=function(){return new EN(this.Oa,16)};YZe.prototype.ra=function(a,b){return new ON(this.Oa,a,b)};var QN=function(a){Pi.call(this,a);this.Ph=AD(a);this.Fa=new B(this);this.Xa=a.get(uia);this.nb=!1};r(QN,Pi);QN.prototype.init=function(){this.Yq(zB(this.getContext()).yf())};QN.prototype.jl=function(){return this.nb};QN.prototype.yc=function(a){if(!this.label)return null;var b;b=this.Ka().createElement("div");b.className="lD";Ee(b,NLd(this.Ia,this.label).Df());ZZe(this,a,b);return b};var $Ze=function(a){CN(a.Da);a.Da.Ug(a.Aa().Ba("l"));a.Da.init();a.Fa.listen(a.Da,"dragover",a.Xc)};
QN.prototype.Xc=function(a){this.Aa().QL(!0);a=a.ra;var b=a.Ff;b&&a_e(a,b);this.Yb&&(this.label?MB(this.label)&&b_e(this,this.label):this.Qzb(),yXe(a),a.N4(),this.Yb=!1)};QN.prototype.Qzb=function(){};
var c_e=function(a,b,c){var d=HB(a.Ia,b.wa.data);a.label=d;var e=a.Aa(),g=a.Fa;c&&(MB(d)?(b_e(a),g.listen(a.Da,["dragover","dragout"],a.Qb),g.listen(a.Da,"drop",a.EAa),n$d(e,!0)):b_e(a,d),$Ze(a,MB(d)));g.listen(b.ra,"dragend",a.Kc);AZe(e,b.wa.data,b.wa.element,!0)},b_e=function(a,b){CN(a.Ja);if(b){var c=a.Aa(),d=a.Fa;a.Ja.Ug(MB(b)?c.Ba("m"):c.Da[1]);d.listen(a.Ja,["dragover","dragout"],a.Qb);d.listen(a.Ja,"drop",a.EAa)}a.Ja.init()};
QN.prototype.Qb=function(a){var b=oLd(this.Ia.ha),c=b.bgColor,b=b.Tu;if("dragover"==a.type)var d=c,c=b,b=d;a=Le("div","at",a.ra.Ff.target)[0];d=a.firstChild.firstChild;a.style.backgroundColor=c;d.style.color=b};QN.prototype.EAa=function(a){AZe(this.Aa(),a.wa.data,a.wa.element,!1)};QN.prototype.Kc=function(a){var b=this.Aa();n$d(b,!1);AZe(b,a.wa.data,a.wa.element,!1);this.label=null;d_e(this,a)};
var e_e=function(a,b){if(0<a.Xa.ha)return b.preventDefault(),!1;a.Xa.ha++;a.Rb=b.ra;var c=a.Aa();c.Ja=!0;c.nb=!l$d(c);return a.Yb=!0},ZZe=function(a,b,c){mh(a.Ph.ha,"cursor",f_e);mh(c,"cursor",f_e);u&&(a.Md=nh(b,"cursor"),a.Ra=b,mh(b,"cursor",f_e))},d_e=function(a){mh(a.Ph.ha,"cursor","");u&&mh(a.Ra,"cursor",a.Md);a.Rb=null;a.Fa.removeAll();var b=a.Aa();b.Ja=!1;b.nb&&b.QL(!1);a=a.Xa;0!=a.ha&&a.ha--};
QN.prototype.Yq=function(a){if(a){if(a=(a=this.Rb)&&a.Ff){var b=new sd;a.Ca(b,!0)}if(!this.nb&&this.Aa()){this.nb=!0;a=SD(this.Db);b="f"==this.Cb.ha?10:60;this.ha=new RN(a,a,m(this.Fc,this),-1,-1,b);var c=m(this.yc,this);this.wa=new RN(a,a,c,-1,-1,b);this.Ca=new RN(a,a,c,-1,-1,b);this.Ta=new SN;this.Da=new SN;this.Ja=new SN;a=dUd(this.Db);this.ha.Xc=a;this.wa.Xc=a;this.Ca.Xc=a;BN(this.ha,this.wa);BN(this.ha,this.Ta);BN(this.ha,this.Da);this.Wa.bbb(this.ha,0);BN(this.wa,this.Ja);BN(this.wa,this.Da);
BN(this.wa,this.ha);BN(this.Ca,this.Ja);BN(this.Ca,this.Da);this.ha.Mf(this);this.wa.Mf(this);this.Ca.Mf(this);this.Wb();this.getHandler().listen(this.Za,"qd",this.qe);this.getHandler().listen(this.Za,"fb",this.Wb);this.getHandler().listen(this.ha,"dragstart",this.kd);this.getHandler().listen(this.wa,"dragstart",this.$Hc);this.getHandler().listen(this.Ca,"dragstart",this.$Oc)}}};QN.prototype.Sa=function(){QN.Ea.Sa.call(this);this.Fa.dispose()};
var SN=function(){AN.call(this)};r(SN,AN);SN.prototype.Ug=function(a,b){var c=new zN(a,b);g_e(this,c)};var g_e=function(a,b){b.Xf(a);a.ek.push(b);a.jl()&&a.tja(b)};SN.prototype.removeItem=function(a){a=Je(a);for(var b,c=0;b=this.ek[c];c++)if(b.element==a){this.ek.splice(c,1);this.mga(b);break}};
var TN=function(a,b,c){v.call(this);this.Ha=!1;this.Fa=!0;this.ha=a;this.ra=new Sd(50);this.Pa=new B(this);this.Ga=new Ae;this.Ca=Hh(a);this.qA=b||0;if(b){if(a=this.Ca.clone(),b=this.qA){var d=Math.min(b,.25*a.height);a.top+=d;a.height-=2*d;b=Math.min(b,.25*a.width);a.left+=b;a.width-=2*b}}else a=this.Ca;this.wa=a;c||this.Pa.listen(He(this.ha),"mousemove",this.Da);this.Pa.listen(this.ra,"tick",this.Ia)};r(TN,v);TN.prototype.Ia=function(){this.ha.scrollTop+=this.Ga.y;this.ha.scrollLeft+=this.Ga.x};
TN.prototype.Da=function(a){var b=this.Fa?this.Aa(a.clientX,this.wa.left,this.wa.width):0,c=this.Aa(a.clientY,this.wa.top,this.wa.height);this.Ga.x=b;this.Ga.y=c;!(b=!b&&!c)&&(b=this.Ha)&&(b=a.clientX,a=a.clientY,c=this.Ca,b=!(c.left<=b&&c.left+c.width>=b&&c.top<=a&&c.top+c.height>=a));b?this.ra.stop():this.ra.enabled||this.ra.start()};TN.prototype.Aa=function(a,b,c){var d=0;a<b?d=-8:a>b+c&&(d=8);return d};TN.prototype.Sa=function(){TN.Ea.Sa.call(this);this.Pa.dispose();this.ra.dispose()};
var UN=function(a,b,c){Mm.call(this,a);this.Da=b;this.Wb=c};r(UN,Mm);UN.prototype.Za=function(){UN.Ea.Za.call(this);h_e(this)};UN.prototype.Sa=function(){x(this.Va);x(this.Aa);UN.Ea.Sa.call(this)};UN.prototype.Qa=function(a,b,c,d){UN.Ea.Qa.call(this,a,b,c,d);d||this.Va.Da(a)};var h_e=function(a){x(a.Va);x(a.Aa);a.Va=new i_e(a.Da,a.Wb,!0);a.Va.Fa=!1;a.Aa=new co(a.target);a.getHandler().listen(a.Aa,"mousewheel",a.Yb)}; UN.prototype.Yb=function(a){this.Da.scrollTop+=10*a.deltaY;this.Da.scrollLeft+=10*a.wa};var i_e=function(a,b,c){TN.call(this,a,b,c)};r(i_e,TN);i_e.prototype.Aa=function(a,b,c){var d=0;a<b?d=-20:a>b+c&&(d=20);return d};
var RN=function(a,b,c,d,e,g){AN.call(this);this.ra=a;this.wa=b;this.Ca=c;this.Ja=d;this.Ta=e;this.Ia=g||60};r(RN,SN);f=RN.prototype;f.nUa=!1;f.tja=function(a){wd(a.element,"MSPointerDown",this.bxb);RN.Ea.tja.call(this,a)};f.mga=function(a){Ad(a.element,"MSPointerDown",this.bxb);RN.Ea.mga.call(this,a)};f.bxb=function(a){var b=a.Gf;b.pointerType==b.MSPOINTER_TYPE_TOUCH&&(a.preventDefault(),a.stopPropagation())};f.iMa=function(a){return this.Ca(a)};
f.Hhb=function(a,b,c){a=this.EPa(a,b,c);b.style.position="absolute";b.style.left=a.x+"px";b.style.top=a.y+"px";b=new UN(b,this.wa,this.Ia);a_e(this,b);b.nb=!0;return b};var a_e=function(a,b){var c=Gh(b.target);b.Ta=new kh(0,0,a.ra.scrollWidth-c.width,a.ra.scrollHeight-c.height)};f=RN.prototype;f.EPa=function(a,b,c){b=this.Ja;a=Df(Ie(a));return new Ae(c.clientX+b+a.x,c.clientY+this.Ta+a.y)};f.l2=function(a,b){this.nUa=!0;RN.Ea.l2.call(this,a,b)};
f.LW=function(a){this.Fa&&this.Fa.wa&&(this.nUa=!1);RN.Ea.LW.call(this,a)};f.Gbb=function(a){a?this.lga():(a=this.Aa,this.ha=new hn(this.Ha,[this.Ha.offsetLeft,this.Ha.offsetTop],[a.Ha.x,a.Ha.y],300,um),wd(this.ha,"end",this.lga,!1,this),this.ha.play())};f.lga=function(){RN.Ea.lga.call(this);this.ha&&(Cd(this.ha),this.ha.dispose(),this.ha=void 0)};var j_e=function(a,b){a.wa=b;var c=a.Ff;c&&b!=c.Da&&(c.Da=b,h_e(c))};RN.prototype.N4=function(){RN.Ea.N4.call(this);var a=this.Ff;a&&h_e(a)};
var k_e=function(a){this.service=a};r(k_e,il);f=k_e.prototype;f.bbb=ol();f.kPa=kl();f.$Fb=ol();f.nDa=ol();f.ZFb=ol();f.dispose=ol();var l_e=function(a){this.ra=a},m_e=function(a,b){var c=a.ra.getSelection();c.yg(b)||(a.ha=c.getSelected(),a.ha.set(b,!1),sz(c),rFd(c,b,!0))},n_e=function(a){var b=a.ra.getSelection();a.ha&&(b.Tj(a.ha),delete a.ha)};var o_e=function(a){this.ra=a};r(o_e,il);o_e.prototype.ha=ml();var p_e=function(a,b,c,d,e){this.wa=a;this.ha=b;this.Cc=c;this.Hc=d;this.ra=e;pl(this)};jl(o_e,p_e);var q_e=["all","chats","circle","drafts","sent"],r_e=[8,3,10,16],s_e=function(a){return(a.Hc?Tz(a.Hc):"")||""};p_e.prototype.Kg=function(){return this.Cc};
var VN=function(a){QN.call(this,a);this.Db=QD(a);this.Dp=new EN(a,21);this.Za=dE(a);this.Sd=GH(a);this.Ia=DB(a);this.Cb=a.get(kg);this.Ha=[];pl(this)};r(VN,QN);jl(k_e,VN);var t_e=["^i","^t","^k","^s"],f_e=T7d("-moz-grabbing","//ssl.gstatic.com/ui/v1/icons/mail/images/2/closedhand.cur","move");VN.prototype.init=function(){VN.Ea.init.call(this);this.getHandler().listen(this.Za,"ec",this.Qoc);this.getHandler().ud(this.Sd,"Dd",this.auc)};VN.prototype.Aa=function(){return aHe(this.getContext())};
VN.prototype.qe=function(a){CN(this.ha);this.He=a.ra;u_e(this,a.target);var b=new zN(a.element);u&&Nh(a.element,!0);g_e(this.ha,b);xXe(b,a.ha,b.element);a.ha.shiftKey&&a.preventDefault()};
VN.prototype.Wb=function(){var a=this.Aa();if(a){var b=l$d(a)?void 0:1;CN(this.wa);for(var c=BZe(a,[],!1,b),d,e=0;d=c[e];e++)this.wa.Ug(d.element,d.label);this.wa.init();"f"==this.Cb.ha&&(d=a.ha&&a.ha.$b()&&!a.gS()?a.vD[2][2].Ba():a.Aa,j_e(this.ha,d));a=BZe(a,[],!0,b);CN(this.Ca);for(e=0;d=a[e];e++)DZe(this.Ia,d.label)&&this.Ca.Ug(d.element,d.label);this.Ca.init()}};
var v_e=function(a,b){var c=Db(t_e),d=Nb(a.Wa.kPa());0<d.length&&(c=Cb(c,d),Ib(c));d=b?void 0:1;D6d(a.Va.ra)&&Ab(c,"^s");var e=s_e(a.Qa);(e&&NB(e)||PB(e))&&Ab(c,e);switch(e){case "^r":Ab(c,"^s")}CN(a.Ta);for(var d=CZe(a.Aa(),[],!0,d),g=0;e=d[g];g++)sb(c,e.label)&&a.Ta.Ug(e.element,e.label);a.Ta.init()};
VN.prototype.Fc=function(a){var b=this.Ka().createElement("div");b.className="lE";var c=this.ra.Ec(),d={fsa:H6d(this.ra,76),A8b:c&&!Uz(c)&&!sb(q_e,c.getType())},c="",d=d.A8b?In(new Hn("{CONVERSATION_COUNT_1,plural,=1{Move 1 conversation}other{Move {CONVERSATION_COUNT_2} conversations}}"),{CONVERSATION_COUNT_1:d.fsa,CONVERSATION_COUNT_2:M(d.fsa)}):In(new Hn("{CONVERSATION_COUNT_1,plural,=1{Label 1 conversation}other{Label {CONVERSATION_COUNT_2} conversations}}"),{CONVERSATION_COUNT_1:d.fsa,CONVERSATION_COUNT_2:M(d.fsa)}),
c=c+d,c=L(c);oi(b,Yma,{className:"lC",content:c});ZZe(this,a,b);return b};VN.prototype.kd=function(a){e_e(this,a)&&(v_e(this,l$d(this.Aa())),m_e(this.Va,this.He.Re()),this.Fa.listen(this.ha,"dragend",this.uPc),w_e(this,this.wa),w_e(this,this.Ta),this.Wa.$Fb(0,a.ra),$Ze(this,!1))};var w_e=function(a,b){a.Fa.listen(b,"drop",a.vPc).listen(b,["dragover","dragout"],a.zAb)};f=VN.prototype;
f.vPc=function(a){var b=a.ha.data,c=s_e(this.Qa),d=x_e(this,c),e=x_e(this,b),c=YB(this.getContext()),d=d+"-"+e;dTd(c,Zx(hxa)+d);AZe(this.Aa(),b,a.ha.element,!1);a=this.Qa;d=a.Hc;c=Tz(d);d=d&&d.getType();if(b&&c!=b){e=76;if(NB(b))switch(b){case "^i":e=8;break;case "^t":if(!c||sb(q_e,d))e=3;break;case "^s":e=9;break;case "^k":e=10,"drafts"==d&&(e=16)}else if(!c||sb(q_e,d))e=12;c=e}else c=null;if(c){var g;sb(r_e,c)?g=null:g=9==c?"msp":b;a.ha.Rp(c,g)}};
f.uPc=function(a){this.ha.nUa&&sD(YB(this.getContext()),kxa);d_e(this,a);this.Wa.ZFb(a);n_e(this.Va)};f.Qzb=function(){v_e(this,!0)};f.EAa=function(a){VN.Ea.EAa.call(this,a);a=this.label;yZe(this.Dp,a,MB(a)?0:2)};f.$Oc=function(a){e_e(this,a)&&c_e(this,a,DZe(this.Ia,a.wa.data))};
f.$Hc=function(a){if(e_e(this,a)){c_e(this,a,DZe(this.Ia,a.wa.data));CN(this.ha);this.ra&&this.ra.Kg().iua(m(function(a){this.ha.Ug(a)},this));for(a=0;a<this.Ha.length;a++)this.ha.Ug(this.Ha[a].ha);a=this.Fa;a.listen(this.ha,"drop",this.ZHc);a.listen(this.ha,["dragover","dragout"],this.zAb)}};
f.ZHc=function(a){for(var b=0;b<this.Ha.length;b++){var c=this.Ha[b];if(c.ha==a.ha.element){c.Ga.call(c.Bg,this.label.getName());return}}if(this.ra){b=a.ha.element;this.Qa.Cc.Vn().qx.l8(b,"yQ",!1);var b=this.Qa,c=this.label.getName(),d=a.ha.element;a=b.Wa.ha(d);a||(d=b.Cc.Yua(d))&&(a=d.Re());a&&(m_e(b.ra,a),b.ha.Rp(12,c),n_e(b.ra));sD(YB(this.getContext()),ixa)}};
f.zAb=function(a){var b="dragover"==a.type;Py(a.ra.Ff.target,"lB",b);if(a.ha.data)AZe(this.Aa(),a.ha.data,a.ha.element,b);else if(this.ra&&"TR"==a.ha.element.tagName){var c=a.ha.element;this.Qa.Cc.Vn().qx.l8(c,"yQ",b)}for(c=0;c<this.Ha.length;c++){var d=this.Ha[c];d.ha==a.ha.element&&(b&&d.wa&&d.wa.call(d.Bg),!b&&d.ra&&d.ra.call(d.Bg))}};
f.Yq=function(a){VN.Ea.Yq.call(this,a);this.Va=this.Qa=this.ra=null;a&&(K.Ma(),a instanceof DG&&u_e(this,a));if("f"==this.Cb.ha&&this.jl()){var b=this.wa;AXe(b);b.Qa=[];b=this.Ca;AXe(b);b.Qa=[];b=this.ha;AXe(b);b.Qa=[];if(b=this.Aa()){var c=b.Aa;c&&(zZe(this.ha,c),b.gS()||zZe(this.ha,b.vD[2][2].Ba()),j_e(this.ha,c))}a instanceof DG&&(b=SD(this.Db,a.Kg().Ba()),zZe(this.wa,b),zZe(this.Ca,b),this.Wa.nDa(0,this.ha,a),this.Wa.nDa(1,this.wa,a),this.Wa.nDa(2,this.Ca,a),j_e(this.wa,b),j_e(this.Ca,b))}};
f.Qoc=function(a){this.Yq(a.zD)};f.auc=function(){this.Yq(this.Za.yf())};var u_e=function(a,b){a.ra=b;a.Va=new l_e(a.ra.Qb.ima());a.Qa=new p_e(a.Ia,a.ra,a.ra.Kg(),a.ra.Ec(),a.Va)},x_e=function(a,b){return""==b?"s":NB(b)?b:"c"};VN.prototype.Sa=function(){VN.Ea.Sa.call(this);this.jl()&&(CN(this.wa),CN(this.Ca),CN(this.Ta));this.Wa.dispose()};VN.prototype.Ie=function(){this.ha&&(yXe(this.ha),this.ha.N4(),yXe(this.wa),this.wa.N4())};
VN.prototype.Ob=function(a,b,c,d,e,g){a.isDisposed()||(b=new y_e(b,c,d,e,g),this.Ha.push(b),md(a,m(this.Ne,this,b),this))};VN.prototype.Ne=function(a){Ab(this.Ha,a)};var y_e=function(a,b,c,d,e){this.ha=a;this.Bg=b;this.Ga=c;this.wa=d||null;this.ra=e||null};
hi(K.Ma(),function(a){rj(a,$k,function(a){a=new VN(a);a.init();return a})});

var z_e=function(a){this.ha=a;this.wa=SC(FB(DB(this.ha.La())));this.ra=YB(a.La())};Q(z_e,NZe);z_e.prototype.Qxb=function(a){a=a.Ka();a=new fm("","ec",a);PN(this.ha,a,16,"ec",!0)};z_e.prototype.yw=function(a,b,c){return"ec"==c.Zf()?(b=new BAe(this.ha.La()),CAe(b),DAe(b,"^cff"==a.getId(),a.jf(),a.getId().substring(4)),this.ra.wb(fCa),!0):!1};z_e.prototype.pva=function(a){if("^cff"==a.getId())return 16;if(Ia(a.getId(),"^cf_"))return 20}; z_e.prototype.updateMenuItems=function(a){if(a.Wq()){var b=this.ha.Da.get("ec");b&&b.or("^cff"==a.getId()?"Edit circles":"Edit circle")}};




var A_e=function(a){this.ha=a};Q(A_e,NZe);A_e.prototype.pva=function(a){if("^sl_root"==a.getId())return 2;if(Ia(a.getId(),"^smartlabel_"))return 5};var B_e=function(a){this.service=a};Q(B_e,k_e);B_e.prototype.kPa=function(){return iKd};
var D_e=function(a){this.service=a;var b=a.La();this.Bd=zE(b);this.Da=QD(a.getContext());this.ra=new B(this);this.Ca=new PK(b);this.Ia=YB(b)};Q(D_e,k_e);f=D_e.prototype;f.Aoa=[];f.bbb=function(a,b){0==b&&(this.ha=new SN,BN(a,this.ha))};
f.$Fb=function(a,b){if(0==a){CN(this.ha);var c=Me("aAy",this.service.ra.Ba());if(0!=c.length){for(var d=0;d<c.length;d++)this.ha.Ug(c[d],{QXa:d});this.ha.init();E_e(this,!0);c=SD(this.Da,this.service.ra.Kg().Ba());d=this.service.Aa().Aa;j_e(b,c);this.wa=0;this.ra.listen(this.ha,"drop",this.Ha).listen(this.ha,["dragover","dragout"],this.Fa).listen(c,"mouseover",m(this.Aa,this,b,0)).listen(d,"mouseover",m(this.Aa,this,b,1))}}};
f.nDa=function(a,b,c){0==a&&NE(this.Bd)&&"inbox"==c.Ec().getType()&&(a=SD(this.Da,this.service.ra.Kg().Ba()),zZe(b,a))};f.ZFb=function(){0<this.Aoa.length&&E_e(this,!1);this.ra.removeAll()};f.dispose=function(){x(this.ha);x(this.ra)};
var E_e=function(a,b){var c=a.service.ra.Ba(),c=Me("aAy",c);if(0!=c.length){for(var d=a.service.ra.Kg().vr,e=0<a.Aoa.length,g=0,h;h=c[g];g++){var l=a,n=h;h=g;var p=b,w=e;h!=d&&(Py(n,"aE1",p),n=Ne("aKn",n),p?(l.Aoa[h]=n&&n.innerHTML?L(n.innerHTML):null,rf(n,"Drag here to move messages")):w&&lA(n,l.Aoa[h]))}b||(a.Aoa.length=0)}};D_e.prototype.Aa=function(a,b,c){b!=this.wa&&(j_e(a,c.currentTarget),this.wa=b)};
D_e.prototype.Ha=function(a){var b=this.service.ra.Kg().vr;if(a.ha.data.QXa!=b){var c=a.ha.element;Py(c,"aDO",!1);Py(c,"aDN",!1);E_e(this,!1);b=PXd(this.Bd)[b];c=PXd(this.Bd)[a.ha.data.QXa];a=wBe(this.Ca,b);b=wBe(this.Ca,c);if(c=sBe(b)[0])this.Ia.$d(XJa,qKd(a)||null,qKd(b)||null),this.service.ra.Rp(c,{xIa:33,Yka:a})}};D_e.prototype.Fa=function(a){var b="dragover"==a.type;Py(a.ra.Ff.target,"lB",b);var c=a.ha.element;a=a.ha.data.QXa!=this.service.ra.Kg().vr;Py(c,"aDO",b);a&&Py(c,"aDN",b)};

var F_e=function(a){return L("<span>"+M(a.M$c)+' <span class="aH5">'+M(a.G5c)+"</span></span>")};var G_e=function(a){this.ha=a;this.Jb=eo(a.La()).Ka()};Q(G_e,NZe);G_e.prototype.cLb=function(a){if(1==a)return!0};G_e.prototype.xdb=function(a){if(1==a)return a=qi(F_e,{M$c:"Label color",G5c:"a"}),a=new VM(a,null,this.Jb),qn(a.Ic().Ba(),"aka"),a};G_e.prototype.updateMenuItems=function(a){var b=Af(this.Jb,"span","aH5")[0];b&&(b.style.color=zLd(a),b.style.backgroundColor=ALd(a))};

di(K.Ma(),"ml");gi(K.Ma(),"ml");
}catch(e){_DumpException(e)}
// Google Inc.
