window.languages["en"] = {
  nplurals: 2,
  plural: function (n) { return  (n != 1) },
  installation_close_confirm: "Are you sure you want to abort the installation? This can cause you computer to malfunction.",
  menu_create_recovery_point: "Create recovery point",
  menu_create_drivers_backup: "Create backup of drivers",
  menu_add_remove_programs: "Programs and Features",
  menu_device_manager: "Device Manager",
  menu_system_properties: "System",
  menu_display_properties: "Display",
  menu_power_options: "Power Options",
  menu_network_connections: "Network Connections",
  menu_computer_management: "Computer Management",
  menu_control_panel: "Control Panel",
  menu_disk_management: "Disk Management",
  menu_task_manager: "Task Manager",
  menu_cmd: "Command Prompt",
  start_title: "Automatic {{MODEL}} configuration",
  start_button_install: "Setup computer automatically",
  start_caption_1: "Your computer's performance will increase and it<br />will be ready for use, after automatic configuration",
  start_caption_2: "DriverPack will analyse your system, install required<br />drivers and software, and carry out diagnostics",
  start_expert_mode: "expert mode",
  start_drivers_title_0: "Will be installed {{COUNT}} driver",
  start_drivers_title_1: "Will be installed {{COUNT}} drivers",
  start_drivers_popover: "The Drivers for your computer have been selected and are ready to be installed. DriverPack will create a system restore point, before this takes place.",
  start_programs_title_0: "Will be installed {{COUNT}} app",
  start_programs_title_1: "Will be installed {{COUNT}} apps",
  start_programs_popover: "Recommended software for your computer: antiviruses, archivers, browsers, and driver utilities — everything that can be used to achieve a higher level of comfort.",
  start_diagnostics_title: "Diagnostics will take place",
  start_diagnostics_popover: "After installation and system restart, DriverPack will launch diagnostics to test the functionality of devices.",
  start_diagnostics_network: "Checking your network connection",
  start_diagnostics_video: "Checking your graphics card",
  start_diagnostics_audio: "Checking your sound card",
  start_diagnostics_other: "Checking other devices",
  menu_install_drivers: "Install drivers on the computer",
  menu_drivers: "Drivers",
  menu_install_programs: "Install basic software on the computer",
  menu_programs: "Software",
  menu_protect_title: "Assistant for your antivirus",
  menu_protect: "Security",
  menu_computer_diagnostics: "Computer diagnostics",
  menu_diagnostics: "Diagnostics",
  menu_bugreport: "Report a bug",
  drivers_section_title: "Driver installation",
  drivers_install_drivers: "Install drivers",
  drivers_column_drivers: "Drivers",
  drivers_utilities: "Utilities",
  programs_column_program: "Programs",
  programs_column_type: "Type",
  drivers_driver_counter: "Drivers recommended for update and installation",
  drivers_program_counter: "Recommended programs",
  drivers_button_install_all: "Install automatically",
  programs_button_install: "Install",
  drivers_row_update: "Update",
  drivers_row_reinstall: "Reinstall",
  popover_device_info: "Device information",
  popover_current_driver: "Current driver",
  popover_alternative_driver: "Alternate driver",
  popover_recommended_driver: "Recommended driver",
  programs_header_text_title: "All the software you need in one place",
  programs_btn_install_all: "Install needed programs <b>({{COUNT}})</b>",
  programs_header_text_caption: "Forget about looking for programs individually! Now you can install everything you need in one click.",
  programs_btn_install_single: "Install",
  programs_btn_installed_single: "Installed",
  protect_header_title: "DriverPack Protect – the assistant for your antivirus",
  protect_header_caption: "DriverPack Protect protects your computer where your antivirus fails: malware, adware and unwanted software detection, removing and blocking",
  protect_remove_all_btn: "Remove unwanted software <b>({{COUNT}})</b>",
  protect_state_success: "No unwanted software detected",
  protect_state_success_caption: "There is no unwanted software on your computer",
  protect_state_warn_unchecked: "Unwanted software detected",
  protect_state_warn_unchecked_caption: "Select the items to remove in the list below",
  protect_state_warn: "Unwanted software to be removed: {{COUNT}} pcs.",
  protect_state_warn_caption: "Google Chrome browser will be cleared",
  protect_state_err: "For DriverPack Protect usage you must connect your computer to the Internet and restart DriverPack",
  protect_show_more: "show more",
  protect_row_rating: "Rating:",
  protect_row_size: "Size:",
  protect_row_publisher: "Publisher:",
  protect_row_version: "Version:",
  protect_row_install_date: "Installation date:",
  protect_rating_level_large: "recommended for deleting",
  protect_rating_level_middle: "can be deleted",
  protect_rating_level_small: "can be skipped",
  protect_rating_level_large_caption: "This program is recommended for deleting as over 70% of users do so.",
  protect_uninstall_single: "delete",
  diagnostics_section_title: "System diagnostics",
  loading_install_software: "Software installation",
  loading_backup_drivers: "Creating backup of drivers",
  loading_button_finish: "Finish",
  loading_backup_done: "Driver backup successfully finished",
  loading_backup_failed: "An error occured while creating a backup of driver",
  about_noconnection: "DriverPack needs an Internet connection. <br> DriverPack will restart automatically when the computer connects to the Internet",
  about_run_error: "DriverPack Solution encountered a problem <br> <br> If a problem persists, please contact us: support@drp.su",
  loading_install_software_title: "Loading program...",
  loading_preparing: "Prepare for the application launch…",
  loading_system_scanning: "Checking PC configuration…",
  loading_sending_api_request: "Downloading data from cloud server…",
  loading_checking_installed_programs: "Analyzing software…",
  loading_ordering_drivers: "Forming drivers installation order…",
  installation_header_preparing: "Creating a restore point…",
  installation_header_title: "Setting up your computer…",
  installation_header_subtitle: "It may take some time, but&nbsp;it's worth it",
  installation_title_name: "Installing items",
  installation_title_button_settings: "Settings",
  driver_class_bluetooth: "Bluetooth",
  driver_class_cardreader: "CardReader",
  driver_class_chipset: "Chipset",
  driver_class_inputdev: "Input Device",
  driver_class_lan: "Network Card",
  driver_class_massstorage: "Mass Storage",
  driver_class_modem: "Modem",
  driver_class_monitor: "Monitor",
  driver_class_phone: "Smartphone",
  driver_class_sound: "Sound Card",
  driver_class_tvtuner: "TV-Tuner",
  driver_class_video: "Video Card",
  driver_class_webcamera: "WebCam",
  driver_class_wifi: "Wi-Fi",
  driver_class_other: "Peripheral devices",
  soft_category_archiver: "Work with archives",
  soft_category_browser: "Fast and secure Internet browsing",
  soft_category_viewer: "View images and documents",
  soft_category_messenger: "Free messaging, voice and video calls",
  soft_category_internet: "Internet tools",
  soft_category_player: "View movies and videos",
  soft_category_backup: "Data backup and protection",
  soft_category_antivirus: "Antivirus protection",
  soft_category_system: "System tools",
  soft_category_drivers: "Utilities for proper driver's functionality",
  installation_error_download: "Download error",
  installation_error_unzip: "Unpacking error",
  installation_error_install: "Installation error",
  installation_progress_stage_waiting: "Waiting to be downloaded",
  installation_progress_stage_downloading: "Downloading",
  installation_progress_downloading_speed: "speed",
  installation_progress_downloading_of: "of",
  installation_progress_stage_downloaded: "Waiting to be installed",
  installation_progress_stage_unzipping: "Unpacking",
  installation_progress_unzipping_unzipped: "unpacked",
  installation_progress_stage_installing: "Installation",
  installation_progress_stage_done: "Finish",
  installation_canceled: "Cancelled",
  loading_no_drivers: "Could not install drivers – please try running the installation again",
  loading_drivers_installed: "The drivers <span class='final_msg-marked'>({{SUCCESS}}/{{TOTAL}})</span> have been installed!",
  loading_soft_installed: "Selected programs were successfully installed",
  loading_reboot: "We recommend you reboot your computer after the installation is complete",
  loading_promo_label: "You can also try",
  loading_promo_button: "Try {{SOFTNAME}}",
  language_title: "English"
}