/* JS */ gapi.loaded_1(function(_){var window=this;
_.iF=function(a){_.Ft.call(this,a.ma);this.zh=a;this.Ys=null};_.C(_.iF,_.Ht);_.iF.prototype.open=function(){this.Ca.targetPos=this.Ca.targetPos||"top-start";this.Ca.anchorPos=this.Ca.anchorPos||"bottom-start";var a=this.Gg(),b=this.ma.Jb();b?(b.style.visibility="hidden",b.style.position="absolute",a.parentNode.appendChild(b)):this.zh.open()};_.iF.prototype.open=_.iF.prototype.open;
_.iF.prototype.Pd=function(){if(this.Ca.closeClickDetection){var a=this,b=function(b){_.Kt(a.ma.Jb(),b)||(a.ma.close(),a.Ys=null)};window.document.EX?(window.document.EX("click",b),this.Ys=function(){window.document.removeEventListener("click",b,!1)}):window.document.attachEvent&&(window.document.attachEvent("onclick",b),this.Ys=function(){window.document.detachEvent("onclick",b)})}var c=this.ma.Jb();window.document.getElementById(this.ma.id).style.height=this.ma.height+"px";var d=this.Gg();d&&_.Pt(c,
this.Ca.targetPos,d,this.Ca.anchorPos,{x:this.Ca.leftOffset||0,y:this.Ca.topOffset||0});c.style.visibility="visible"};_.iF.prototype.onready=_.iF.prototype.Pd;_.iF.prototype.close=function(){this.zh.close();this.Ys&&this.Ys()};_.iF.prototype.close=_.iF.prototype.close;
_.jF=function(a){_.Ft.call(this,a)};_.C(_.jF,_.Ht);var kF=["transition","WebkitTransition","MozTransition","OTranstion","msTransition"];_.jF.prototype.create=function(a){this.Qa=window.document.createElement("div");var b={position:"absolute",top:"-10000px",zIndex:_.Lt(this)};this.Ca.width&&(b.width=this.Ca.width+"px");for(var c in b)this.Qa.style[c]=b[c];(a||window.document.body).appendChild(this.Qa)};
_.jF.prototype.open=function(a){this.ma.rf("updateContainer",(0,_.u)(this.ym,this));this.create(a);this.ma.Jg(this.Qa);this.ma.eg(this.Qa)};_.jF.prototype.open=_.jF.prototype.open;_.jF.prototype.Pd=function(){var a=lF(this);if(a){var b=window.document.getElementById(this.ma.Ba());b.style.height=a.height+"px";b.style.width=a.width+"px";this.ma.width=a.width;this.ma.height=a.height;b.style.boxShadow="0 4px 16px rgba(0, 0, 0, 0.3)"}};_.jF.prototype.onready=_.jF.prototype.Pd;
_.jF.prototype.close=function(){this.Qa.parentNode&&this.Qa.parentNode.removeChild(this.Qa)};_.jF.prototype.close=_.jF.prototype.close;_.jF.prototype.ym=function(a,b,c){var d=this.ma.Jb();d&&(a?(this.hf(b,c),d.style.opacity=0,d.style.display="",window.setTimeout((0,_.u)(function(){mF(d,!0);d.style.opacity=1},this),0)):(d.style.display="none",mF(d,!1),d.style.opacity=0))};var mF=function(a,b){for(var c=0;c<kF.length;c++)a.style[kF[c]]=b?"opacity .13s linear":""};
_.jF.prototype.hf=function(a,b){var c=this.ma.Jd();a+=10;b+=10;if(_.H.Wa&&(c&&(c=_.bt(c.Jb(),window),a+=c.x,b+=c.y),c=lF(this))){var d=_.rs(window),e=_.qs(window.document);d.width&&(a=Math.min(a,d.width+e.x-c.width-8),b+c.height>d.height+e.y-8&&(b-=20+c.height,b=Math.max(b,Math.min(e.y+1,_.Et()-c.height))))}c=this.ma.Jb();c.style.left=a+"px";c.style.top=b+"px"}; var lF=function(a){return a.ma.width&&a.ma.height?{width:a.ma.width,height:a.ma.height}:(a=a.ma.kb())&&a.offsetWidth&&a.offsetHeight?{width:a.offsetWidth,height:a.offsetHeight}:null};
_.nF=function(a){_.Ft.call(this,a)};_.C(_.nF,_.Ht);_.nF.prototype.Bz=null;_.nF.prototype.aG=null;_.nF.prototype.Om=null;var oF={end:"start",left:"right",right:"left",start:"end"},pF={top:"bottom",bottom:"top"};_.nF.prototype.open=function(){var a=window.document.createElement("div");_.Q(a,{top:"-10000px",position:"absolute",zIndex:_.Lt(this)});this.Gg().parentNode.appendChild(a);this.ma.eg(a);this.ma.Jg(a)};_.nF.prototype.open=_.nF.prototype.open;
_.nF.prototype.Pd=function(){var a=window.document.getElementById(this.ma.id);a.style.height=this.ma.height+"px";a.style.width=this.ma.width+"px";a.style.boxShadow="0 4px 16px rgba(0, 0, 0, 0.3)";var b=this.ma.Jb();b.style.lineHeight=0;var c=this.Gg(),d=this.Ca.targetPos||"top-start",e=this.Ca.anchorPos||"bottom-start",f=this.Ca.leftOffset||0,h=this.Ca.topOffset||0;_.Pt(b,d,c,e,{x:f,y:h});var k=_.rs(window),l=_.qs(window.document),m=b.offsetLeft<l.x||b.offsetLeft+b.offsetWidth>k.width+l.x,k=b.offsetTop<
l.y||b.offsetTop+b.offsetHeight>k.height+l.y,d=qF(d,m,k),e=qF(e,m,k);_.Pt(b,d,c,e,{x:f*(m?-1:1),y:h*(k?-1:1)});b.style.visibility="visible";this.Bz=_.O(window.document,"mouseover",(0,_.u)(function(b){b.target===a&&this.Om&&(window.clearTimeout(this.Om),this.Om=null)},this));this.aG=_.O(window.document,"mouseout",(0,_.u)(function(b){b.target===a&&(this.Om=window.setTimeout((0,_.u)(this.ma.close,this.ma),1E3))},this))};_.nF.prototype.onready=_.nF.prototype.Pd;
var qF=function(a,b,c){a=a.split("-");for(var d=0;2>d;d++)b&&oF[a[d]]&&(a[d]=oF[a[d]]),c&&pF[a[d]]&&(a[d]=pF[a[d]]);return a.join("-")};_.nF.prototype.close=function(){this.Bz&&(_.Fh(this.Bz),_.Fh(this.aG),this.aG=this.Bz=null);this.Om&&(window.clearTimeout(this.Om),this.Om=null);_.nF.S.close.call(this)};_.nF.prototype.close=_.nF.prototype.close;

_.H.Hc("hover",function(a){return new _.jF(a)});_.H.Hc("hover-menu",function(a){return new _.nF(a)});_.H.Ua("float")||_.H.Hc("float",function(a){a=new _.jF(a);return a=new _.iF(a)});
});
// Google Inc.
