try{
fi(K.Ma(),"so");var C2=function(a){var b=a.La();this.Ae=zB(b);this.Jb=eo(b).Ka();this.ha=a;this.Ph=AD(b);this.lm=GH(b);this.Fa=QD(b);this.Ub=tA(b);this.yc=jE(b);this.Lb=nB(b);this.ra=hl(b).Pc();this.Da=pk(ok(b).Fb)};C2.prototype.wa=null;C2.prototype.Qb=function(){var a=this.ha,b=GH(a.getContext()).Od();hce(a,b,a.Ae.yf())};C2.prototype.onOverlayActive=C2.prototype.Qb;C2.prototype.Va=function(){return"ap6"};C2.prototype.getNativeIconClass=C2.prototype.Va;C2.prototype.Cb=function(){return IH.prototype.G9a};
C2.prototype.getSearchActionMessage=C2.prototype.Cb;C2.prototype.Ab=function(){var a=He(this.Ph.ha);a||(a=document);return a};C2.prototype.getDocument=C2.prototype.Ab;C2.prototype.Kc=function(){if(!this.wa){var a=this.Jb.Na("DIV",{style:"display:none"});this.wa=a;var b=this.Ph.ha;b||(b=document.body);b.appendChild(a)}return this.wa};C2.prototype.getOverlayElement=C2.prototype.Kc;C2.prototype.Wb=function(a,b){this.Ca(a,b,null,null)};C2.prototype.openResultByUrl=C2.prototype.Wb;
C2.prototype.Ca=function(a,b,c){if(!c){var d=b.lastIndexOf("/");0>d||(c=b.substr(d+1))}c&&(b=(b=(b=cE(this.ha.La()))&&b.wa)&&nVd(b),this.Ae.navigate({view:DC,search:Mz(a),Tqa:b,KEc:!0,aB:0,Tl:c}),Wh("fl",this.Ha,0,this))};C2.prototype.openResult=C2.prototype.Ca;C2.prototype.Ha=function(){this.ha.ha.blur()};C2.prototype.Yb=function(a){var b=this.ha.Ca;b&&b.Gl()?(b.update(!0),b.Nu(),b.Ia()):(a=AGd(Pz,a))?this.Ae.navigate({view:CC,search:a}):gce(this.ha);Wh("gl",this.Fa.ha,0,this.Fa)};
C2.prototype.performNativeSearch=C2.prototype.Yb;C2.prototype.Ja=function(){return"gmail"};C2.prototype.getClientName=C2.prototype.Ja;C2.prototype.Py=function(){return ea};C2.prototype.getVersion=C2.prototype.Py;var Q8g=function(a,b){var c=GA(a.ha.La()).Di();return(c=se(new ie(c.location),b))?String(c):""};C2.prototype.Fc=function(){return Q8g(this,"jsmode")};C2.prototype.getJsMode=C2.prototype.Fc;C2.prototype.Qa=function(){return Q8g(this,"cssmode")};C2.prototype.getCssMode=C2.prototype.Qa;
C2.prototype.zt=function(){return this.Ub.getData("pi:e")};C2.prototype.getLocale=C2.prototype.zt;C2.prototype.qe=function(){return $f()};C2.prototype.getSessionIndex=C2.prototype.qe;C2.prototype.log=function(){};C2.prototype.log=C2.prototype.log;C2.prototype.Ne=function(){var a=Q8g(this,"asfecb");return""==a?this.Ub.Hg(5278):"1"==a};C2.prototype.useCanary=C2.prototype.Ne;
C2.prototype.Xa=function(a){var b=0,c=0;"gbqfq"==a.id&&(c=-8,b=a.parentNode,b=b.offsetTop+b.offsetHeight-(a.offsetTop+a.offsetHeight)+1);return{top:b,left:c}};C2.prototype.getOffsets=C2.prototype.Xa;C2.prototype.Aa=function(){return!qA(this.Ub,1245)&&!this.ra.Gb(5839)&&this.ra.Gb(5628)&&!this.ra.Gb(5629)};C2.prototype.isDarkLaunch=C2.prototype.Aa;C2.prototype.Rb=function(){return this.Aa()||2==this.xl()&&!this.ra.Gb(5817)};C2.prototype.isOverlayDisabled=C2.prototype.Rb;
C2.prototype.xl=function(){var a=this.lm.Od();return a&&"contacts"==a.id?2:1};C2.prototype.getView=C2.prototype.xl;C2.prototype.Ia=function(){return!this.ha.Ca};C2.prototype.canDisplay=C2.prototype.Ia;C2.prototype.kd=function(a){kE(this.yc,a,{target:"_blank"},!0)};C2.prototype.openUntrustedWindow=C2.prototype.kd;C2.prototype.Of=function(){return qA(this.Ub,1245)||this.ra.Gb(5839)};C2.prototype.wantResults=C2.prototype.Of;
C2.prototype.ef=function(){return this.ra.Gb(5922)&&!!this.Da.qb("udc")&&30<this.Da.qb("aad")};C2.prototype.wantHistoryBubble=C2.prototype.ef;C2.prototype.He=function(){return!1};C2.prototype.showContactThumbnails=C2.prototype.He;var R8g=function(a,b,c){var d=new VA(a.ha.La());d.ra=!0;d.Fd(b,c);d.send();a.Lb.Fd(b,c)};C2.prototype.Ie=function(a){R8g(this,"ix_chst",a)};C2.prototype.setHistoryPrefShowTimestamp=C2.prototype.Ie;C2.prototype.Md=function(a){R8g(this,"ix_chsc",a)};
C2.prototype.setHistoryPrefShowCount=C2.prototype.Md;C2.prototype.Sd=function(a){R8g(this,"ix_chdt",a)};C2.prototype.setHistoryPrefDismissed=C2.prototype.Sd;C2.prototype.Gc=function(){return qB(this.Lb,"ix_chst")};C2.prototype.getHistoryPrefShowTimestamp=C2.prototype.Gc;C2.prototype.Ta=function(){return qB(this.Lb,"ix_chsc")};C2.prototype.getHistoryPrefShowCount=C2.prototype.Ta;C2.prototype.Ra=function(){return qB(this.Lb,"ix_chdt")};C2.prototype.getHistoryPrefDismissed=C2.prototype.Ra;
C2.prototype.Ob=function(){return"We are bringing you better, personalized autocomplete for search in "+(ma+(". Your searches in "+(ma+" will be added to your Web History, which you can delete, pause or resume at any time.")))};C2.prototype.getWebHistoryMainTextHtml=C2.prototype.Ob;C2.prototype.Im=function(){return this.Ub.Xd()};C2.prototype.getEmailAddress=C2.prototype.Im;C2.prototype.Xc=function(){};C2.prototype.getParameter=C2.prototype.Xc;
C2.prototype.Za=function(a){return a.Vy()?1101:a.Kr()?1102:a.jA()?1104:a.wm()?1103:0};C2.prototype.getNativeResultType=C2.prototype.Za;C2.prototype.nb=function(){return this.Ga()};C2.prototype.getRequestUri=C2.prototype.nb;C2.prototype.Ga=function(){return null};C2.prototype.getBaseRequestUri=C2.prototype.Ga;C2.prototype.Db=function(){return""};C2.prototype.getSubcorpus=C2.prototype.Db;
var S8g=function(){this.ha=this.tf=this.ra=null};S8g.prototype.Ga=function(a,b){this.ha?b&&b(this.ha):(this.ra=new C2(a),b&&(this.tf=b),a.La().get("A").NWa("cloudsearch").addCallback(this.wa,this))};S8g.prototype.wa=function(a){this.ha=a.install(this.ra);this.tf&&this.tf(this.ha)};
var T8g=function(){v.call(this)};r(T8g,Yh);$h(ai(K.Ma(),"so"),T8g);T8g.prototype.Zc=function(a){a.registerService("JmKzXe",new S8g(a))};



di(K.Ma(),"so");gi(K.Ma(),"so");
}catch(e){_DumpException(e)}
// Google Inc.
